src/header/mod.rs

compilation fix for rust version "rustc 0.13.0-nightly (7608dbad6 2014-12-31 10:06:21 -0800)"

compilation fix

---

src/http.rs

[New array syntax](https://github.com/rust-lang/rust/pull/20387).

Array syntax fallout

---

src/client/response.rs
src/http.rs
src/server/request.rs

Currently, when the chunk size is an invalid hex number (i.e. contains a non-hex digit), hyper would halt its parsing at the last valid hex digit and report this as the chunk size.
For example, the following would be the chunk sizes reported for some strings:
"X" => 0
"1X" => 1
"aY" => 10
"a;a" => 10 (only this should be correct!)
This fix makes it so that any chunk size, which cannot be parsed as a valid hex number, causes an `IoError`.
Additionally, the case where the chunk size is followed by a chunk extension is also handled -- the ";" token is allowed to immediately follow the chunk size, as it represents the delimiter between the size and the extensions.
The chunk extension parsing is (still) not fully compliant with the official syntax spec and accepts extensions deviating from it …

Fix chunk size parsing: handle invalid chunk sizes

---

src/header/common/content_type.rs

fixes invalid format of mime types

---

src/server/request.rs

server(feat): add a deconstruct method to Request.

---

src/header/shared/quality_item.rs

fix(headers): Don't display q if q=1 in quality item.

---

benches/client_mock_tcp.rs
src/header/common/authorization.rs
src/header/common/cache_control.rs
src/header/common/connection.rs
src/header/common/cookie.rs
src/header/common/date.rs
src/header/common/expires.rs
src/header/common/host.rs
src/header/common/if_modified_since.rs
src/header/common/last_modified.rs
src/header/common/set_cookie.rs
src/header/common/upgrade.rs
src/header/mod.rs
src/header/parsing.rs
src/header/shared/encoding.rs
src/header/shared/quality_item.rs
src/http.rs
src/method.rs

fix(rustup): update FromStr

---

src/net.rs

HttpAcceptor::accept()'s HTTPS logic passes IO errors from the underlying
SSL stream directly to the caller. Furthermore, the caller uses the
EndOfFile error code to detect that the server should stop accepting
connections. This means that if the TCP connection was succesfully
accepted, but an EOF condition was detected during the handshake, the
server will stop accepting connections and quit. This allows for a
trivial denial of service attack and can happen accidentally as well.
Change HttpAcceptor::accept such that if the TCP stream underlying
the SSL stream returns an EndOfFile error, change the error kind
to OtherIoError.
----
The way I fixed this is a bit ugly, but can't think of a nicer and easy way at the moment.
Suggestions welcome.
Cheers,
cyndis

fix(net): don't stop the server when an SSL handshake fails with EOF

---

src/header/shared/charset.rs

https://github.com/hyperium/hyper/pull/300#issuecomment-77097512

fix(header): Fix charset parsing bug.

---

src/header/common/cookie.rs

fixes: https://github.com/hyperium/hyper/issues/374

fix(headers): Fix overflow with empty cookies

---

src/buffer.rs
src/server/mod.rs

fix(buffer): get_buf to not return consumed part of buffer

---

src/buffer.rs

The results of benches/client.rs are below.
Before:
running 1 test
test bench_mock_hyper ... bench:    321609 ns/iter (+/- 18127)
After:
running 1 test
test bench_mock_hyper ... bench:    239319 ns/iter (+/- 29938)

perf(buffer): pull in std::io::BufReader improvements

---

CONTRIBUTING.md

See https://github.com/hyperium/hyper/pull/419

docs(contributing): Remove underscore from `BREAKING_CHANGE`

---

.travis.yml
src/server/listener.rs
src/server/mod.rs

Should build on both nightly and beta.

fix(server): Use thread::spawn instead of thread::scoped.

---

examples/hello.rs
examples/server.rs
src/server/response.rs

feat(server): add Response.send to write a sized body

---

src/client/request.rs

Adding more tests for request.

test(request): increasing test coverage of request module

---

src/header/common/connection.rs

test(connection): increasing test coverage of connection module

---

CONTRIBUTING.md

Only show easy issues that are open.

docs(CONTRIBUTING): link to open easy issues

---

src/header/mod.rs

Sorry about that!
r? @reem (or whoever)

Fix broken deserialization of headers.

---

src/header/common/connection.rs

fix(headers): case insensitive values for Connection header

---

src/server/mod.rs

I'm adding a feature to my webserver:  whenever the thread pool is getting too busy (say 4 out of 8 threads are occupied, possibly idly with keep-alive requests), we force Connection close on subsequent requests until the thread pool isn't so busy anymore.
To do this, I need hooks into the beginning and end of the connection loop.  The Handler handle function is per-request, not per-connection.
A very simple addition, but please consider the function names, comments, etc., as I have no preference for these.

feat(server): Add Handler per-connection hooks

---

src/http/h1.rs

When the Content-Length header is invalid, the Http11Message ends up
dropping the stream before returning the error. This causes a panic when
the `close_connection` method of the message is used later. This commit
fixes this by saving the stream onto the message instance before
returning the error. A regression test is also included.
Closes #646

fix(http): Make sure not to lose the stream when CL is invalid

---

src/server/response.rs

Previously, hyper was defaulting to Chunked which adds a Transfer-Encoding
header, whenever there was no Content-Length header. RFC 7230 section 3.3.1
reads:
...
A server MUST NOT send a Transfer-Encoding header field in any
response with a status code of 1xx (Informational) or 204 (No
Content). A server MUST NOT send a Transfer-Encoding header field in
any 2xx (Successful) response to a CONNECT request
...
This commit fixes the cases of 1xx (Informational), 204 (No Content) by
using the EmptyWriter. It also uses EmptyWriter for 304 (NotModified) which
should not have a body.
It does NOT address the case of responses to CONNECT requests, or to HEAD
requests which do not send a body.  These cases cannot be determined using
the data available in the response, and are left for future work.

fix(server): use EmptyWriter for status codes that have no body

---

src/http/h1.rs

@seanmonstar 
When the `HttpMessage` API was added and implemented for HTTP/1.1, we commented on the fact that the stream was being manually juggled in and out of `Option`s, leading to the possibility of losing the stream prematurely. At the time, I mentioned that I couldn't see how this could be avoided without resorting to some `unsafe` code. This was due to the fact that the `HttpMessage` trait methods require a `&mut self`, while the implementation needs to _move_ the stream object around.
I still think this is the case, but I think that with a minimal amount of unsafe code (3 lines which could have easily been a single one), a safe API can be exposed that guarantees that the stream will never be dropped (and eliminating the panics that this could lead to).
It hinges on the …

[WIP] Add a stream state enum that makes it impossible to lose a stream

---

.appveyor.yml
src/header/shared/quality_item.rs

Is better now
Fixes https://github.com/hyperium/hyper/issues/653

Improve appveyor ci

---

src/server/response.rs

It may be worth weakening the check here to only set 500 when the status is still 200 (incase a user wants to return 400 or some other error), but I think being strict here discourages the use of panics for control flow.

fix(response): respond with a 500 if a handler panics

---

src/server/mod.rs

fix(server): Flush 100-continue messages

---

src/buffer.rs

fix(buffer): fix incorrect resizing of BufReader

---

src/header/common/content_type.rs

JSON Charset patch

---

src/header/common/content_type.rs

Leftover from ec568e9a551018b3353b6754eb2fcd729c7ea3c6.

Remove "charset" from ContentType::json() docs

---

.travis.yml

In preparation for https://github.com/hyperium/hyper/issues/755.

Enable Travis CI testing on OSX.

---

Cargo.toml
src/client/mod.rs
src/client/request.rs
src/header/common/content_disposition.rs
src/header/parsing.rs
src/http/h1.rs
src/http/h2.rs
src/lib.rs
src/uri.rs

**Do not merge yet:** rust-url 1.0 is not published yet and may still get breaking changes. The goal of this PR for now is to demonstrate API usage.
Depends on:
* https://github.com/servo/rust-url/pull/176
* <s>https://github.com/alexcrichton/cookie-rs/pull/42</s>

Update to rust-url 1.0

---

src/client/pool.rs

@jdm sanity check?
Closes #780

fix(client): fix panic in Pool::connect

---

src/net.rs

feat(net): Add OpensslClient constructor

---

src/net.rs

It doesn't work, so it's just causing errors.
Closes #794

fix(windows): disable openssl cert validation for Windows

---

src/client/request.rs

feat(client): add Request.set_uri(RequestUri) method

---

src/client/mod.rs
src/http/conn.rs

chore(http): reduce some logs from error level

---

src/client/proxy.rs
src/net.rs

Fix 0.9.x build with `--no-default-features --features=security-framework`

---

src/http/conn.rs

> All of the move semantics remain the same for http::Conn while
the self consumption and move semantics only require a pointer copy
now rather than copying larger amounts of data. This greatly improves
the performance of hyper, by my measurements about 125% faster when
benchmarking using wrk.
Rebase of #822 
Closes #822

perf(http): reduce memcpy calls using boxed pimpl

---

src/lib.rs

fix(lib): make ControlError public

---

src/client/mod.rs
src/http/conn.rs
src/http/h1/parse.rs
src/http/mod.rs
tests/client.rs
tests/server.rs

feat(client): implement connection pooling for Client

---

examples/client.rs
src/client/connect.rs
src/client/dns.rs
src/client/mod.rs
src/http/conn.rs
src/http/h1/parse.rs
src/http/mod.rs
src/server/mod.rs

fix(client): handle when DNS resolves after a timeout triggers

---

src/header/common/last-event-id.rs

Add a Last-Event-ID header to properly work with Server-Sent Events
Closes #723

feat(headers): add last-event-id header

---

src/net.rs
src/server/mod.rs
tests/server.rs

Let Server::new take one or more listeners

---

.travis.yml
doc/guide/server.md
src/lib.rs

docs(guide): add meat to the Server Guide

---

src/header/common/content_location.rs
src/header/common/mod.rs
src/header/mod.rs

feat(headers): add Content-Location header

---

src/client/dns.rs

Spawn client DNS threads with descriptive name

---

src/http/h1/decode.rs

Async decoder implementation.
**Todo**: Extensions
_Work in progress (will squash commits eventually)_

Async Chunked Decoding

---

src/http/conn.rs

Not handling this was an issue for keep-alive connections because
requests would get assigned to a closed connection and then immediately
error. Handling the HUP event makes this situation much less likely. It
is still possible however; consider the situation where a HUP arrives
while the event loop is busy processing new requests to add. The
connection is disconnected, but the HUP hasn't been processed, and a
request could be assigned to it. This case is, however, unlikely.

fix(conn): Handle remote hangup

---

src/http/h1/decode.rs

Before this, the final \r\n for an empty body was not being read. This
caused issues with keep-alive connections.

fix(http): Chunked decoder reads last \r\n

---

examples/hello.rs
examples/server.rs
src/http/conn.rs
tests/server.rs

Fix  to work on the chunking bug and add some more tests.

Fix examples and get tests compiling with api changes

---

Cargo.toml
src/client/connect.rs
src/error.rs
src/lib.rs

Update Hyper's tokio branch to reflect https://github.com/tokio-rs/tokio-tls/commit/b121025c16f829ebd079ebe1588a05070f5b3ee9
Sorry, just about to head out the door! Would normally write a better description. Will do later!

Update Hyper's tokio branch to reflect tls

---

examples/hello.rs
examples/server.rs
src/client/connect.rs
src/client/mod.rs
src/client/pool.rs
src/server/mod.rs
tests/server.rs

address tokio_service mutability changes

---

src/http/h1/decode.rs
src/mock.rs

Looks like a few last minor updates are needed.

Get tests compiling on tokio branch

---

src/uri.rs

Hi,
Parsing `"http://host:80"` caused panic (index out of bound) because the
authority end index was computed with the original uri but the uri
stored for later used was sanitized by `Url::parse()` to `"http://host"`.
The fix computes the autority end index with the actual uri used (the
one from `Url::parse()`). Two tests have been added.
Please do not hesistate if you want me to adapt the fix differently.
Cheers,
Florent

fix(uri): fix panic when uri contain default port

---

Cargo.toml
src/header/common/authorization.rs
src/lib.rs

Replace rustc-serialize with base64 crate.
https://github.com/hyperium/hyper/issues/1028

refactor(header): Change to base64 serialize

---

src/header/common/content_length.rs
src/header/common/retry_after.rs
src/header/internals/vec_map.rs
src/header/mod.rs
src/header/parsing.rs
src/header/raw.rs
src/http/buf.rs
src/http/chunk.rs
src/http/conn.rs
src/http/h1/decode.rs
src/http/h1/parse.rs
src/http/io.rs
src/http/mod.rs
src/lib.rs
src/mock.rs

use MemSlice in Headers

---

Cargo.toml

Some serialization speed improvement in that version

chore(version): update base64

---

src/server/mod.rs

BREAKING CHANGE: The `run_until` future used to require its `Error` to
be `hyper::Error`, now it can be `()`.

feat(server): change Server.run_until Future Error to ()

---

src/header/common/content_type.rs

feat(headers): impl Eq for ContentType

---

src/http/conn.rs

fix(http): fix busy looping when in keep-alive

---

src/http/h1.rs

The trailing newline otherwise breaks keepalive after a chunked request.

fix(http): Consume entire chunked encoding message

---

src/http/conn.rs
src/http/io.rs
src/mock.rs

fix(conn): always flush io from poll_complete

---

src/http/conn.rs
src/http/io.rs
src/mock.rs

fix(conn): always read till blocked when parsing

---

src/http/conn.rs
tests/server.rs

fix(server): fix broken keep-alive in Server

---

src/header/common/origin.rs

This change removes one common string allocation when parsing the origin
header.
Fixes #1124

refactor(headers): use static "http"/"https" for scheme

---

CHANGELOG.md

`<s>` in html is a strikethrough.

Fix formatting in README.

---

Cargo.toml
src/header/common/authorization.rs

feat(headers): update to unicase 2.0 and base64 0.5

---

src/header/common/link.rs
src/header/common/mod.rs

Closes #650
This is a rebase of #1044 onto the 0.10.x branch.

feat(headers): Backport Link header implementation to 0.10.

---

Cargo.toml
build.rs

As in the title. Discussed on IRC.

chore(dev): switch to version_check from rustc_version

---

src/header/mod.rs

Commit 7d122bd15fb354c427c40986c28e292f9c65f54e removed usage of `header::sealed::GetType`, so the trait can safely be removed.

refactor(header): remove GetType trait

---

src/client/pool.rs

Previously, the pool cleanup logic would erroneously clean up
pools that had exactly one connection left in them. This bug
was introduced in 30fb0e777815adcaa6b287ac7720570dedd77942.

fix(client): don't drop connection pools with exactly one connection left

---

.travis.yml
Cargo.toml
src/client/compat.rs
src/client/compat_impl.rs
src/client/mod.rs
src/common/str.rs
src/header/mod.rs
src/http/request.rs
src/http/response.rs
src/lib.rs
src/method.rs
src/server/compat.rs
src/server/compat_impl.rs
src/server/mod.rs
src/status.rs
src/uri.rs
src/version.rs

Design exploration for #1313. This is missing tests at the moment (working on it), but I would appreciate some feedback as to my current approach.
TODO

feat(*): implement compatibility with http crate

---

src/client/dns.rs

feat(client): add names to DNS threads

---

CHANGELOG.md
src/header/common/link.rs
src/proto/h1/parse.rs
tests/client.rs

Fix small typos

---

src/header/common/range.rs

Implemented this for work recently, and it took us a couple of tries and careful reading of the RFC to get it right. Based on this experience, I could image it to be useful as a built-in.
Let me know what you think!

feat(header): implement ByteRangeSpec::to_satisfiable_range

---

Cargo.toml
examples/params.rs

Add an example program illustrating parsing a request body through
generating a response body.

docs(server): Add a forms server example

---

.travis.yml
Cargo.toml
src/client/mod.rs
src/client/pool.rs
src/client/tests.rs
src/lib.rs
src/proto/h1/dispatch.rs
src/server/tcp.rs
tests/client.rs

refactor(lib): change from futures-timer to tokio-timer

---

src/body.rs

Avoid double boxing when wrapping a Stream in a Body

---

examples/README.md

Resolves https://github.com/hyperium/hyper/issues/1511
Thanks to @apiraino

Add a README.md file for examples

---

examples/echo.rs

Update the echo example based on the functionality explained in the Hyper guide: https://hyper.rs/guides/server/echo
CLOSES: #1528

docs(server): update echo example with functionality from the guide

---

src/client/connect.rs
src/error.rs

add `set_scheme`, `set_host`, and `set_port` for `Destination`

---

src/proto/h2/mod.rs
src/proto/h2/server.rs

Update Http2 proto to cancel quick when the stream is reset, on an
`RST_STREAM` frame.
Closes: #1549

feat(https): Quick cancel on RST_STREAM

---

src/headers.rs
src/proto/h1/role.rs

chore(headers): use HeaderValue::from for content-length

---

Cargo.toml
examples/README.md
examples/client_json.rs

Add a client example getting and parsing json.

---

src/server/mod.rs

mention http2 support in docs

---

src/client/connect.rs

feat(client): add ability to include `SO_REUSEADDR` option on sockets

---

Cargo.toml
build.rs
src/client/conn.rs
src/client/mod.rs
src/headers.rs

addresses some TODOs in the code

replace usage of Box<Trait> with impl Trait

---

build.rs
src/client/conn.rs
src/client/mod.rs
src/common/macros.rs
src/common/mod.rs
src/headers.rs
src/lib.rs

Thanks to @sinkuu for the suggestion!

refactor(lib): use type macro to detect impl Trait

---

src/client/mod.rs
src/client/pool.rs

Setting this will cap the amount of idle connections kept around for a
specific host. This defaults to no limit (`usize::MAX`).
Closes #1639

Add max_idle_per_host Client configuration

---

src/proto/h1/role.rs

Don't eat the first character in a header name if it's not a letter

---

src/client/connect/mod.rs
src/error.rs

fix(client): allow calling `Destination::set_host` with IPv6 addresses

---

src/client/connect/dns.rs

Add FromStr impl for Name

---

src/service/make_service.rs

Include the creation of server too. Previously, the parameter type of
the closure had a different type than the default server provided, which
wasn't obvious to the user.
I think it's better to have the full example, both because the user has a working snippet to start from, and to make sure the types don't diverge during some refactorings.
Fixes #1773

Make the make_service_fn example a full snippet

---

src/client/conn.rs
src/server/conn.rs

Related issue: #1786.
Not sure about code style, etc.

Add wrappers to use poll_without_shutdown without problems

---

src/body/body.rs

I tried to find a general `Hyper::Error` to avoid calling unwrap, but didn't find any, to you have a suggestion or better solution?

impl Sink for Body::Sender, closes 1781

---

src/proto/h1/role.rs

This is an attempt at a fix for #1795

refactor(role): code refactor

---

src/client/connect/http.rs

This is required to get better download/upload speeds with TlsStream.
With default buffer size, I get about 10MB/s download speed.
With 1MB buffer size, I get about 500MB/s.
Signed-off-by: Dietmar Maurer <dietmar@proxmox.com>

feat(HttpConnector): allow to set socket buffer sizes

---

src/body/body.rs

Without this, the following innocent code errors:
```rust
match req.uri() {
u => {
let b = req.into_body().try_concat().await;
}
}
```
Even curious-er, the code is definitely *moving* the `Request<Body>`, due to `req.into_body()`, but the compiler still thinks it's borrowed at the `.await`.

feat(body): require Sync when wrapping a dynamic Stream

---

Cargo.toml
examples/client_json.rs

Update client_json example to use async await

---

examples/multi_server.rs

docs(examples): Update multi_server example to use async await

---

examples/params.rs

docs(examples): Update params example to use async await

---

Cargo.toml

Close #1849 
Ref https://github.com/hyperium/hyper/pull/1872#issuecomment-512034974
@seanmonstar

test(examples): uncomment re-enabled examples

---

examples/client.rs
examples/client_json.rs
examples/hello.rs
examples/multi_server.rs
examples/params.rs
examples/proxy.rs
examples/send_file.rs
examples/single_threaded.rs
examples/state.rs
examples/upgrades.rs
examples/web_api.rs
src/rt.rs
src/server/mod.rs
src/service/make_service.rs

Remove re-export of `tokio::main`

---

Cargo.toml
src/body/body.rs
tests/client.rs
tests/support/mod.rs

This PR updates the tests after the breaking changes and makes them pass.

Update the `tests/client.rs` test

---

Cargo.toml

Fixed documentation issue (https://github.com/taiki-e/pin-project/pull/71)

chore(dependencies): update pin-project to 0.4.0-alpha.9

---

Cargo.toml
src/common/drain.rs
src/proto/h2/server.rs
src/server/conn.rs
src/server/mod.rs
src/server/shutdown.rs

Depends on https://github.com/hyperium/h2/pull/413.
Changes: https://github.com/taiki-e/pin-project/releases/tag/v0.4.0-beta.1 (https://github.com/taiki-e/pin-project/pull/90 is the biggest change in this release)

chore(dependencies): update tokio and pin-project

---

Cargo.toml

Use new alpha release of h2

---

Cargo.toml
benches/connect.rs
src/client/connect/http.rs

perf(client): change HttpConnecting to hold Arc<Config> instead of inlined fields

---

src/client/pool.rs

fix(client): fix panic from unreachable code

---

src/client/conn.rs
src/server/conn.rs

This should make it easier to add H3 functionality.

chore(lib): use dedicated enums for connection protocol versions

---

src/proto/h1/dispatch.rs

fix(client): fix polling dispatch channel after it has closed

---

src/client/connect/dns.rs
src/client/connect/http.rs

refactor: Use async/await in HttpConnector

---

src/client/connect/http.rs

We return this `Future` instead of the `Pin<Box<dyn Future>>` directly so that users don't rely on it fitting in a `Pin<Box<dyn Future>>` slot (and thus we can change the type in the future).

refactor(client): return HttpConnecting newtype

---

Cargo.toml
benches/end_to_end.rs
examples/client.rs
src/client/mod.rs
tests/server.rs

chore(dependencies): update to http-body 0.3

---

src/proto/h1/role.rs

refactor(h1): un-split record_header_indicies for ARM

---

src/client/mod.rs

feat(client): impl tower_service::Service for Client

---

src/client/conn.rs
src/client/mod.rs
src/proto/h2/client.rs

Remove Unpin requirements for client request bodies

---

src/proto/h1/conn.rs
tests/server.rs

fix(http1): remove panic for HTTP upgrades that have been ignored

---

src/body/body.rs

Fix Body size of tests on 32-bit architecture

---

src/server/conn.rs

cc https://github.com/hyperium/hyper/issues/2161

fix(server): fix panic in Connection::graceful_shutdown

---

src/client/dispatch.rs

Related https://github.com/seanmonstar/reqwest/issues/853

Replace futures mpsc with tokio mpsc in client dispatcher

---

Cargo.toml
examples/README.md
examples/send_file.rs
examples/send_file_index.html

feat(example): read file by chunks in send_file example

---

Cargo.toml

fix(cargo): require tokio 0.2.11

---

src/proto/h1/role.rs

refactor(http1): include bytes in invalid header name panic

---

src/client/connect/http.rs

fix(http): fix panic when addrs in ConnectingTcpRemote is empty

---

hyper-capi/examples/client.c

... makes it easier to toy with the example against other sites and paths.

client.c: accept optional args to set host, port and path

---

.github/workflows/CI.yml
Cargo.toml
benches/body.rs
benches/connect.rs
benches/end_to_end.rs
benches/pipeline.rs
benches/server.rs
examples/single_threaded.rs
src/client/connect/dns.rs
src/client/connect/http.rs
src/client/dispatch.rs
src/client/pool.rs
src/common/drain.rs
src/common/io/rewind.rs
src/proto/h1/conn.rs
src/proto/h1/decode.rs
src/proto/h1/dispatch.rs
src/proto/h1/io.rs
src/proto/h1/role.rs
src/proto/h2/ping.rs
src/server/conn.rs
src/server/tcp.rs
src/upgrade.rs
tests/client.rs
tests/server.rs
tests/support/mod.rs

Continuation of #2317 and #2319.
Closes #2302

Tokio 0.3 Upgrade

---

src/common/drain.rs

The current implementation of `drain` uses a `tokio::sync::watch`
channel to send the shutdown signal, and a `tokio::sync::mpsc` to signal
when all draining tasks have completed. No data is ever actually sent on
the MPSC; instead, it is simply used to notify the task that signalled
the drain when all draining tasks have been dropped.
Tokio 0.3's `watch::Sender` has a `closed` method that can be used to
await the dropping of all receivers. This can be used instead of the
MPSC channel. This commit updates `drain` to use `watch::Sender::closed`
instead. This has fewer moving parts, and may have slightly less
overhead (as it doesn't require additional allocation forthe MPSC which
is never actually used).
Signed-off-by: Eliza Weisman <eliza@buoyant.io>

refac(common): simplify drain

---

src/client/conn.rs

Add basic, module level example for the Builder performing a handshake,
spawning a task to run the Connection and sending a single request and
receiving the response.
Addresses #2272

docs(client): add example of client conn usage

---

src/error.rs

Used match macro to improve the code quality

---

src/proto/h1/decode.rs
src/proto/h1/encode.rs
src/server/tcp.rs

Update the match with the matches macro to improve the code quality.
@seanmonstar

Update the match with the matches macro

---

.github/workflows/CI.yml
src/lib.rs

docs(lib): enable doc_cfg on docs.rs builds

---

src/client/conn.rs
src/client/connect/dns.rs
src/client/dispatch.rs
src/client/mod.rs
src/client/pool.rs
src/common/date.rs
src/common/drain.rs
src/common/exec.rs
src/common/mod.rs
src/common/never.rs
src/common/sync_wrapper.rs
src/error.rs
src/ffi/mod.rs
src/headers.rs
src/lib.rs
src/proto/h1/conn.rs
src/proto/h1/decode.rs
src/proto/h1/dispatch.rs
src/proto/h1/encode.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h2/server.rs
src/proto/mod.rs
src/server/conn.rs
src/server/tcp.rs
src/service/make.rs
src/service/mod.rs
src/upgrade.rs

Apply unreachable_pub lint

---

capi/include/hyper.h
src/ffi/error.rs

feat(ffi): add HYPERE_INVALID_PEER_MESSAGE error code for parse errors

---

src/proto/h1/decode.rs

This fixes the CI failure currently occurring on the master branch.

Fix non_fmt_panic warning

---

capi/cbindgen.toml
src/ffi/body.rs
src/ffi/client.rs
src/ffi/io.rs
src/ffi/task.rs

refactor(ffi): Removed need for cbindgen type renames

---

.github/workflows/CI.yml
Cargo.toml
src/ffi/body.rs
src/ffi/client.rs
src/ffi/error.rs
src/ffi/http_types.rs
src/ffi/io.rs
src/ffi/mod.rs
src/ffi/task.rs
src/lib.rs

docs(ffi): generate FFI documentation

---

src/proto/h1/io.rs

If the write buffer was filled with large bufs from the user, such that
it couldn't be fully written to the transport, the write buffer could
start to grow significantly as it moved its cursor without shifting over
the unwritten bytes.
This will now try to shift over the unwritten bytes if the next buf
wouldn't fit in the already allocated space.

fix(http1): reduce memory used with flatten write strategy

---

src/error.rs
src/proto/h1/role.rs

When a header parse error is because of content-length or
transfer-encoding semantics, include a better error message in the
`hyper::Error`.
Closes #2569

refactor(error): add header parse error details in `hyper::Error`

---

capi/include/hyper.h
src/client/conn.rs
src/ffi/body.rs
src/ffi/client.rs
src/ffi/http_types.rs
src/proto/h1/conn.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h1/role.rs

feat(ffi): add option to get raw headers from response

---

src/proto/h1/decode.rs

We don't really care what bytes are in chunked extensions. We ignore
them until we find a CRLF. However, some other HTTP implementations may
only look for a LF, and forget that chunked requires the CR as well. To
save them from themselves, this makes hyper reject any chunked
extensions that include an LF byte.
This isn't a *bug*. No one ever cares what's in the extensions. This is
meant as a way to help implementations that don't decoded chunked
encoding correctly. This shouldn't affect really anyone in the real
world.

refactor(http1): reject newlines in chunked extensions

---

src/error.rs
src/server/conn.rs

fix(server): convert panic to error if Connection::without_shutdown called on HTTP/2 conn

---

src/client/client.rs
src/client/conn.rs
src/server/conn.rs
src/server/server.rs

docs(http1): clarify HTTP1 preserve case option

---

src/proto/h1/role.rs

Minor reformatting of single block.

style(http1): correct indentation

---

docs/CODE_OF_CONDUCT.md

This includes a custom code of conduct for hyper. It's just my preference to personalize it, since the way we treat each other is so important. In short:

docs(conduct): add custom CODE_OF_CONDUCT

---

CONTRIBUTING.md
docs/PULL_REQUESTS.md

Add contributing guide for submitting pull requests

---

Cargo.toml
README.md

Begin 1.0 development

---

tests/client.rs
tests/server.rs

Re-enables the tests that were disabled in #2896 
cc @oddgrd :)

test(client,server): add back tests around streaming bodies

---

examples/http_proxy.rs

Fix http_client example

---

examples/client.rs
examples/client_json.rs

docs(examples): include Host header in client examples

---

Cargo.toml

Pinning so that working on #2840 doesn't break CI here.

chore(body): pin to specific commit for http-body

---

CHANGELOG.md
Cargo.toml

(Just getting CI happy, I'll merge just before publishing.)

Prepare v1.0.0-rc.1

---

CHANGELOG.md
Cargo.toml

I'll publish Monday morning. cc @nox

Prepare v0.14.21

---

Cargo.toml

chore(dependencies): enable socket2 'all' feature

---

src/client/conn/http2.rs

feat(client) implement Clone for http2::SendRequest

---

docs/MAINTAINERS.md

Thanks for the invitation, happy to help out however I can!

docs: add oddgrd to the list of triagers

---

src/body/incoming.rs

chore(body): disable miri for a flaky test

---

docs/GOVERNANCE.md
docs/ISSUES.md
docs/TENETS.md

docs: fix some broken links

---

Cargo.toml

Updates to pretty_env_logger 0.5.

chore(dependencies): update to pretty_env_logger 0.5

---

Cargo.toml

chore(dependencies): remove implicit features of optional dependencies

---

.github/workflows/CI.yml
Cargo.toml

Adds a CI job to check unused dependencies.

chore(ci): check unused dependencies

---

Cargo.toml

This might improve readability.

refactor(dependencies): move optional dependencies to optional section

---

docs/MAINTAINERS.md

docs(maintainers): update triagers

---

.github/workflows/CI.yml
src/body/mod.rs
src/client/mod.rs
src/server/mod.rs
src/service/mod.rs
src/upgrade.rs

doc(lib): resolve rustdoc warning

---

src/client/mod.rs

Part of https://github.com/hyperium/hyper/issues/3067

docs(client): add example links

---

src/common/io/rewind.rs
src/upgrade.rs

test(upgrade): fix Upgrade test compilation errors with no features

---

examples/README.md

Updates examples' dependency document.

docs(examples): update dependencies section

---

src/error.rs
src/headers.rs
src/proto/h1/conn.rs
src/proto/h2/client.rs
src/proto/mod.rs
src/server/conn/http1.rs
src/server/conn/http2.rs

refactor(lib): small refactoring

---

src/body/incoming.rs
src/common/io/rewind.rs
src/error.rs
src/ext/mod.rs
src/headers.rs
src/proto/h1/conn.rs
src/proto/h1/dispatch.rs
src/proto/h1/role.rs
src/proto/h2/client.rs
src/proto/h2/mod.rs

chore(lib): small refactoring

---

src/error.rs

Removes the lint configs of allowing unused code, and adds features cfg attributes to them.

refactor(error): remove lint config to allow unused code

---

src/body/incoming.rs

`opt_len` seems to be able to be written as a function instead of a macro.

refactor(body): switch opt_len helper macro as function

---

Cargo.toml
benches/end_to_end.rs
src/client/dispatch.rs

test(benches): re-enable end-to-end http2 chunked benchmarks

---

examples/client.rs

docs(examples): fix client request path

---

.github/workflows/CI.yml
docs/CODE_STYLE.md

Sets rustfmt edition config to 2021.

chore(ci): set rustfmt edition to 2021

---

src/body/incoming.rs
src/body/length.rs
src/client/conn/http2.rs
src/ext/h1_reason_phrase.rs
src/proto/h1/decode.rs
src/proto/h1/encode.rs
src/server/conn/http2.rs

refactor(lib): apply small refactoring

---

Cargo.toml

closes #3653
Bumps tokio to v1.27

fix(v0.14): bump tokio to 1.27

---

.github/workflows/CI.yml

Updates to taiki-e/cache-cargo-install-action@v2.

chore(ci): update to taiki-e/cache-cargo-install-action@v2

---

src/proto/h1/io.rs
tests/client.rs

fix(http1): fix intermitent panic parsing partial headers

---

.github/workflows/CI.yml

Updates to `actions/checkout@v5`.

chore(ci): update to actions/checkout@v5
