src/header/common/cache_control.rs

Just a minor replacement of a deprecated reference to trim_chars.

Replaced deprecated reference to trim_chars with trim_matches

---

src/net.rs
src/server/mod.rs

Try three! Thoughts on whether more stuff should be configurable? Also, sorry for being too dense to figure out the refactoring you guys were talking about on the last PR
Tested with
```
extern crate hyper;
use std::io::net::ip::Ipv4Addr;
use std::path::posix::Path;
use hyper::server::{Request, Response};
static PHRASE: &'static [u8] = b"Hello World!";
fn hello(_: Request, res: Response) {
let mut res = res.start().unwrap();
res.write(PHRASE).unwrap();
res.end().unwrap();
}
fn main() {
hyper::Server::https(Ipv4Addr(127, 0, 0, 1), 3000,
Path::new("./cert.pem"), Path::new("./key.pem"))
.listen(hello).unwrap();
println!("Listening on http://127.0.0.1:3000");
}
```

Added TLS/SSL support serverside

---

src/header/common/cache_control.rs
src/header/common/connection.rs
src/header/common/content_type.rs
src/header/common/date.rs
src/header/common/expires.rs
src/header/common/if_modified_since.rs
src/header/common/last_modified.rs
src/header/common/location.rs
src/header/common/server.rs
src/header/common/transfer_encoding.rs
src/header/common/upgrade.rs

fix(header): fix fmt_header outputs of several headers

---

src/header/common/accept_encoding.rs
src/header/common/mod.rs
src/header/common/server.rs

Add `impl_header!` and `impl_list_header!` macros. Rewrite `Accept-Encoding`
and `Server` header implementations to use the new macros.

refactor(headers): add header macros and add two example uses

---

src/http.rs

In order to be able to handle larger headers than 1k, for example
header containing tracking cookies etc.
references:
- http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers
- http://stackoverflow.com/questions/686217/maximum-on-http-header-values

Increase MAX_HEADER_FIELD_LENGTH to 4k

---

src/header/mod.rs
src/net.rs

TypeId has moved from std::intrinsics to std::any

fix(imports): Update TypeId import location to "any" module

---

src/header/common/mod.rs

This is needed to allow compilation of Iron's static as far as I can see, but maybe @reem has an alternative?

Make CacheDirective public

---

src/header/common/mod.rs

Expose Authorization header Scheme trait and Basic authorization
Expose the Upgrade header Protocol
Refactor ConnectionOption export to be more similar to CacheDirective export for consistency
This is required for people to use the Authorization and Upgrade headers.

fix(headers): make Schemes, Basic, Protocol public

---

src/header/common/connection.rs
src/header/common/upgrade.rs

This makes ConnectionHeader case-insensitive since HTTP header field names are case-insensitive.
RFC6455 requires the Upgrade Protocol to search case-insensitively for "websocket". At the moment only lower-case works (I hit this when trying to get Autobahn to work with my websocket library).
Other protocol values may be case-sensitive, however, so ProtocolExt is still a normal case-sensitive String.

fix(headers): make ConnectionHeader and search for websocket protocol unicase

---

CONTRIBUTING.md

It turned out in #271 that the current description for commit messages introducing breaking changes is not clear enough.

chore(git): clarify CONTRIBUTING.md

---

src/header/common/cookie.rs
src/header/common/mod.rs

`Cookie` is the actual name of the header and since all other header structs
use the exact camel-cased version of their name using a different name here
is very inconvienient and confusing. You will encounter weird errors if you
try to use `Cookie` as the header. For this reason rename `Cookies` as
discussed on IRC with @seanmonstar and @reem and use `CookiePair` for real
cookies.
Breaks code using `Cookie` header.

refactor(headers): Rename `Cookies` header to `Cookie`

---

src/server/mod.rs

It's different from the elided lifetimes, but having at least one explicit shared lifetime has allowed me to actually get the compiler to trust me on some dependent code. 
Any concerns on this being too restrictive?

refactor(server): Add explicit lifetime annotations for Handler trait

---

benches/client.rs
benches/client_mock_tcp.rs
benches/server.rs
examples/client.rs
examples/hello.rs
examples/server.rs
src/client/mod.rs
src/client/request.rs
src/client/response.rs
src/header/common/authorization.rs
src/header/mod.rs
src/http.rs
src/lib.rs
src/mock.rs
src/net.rs
src/server/mod.rs
src/server/request.rs
src/server/response.rs

Make it build with the latest rust-nightly (2015-01-27)
Renamed io import to old_io.
Renamed Writer::write to Writer::write_all

fix(rustup): update io import, Writer::write

---

src/header/mod.rs

fix(headers): add limit to maximum headers that should be parsed

---

README.md

`res` needs to be unwrapped, we want to print out `body`, and `res` doesn't need to be mutable.

fix(readme): Make the README client example work

---

Cargo.toml
src/header/cell.rs
src/header/mod.rs
src/lib.rs

It turns out, we don't need capabilities of MuCell (or even RefCell).
We don't to have sophisticated interior mutability. We don't ever lend
out references that may be mutated later. Instead, if there is no value
to lend, then we generate the value, require interior mutability to save
the value internally, and then we return a reference. We never ever
change a value once it's been generated. It can be changed, but only via
&mut self methods, where we can safely reason about mutability.
This means we don't need keep borrow checking code at runtime, which
helps performance. We also are able to reduce the amount of unsafe
transmutes. The internal API more safely constrains the usage of unsafe,
enforcing our invariants, instead of shotgunning unsafe usage with Refs
and promising we're doing …

refactor(headers): switch from MuCell to OptCell

---

src/header/common/etag.rs
src/header/mod.rs
src/header/shared/entity.rs
src/header/shared/mod.rs

Allow use of EntityTag in other headers that use entity tags.

Factor out EntityTag from Etag header

---

README.md

`res` needs to be mutable (introduce with #294) otherwise
```
Compiling toto v0.0.1 (file:///home/ctjhoa/rust/toto)
src/main.rs:14:16: 14:20 error: cannot borrow immutable local variable `resp` as mutable
src/main.rs:14     let body = res.read_to_string().unwrap();
^~~~
error: aborting due to previous error
Could not compile `toto`.
```

docs(readme): Make the README client example work

---

examples/client.rs

As per this compiler warning
"warning: use of deprecated item: use std::env::args() instead, #[warn(deprecated)] on by default"

chore(examples): Stop using deprecated std::os::args in example

---

src/status.rs

As discussed in #177 hyper must support status code outside the
standard range for compatibility reasons.
BREAKING CHANGE: This removes unregistered status codes from the enum. Use
`FromPrimitive` methods to create them now. StatusCode and StatusClass can no
longer be casted to `u16`, use `ToPrimitive` methods now.
For example `status.to_u16().unwrap()` to get the status code number.
Closes #303

feat(header): Support arbitary status codes

---

src/http.rs
src/lib.rs
src/server/request.rs

If a client sent an illegal request (like a GET request with a message
body), or if there was a legal request with a body but the Handler
didn't read all of it, the remaining bytes would be left in the stream.
The next request to come from the same client would error, as the server
would confuse the remaining bytes, and think the request was malformed.
Fixes #197
Fixes #309

fix(server): Drain requests on drop.

---

src/http.rs
src/lib.rs
src/server/request.rs

Reverts hyperium/hyper#310
This is not a good idea, since it means that the request will be read in its entirety no matter what, which is very much not a desirable property for many servers.

Revert "fix(server): Drain requests on drop."

---

src/header/common/accept_language.rs
src/header/common/mod.rs

Adds header support for Accept-Language, using a struct for the primary and
sub components of the language.
NOTE: I have been unable to get equality comparison working

feat(headers): add AcceptLanguage header

---

examples/hello.rs
examples/server.rs
src/lib.rs
src/server/acceptor.rs
src/server/mod.rs

This is a modified and specialized thread pool meant for
managing an acceptor in a multi-threaded way. A single handler
is provided which will be invoked on each stream.
Unlike the old thread pool, this returns a join guard which
will block until the acceptor closes, enabling friendly behavior
for the listening guard.
This improves performance by like 15%, all the way to 105k req/sec
on my machine, which usually gets about 90k.

feat(server): Rewrite the accept loop into a custom thread pool.

---

src/header/shared/quality_item.rs

PartialOrd is useful to sort Collections of QualityItems by quality.
So you can find the preferred match easier.
Closes #314

feat(headers): Implement PartialOrd for QualityItem

---

src/header/common/mod.rs

This adds a `$crate` variable missed by de1be6726
Note that even though this PR targets master, it needs #324 (or some equivalent PR) to build on the current rust nightly. Let me know if I should rebase.
Closes #323

fix(headers): use $crate when referring to hyper modules on macros

---

src/header/mod.rs

Closes https://github.com/hyperium/hyper/issues/326

Add remove_raw method and corresponding test

---

src/header/common/accept.rs
src/header/common/accept_encoding.rs
src/header/common/accept_language.rs
src/header/mod.rs
src/header/shared/mod.rs
src/header/shared/quality_item.rs

Using floating point numbers is problematic because comparison is inexact.
They also take more space than integral numbers in this case.
Closes: #330
BREAKING_CHANGE: Replace f32 quality values in quality items with a
Quality(u16) newtype. Valid values are from 0 to 1000.

refactor(headers): Use u16 based newtype for quality value

---

Cargo.toml
examples/client.rs
examples/hello.rs
examples/server.rs
src/client/response.rs
src/error.rs
src/header/common/authorization.rs
src/header/mod.rs
src/http.rs
src/lib.rs
src/method.rs
src/net.rs
src/server/mod.rs
src/server/request.rs
src/uri.rs

httparse is a http1 stateless push parser. This not only speeds up
parsing right now with sync io, but will also be useful for when we get
async io, since it's push based instead of pull.
BREAKING CHANGE: Several public functions and types in the `http` module
have been removed. They have been replaced with 2 methods that handle
all of the http1 parsing.

perf(http): changes http parsing to use httparse crate

---

README.md
benches/client.rs
benches/server.rs
examples/hello.rs
examples/server.rs
src/header/mod.rs
src/lib.rs
src/net.rs
src/server/mod.rs

This PR fixes `cargo build` and `cargo test`, and includes the PR of @adrianheine .
Method lookup on traits seems to have changed to force
`impl TraitName` expressions to be more specific. That means that
`method` will not be found anymore on an object of type `&Trait+Send`,
unless you provide an `impl Trait+Send`.
Now `NetworkStream` and `HeaderFormat` trait implementations
are done against `* + Send`, which helps the compiler to find the
respective `downcast*` method implementations once again.

fix(rustup): rustc 1.0.0-nightly (ea8b82e90)

---

README.md
benches/server.rs
examples/hello.rs
examples/server.rs
src/lib.rs
src/net.rs
src/server/mod.rs

Adapt to current rustc (closes #381)

---

src/header/common/host.rs
src/header/shared/entity.rs
src/server/mod.rs

* replace `char_at()` calls with itertor, as suggested by compiler
* fixed comparison in test
**Benchmarks fail if they are run** - this is nothing travis could figure out due to the `--no-run` flag. The error is:
```bash
test header::common::date::asctime::bench_format                    ... thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:362
```
I don't know when this regression sneaked in, it doesn't seem to be related to this commit though.

fix(rustup): 1.0.0-nightly (e2fa53e59 2015-03-20)

---

.travis.yml

By stating that hyper does not need sudo to build it can be compiled in
a container:
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

chore(build): Enable building hyper in docker containers on travis

---

src/header/common/accept.rs
src/header/common/accept_charset.rs
src/header/common/accept_encoding.rs
src/header/common/accept_language.rs
src/header/common/access_control/allow_headers.rs
src/header/common/access_control/allow_methods.rs
src/header/common/access_control/request_headers.rs
src/header/common/allow.rs
src/header/common/connection.rs
src/header/common/etag.rs
src/header/common/host.rs
src/header/common/if_match.rs
src/header/common/if_none_match.rs
src/header/common/pragma.rs
src/header/common/upgrade.rs
src/header/common/vary.rs
src/header/mod.rs
src/header/parsing.rs
src/header/shared/charset.rs
src/header/shared/encoding.rs
src/http.rs
src/lib.rs
src/method.rs
src/status.rs

* fix `extern crate` declaration for rustc-serialize
* enable `into_cow` feature
* replace as_slice() calls by as_ref and enable `convert` feature

fix(rustup): rustc 1.0.0-nightly (123a754cb 2015-03-24)

---

src/client/request.rs
src/client/response.rs
src/error.rs
src/header/internals/item.rs
src/http.rs
src/net.rs
src/server/listener.rs
src/server/mod.rs
src/server/request.rs

Removing the remaining casts trigger inference failures... so they're... not trivial?

fix(rustup): static bounds required on Type definition, trivial_casts

---

.travis.yml

Travis supports the caching of folders between builds.
By storing the ./target folder we can cache hyper's dependencies.

chore(travis): Enable caching of ./target folder.

---

src/buffer.rs
src/client/response.rs
src/http.rs
src/lib.rs
src/server/mod.rs
src/server/request.rs

This includes a custom BufReader, since the one in libstd doesn't allow
reading additional data into the buffer without consuming it. This is
required because some connections may send shorter packets, and so we
need to perform multiple reads. After each read, the contents of the
buffer are passed to httparse to see if have a valid message. If so, the
proper amount of bytes are consumed. The additional bytes are left in
the buffer since they are the beginning of the body.
The buffer in this BufReader also grows in size, compared to the libstd
which is sized once. This is because we start with a smaller buffer,
since the majority of messages will be able to include their head in a
packet or 2. Therefore, it's a wasteful performance hit to allocate the
maximum size for every message. …

fix(http): read more before triggering TooLargeError

---

src/header/common/authorization.rs
src/net.rs
src/uri.rs

* enable slice_patterns feature
* add `Reflect` trait bounds where necessary

fix: rustup

---

src/header/common/etag.rs
src/header/common/if_match.rs
src/header/common/if_none_match.rs
src/header/shared/entity.rs

Adds strong and weak comparison to EntityTag as described in the RFC, add tests for this. Make EntityTag safe to use by hiding the tag field, this prevents users from inserting malicious values for the tag. Invalid values can screw up header formatting and may allow to insert headers. Introduce EntityTag::new(), .tag() and .set_tag() methods. Fix Display trait for EntityTag. DQUOTES were missing. Remove custom formatting in ETag header. Improve docs.
BREAKING_CHANGE: EntityTag.tag is private, use EntityTag.tag() and EntityTag.set_tag("foobar") to access.

feat(entitytag): Add EntityTag comparison, make EntityTag safe to use

---

src/header/common/date.rs
src/header/common/expires.rs
src/header/common/if_modified_since.rs
src/header/common/if_unmodified_since.rs
src/header/common/last_modified.rs
src/header/mod.rs
src/header/parsing.rs
src/header/shared/httpdate.rs
src/header/shared/mod.rs
src/server/response.rs

Using `time::Tm` directly in HTTP header fields requires special handling to parse and format
the header values., this stops us from using the header macros. By wrapping `time::Time` in a
`HttpDate`, we can use the `FromStr` and `Display` traits of `HttpDate` like for most other values.
BREAKING_CHANGE: All code using one of the `Date`, `Expires`, `If-Modified-Since`,
`If-Unmodified-Since`, `Last-Modified` header fields needs to wrap `time::Tm`
with `HttpDate`. Removed `FromStr` trait of `Date`, `If-Modified-Sice` and `If-Unmodified-Sice`,
implementing the trait here is inconsistent with other headers.

refactor(header): Implement `HttpDate`, a wrapper for dates

---

src/header/common/accept.rs
src/header/common/accept_charset.rs
src/header/common/accept_encoding.rs
src/header/common/accept_language.rs
src/header/common/allow.rs
src/header/common/content_encoding.rs
src/header/common/content_length.rs
src/header/common/content_type.rs
src/header/common/date.rs
src/header/common/expires.rs
src/header/common/if_modified_since.rs
src/header/common/if_unmodified_since.rs
src/header/common/last_modified.rs
src/header/common/location.rs
src/header/common/mod.rs
src/header/common/referer.rs
src/header/common/server.rs
src/header/common/transfer_encoding.rs
src/header/common/user_agent.rs

The new macro handles single value headers, list headers, and list
headers with at least one item.
It creates the item for the header and contains its documentation. The
new macro allows handling
more header cases in the future, it will also be possible to include
tests inside the macro.
BREAKING_CHANGE: Removed impl_header!() and impl_list_header!() macros,
use new header!() macro.

refactor(headers): Introduce header!() macro, improve documentation

---

src/header/mod.rs
src/http.rs
src/lib.rs
src/status.rs

mergable with tomorrow's nightly

chore(stability): remove into_cow feature gate

---

Cargo.toml
src/header/mod.rs
src/lib.rs
src/net.rs

Removes the need for raw::TraitObject and Any::get_type_id

chore(all): Move downcasting to a stable implementation.

---

src/header/mod.rs

We can revert this PR when rust-lang/rust#23995 lands, but it won't
land until after beta is cut.

fix(headers): Add CowStr as a temporary hack to build on beta.

---

README.md

Remove unused import
res doesn't need to be mutable in parameter list
Change .listen() to string format

fix(README): Update to compile example against Rust beta

---

src/header/common/if_match.rs
src/header/common/if_none_match.rs
src/header/common/mod.rs
src/header/common/vary.rs

`If-Match`, `If-None-Match` and `Vary` headers are either a "*" value meaning that the header
matches every possible item or a list of items, one of them must be matched to fulfil the condition.
BREAKING_CHANGE: `If-Match`, `If-None-Match` and `Vary` item variant name changed to `Items`
Depends on #419

 refactor(headers): Use header!() macro for 3 headers with a "*" value

---

src/header/common/etag.rs
src/header/common/mod.rs

Change `Etag` (only the `E` is capitalized) to `ETag` as it is written in the relevant RFC.
BREAKING_CHANGE: `Etag` header field is now `ETag` header field
Depends on #419

refactor(headers): Use header!() macro for `ETag` header

---

src/client/mod.rs
src/client/request.rs
src/lib.rs
src/net.rs

Closes #379
BREAKING CHANGE: For people using the default HttpConnector and Client,
everything should continue to just work. If the Client has been
used with a generic parameter, it should be removed.
However, there were some breaking changes to the internals of
NetworkConnectors. Specifically, they no longer return a
NetworkStream, but instead a `Into<Box<NetworkStream + Send>>`. All
implementations of NetworkStream should continue to just work,
however.
Possible breakages could come from the stricter usage of Send
throughout the Client API.
cc @Manishearth @reem

feat(client): remove generic parameter for Connector

---

src/client/response.rs
src/http.rs
src/server/response.rs

Also derives it for Responses, since that's easy now.

feat(http): Implement Debug for HttpReader/Writer.

---

src/net.rs

Pretty simple.  Turns out that last PR I made had Response's implementing Debug... but only if the type param was Debug as well.  Since HttpStream is the default, seems sensible for it to implement Debug.

feat(net) make HttpStreams implement Debug

---

src/server/mod.rs

fix(server): join on thread when Listening drops

---

src/http.rs
src/server/mod.rs

fix(server): handle keep-alive closing

---

src/server/mod.rs

The new beta adopts the new `JoinHandle` API which has a type parameter.

fix(server): JoinHandle type parameter

---

src/net.rs
src/server/mod.rs

Ssl context

---

src/client/mod.rs
src/client/pool.rs
src/client/request.rs
src/client/response.rs
src/http.rs
src/net.rs
src/server/mod.rs

This adds a connection pool to the Client that is used by default. It
accepts any other NetworkConnector, and simply acts as a
NetworkConnector itself. Other Pools can exist by simply providing a
custom NetworkConnector. This Pool is only used by default if you also
use the default connector, which is `HttpConnector`. If you wish to use
the Pool with a custom connector, you'll need to create the Pool with
your custom connector, and then pass that pool to the
Client::with_connector.
This also adds a method to `NetworkStream`, `close`, which can be used
to know when the Stream should be put down, because a server requested
that the connection close instead of be kept alive.
Closes #363
Closes #41 
------
cc @jamwt

feat(client): add a Connection Pool

---

src/header/common/mod.rs

That way, third-parties can keep using the `header!` macro, which
now requires the `test_header!` macro as well.
Considering the `header!` macro is exported and part of the public
API, it was not desired to prevent it's usage in any way.

fix(header): exporting test_header! macro

---

src/header/common/if_range.rs
src/header/common/mod.rs

feat(headers): Add If-Range header

---

examples/headers.rs
src/header/common/mod.rs

Closes #490
/cc @pyfisch @maximih

fix(header): make test_module of header! optional

---

src/http.rs

fix(http): keep raw reason phrase in RawStatus

---

src/header/common/mod.rs
src/header/common/upgrade.rs

Parses protocols into a name and a value part matching the RFC.
An enum contains all registered or known protocols, but contains
an extension variant.
Closes #480
BREAKING CHANGE: Upgrade header Protocol changed.

feat(headers): Parse Upgrade header protocols further

---

src/header/common/accept.rs
src/header/common/access_control_allow_headers.rs
src/header/common/access_control_allow_methods.rs
src/header/common/access_control_max_age.rs
src/header/common/access_control_request_headers.rs
src/header/common/access_control_request_method.rs
src/header/common/allow.rs
src/header/common/authorization.rs
src/header/common/cache_control.rs
src/header/common/connection.rs
src/header/common/content_type.rs
src/header/common/cookie.rs
src/header/common/etag.rs
src/header/common/host.rs
src/header/common/if_range.rs
src/header/common/last_modified.rs
src/header/common/mod.rs
src/header/common/pragma.rs
src/header/common/set_cookie.rs
src/header/internals/item.rs
src/header/mod.rs
src/header/parsing.rs
src/header/shared/charset.rs
src/header/shared/encoding.rs
src/header/shared/entity.rs
src/header/shared/language.rs

src/header/parsing.rs now uses unsafe get_unchecked() again, I don't
know why it was removed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hyperium/hyper/503)

refactor(headers): Improve docs, fix nits, make formatting faster

---

src/header/common/access_control_allow_origin.rs

The spec says the header can be either a `*`, `null` or an URL.
Improve docs of header.
BREAKING CHANGE: Add variant to Access-Control-Allow-Origin enum

feat(headers): Allow `null` value in Access-Control-Allow-Origin

---

src/client/mod.rs
src/client/request.rs
src/client/response.rs
src/error.rs
src/header/mod.rs
src/http.rs
src/lib.rs
src/method.rs
src/server/mod.rs
src/server/request.rs
src/uri.rs

The old names followed the old style of including the module name and
"Error" in each variant. The new style is to refer to an error from its
owning module, and variants are now scoped to their enum, so there's no
need to include the enum name in the variant name.
BREAKING CHANGE: The terms `Http` and `Error` have been removed from the Error
type and its variants. `HttpError` should now be accessed as `hyper::Error`,
and variants like `HttpIoError` should be accessed as `Error::Io`.

refactor(error): remove redundant parts of error names

---

benches/client.rs
src/client/mod.rs
src/client/pool.rs
src/error.rs
src/mock.rs
src/net.rs

The errors from openssl were previously boxed into a
Box<std::error::Error>, which lost some specifics and made it difficult
to match against. To solve this, an `Ssl` variant is added to the
`Error` enum of hyper, and is returned when openssl returns specific
errors.
Closes #483
BREAKING CHANGE: Adds a variant to `hyper::Error`, which may break any
exhaustive matches.
cc @jdm

feat(error): add Ssl variant to hyper::Error

---

.travis.yml

Generates a test coverage using kcov on travis. The coverage is only
generated for beta builds. kcov requires using sudo, so beta builds
can't run on container infrastructure anymore.
Closes #44 
[![Coverage Status](https://coveralls.io/repos/pyfisch/hyper/badge.svg?branch=kcov)](https://coveralls.io/r/pyfisch/hyper?branch=kcov)

chore(travis): Enable test coverage generation

---

src/net.rs

On OSX, calling shutdown a second time will return a NotConnected error.
This commit will just ignore it, since we can agree that if a stream is
"not connected", it is in fact "closed".
Closes #508 
/cc @wezm
---------
I couldn't decide whether to use conditional compilation to only do this on OSX, but eventually figured the reasoning in the commit message.

fix(net): ignore NotConnected error in NetworkStream.close

---

examples/client.rs
src/client/request.rs

Only call close() in the Response, which should already return a
responding `Connection: close`.
Closes #519

fix(client): dont call close() inside Request

---

benches/client.rs
src/client/mod.rs
src/client/pool.rs
src/mock.rs
src/net.rs

The client no longer drops the old `Connector` instance, along with its
entire context (such as the settings and pooled connections in the case
of a `Pool` connector); rather, it passes the SSL verifier on to the
`Connector` so that it uses it for any future connections that it needs
to establish.
A regression test is included.
Closes #495

fix(client): keep the underlying connector when setting an SSL verifier

---

benches/client.rs
src/client/mod.rs
src/client/pool.rs
src/client/request.rs
src/mock.rs
src/net.rs

BREAKING CHANGE: Any custom Connectors will need to change to &self in
the connect method. Any Connectors that needed the mutablity need to
figure out a synchronization strategy.
Request::with_connector() takes a &NetworkConnector instead of &mut.
Any uses of with_connector will need to change to passing &C.

feat(net): remove mut requirement for NetworkConnector.connect()

---

Cargo.toml

Coming into Rust 1.0, I hope crates will behave well (semver) when making breaking changes. So, we should be stricter about what versions we know work, instead of just telling users "Set DepA's version to 0.X in your Cargo.lock to fix that".
Bumping versions dependencies is easy, and can save people headaches.

chore(cargo): set stricter versions for dependencies

---

src/header/common/cache_control.rs
src/header/common/cookie.rs
src/header/common/mod.rs
src/header/common/set_cookie.rs

The `deref!` macro is largely for internal use, however, it must be exported
because the header! macro uses it. As deref! is also a particularly
general name, this renames it to __hyper__deref! to prevent name
clashes.

Rename tm! to __hyper__tm!, and export it, and rename deref!

---

src/server/mod.rs
src/server/response.rs

BREAKING CHANGE: Usage of Response.deconstruct() and construct() now use
a &mut Headers, instead of the struct proper.

feat(server): check Response headers for Connection: close in keep_alive loop

---

src/client/mod.rs

Sean, nice meeting you at the launch meetup today!
I am not sure what you are looking for in issue #351, here is a first minimal attempt. Comments welcome :)

Issue 351: default trait for client

---

src/header/shared/charset.rs
src/header/shared/encoding.rs
src/header/shared/entity.rs
src/header/shared/httpdate.rs
src/header/shared/language.rs
src/header/shared/quality_item.rs

This allows more precise errors in the future and makes it easier to use
the try!() macro in some cases.
BREAKING CHANGE: Error enum extended. Return type of header/shared/
types changed.

feat(headers): return hyper::Error instead of () from header components

---

src/buffer.rs

``cmp::min(cap * 4, MAX_BUFFER_SIZE) - cap'' can underflow when
cap > MAX_BUFFER_SIZE.  cap can exceed MAX_BUFFER_SIZE because
Vec::reserve aligns to powers of two.
Discovered by Matt Howard <themdhoward@gmail.com>
You can trigger this bug by requesting from the "server" implemented here:
perl -e'print "HTTP/1.1 200 OK\r\nServer: " . " "x900000000 . "\r\n"' | nc -l -p 8080
Regards,
Stacey Ell

fix(buffer): check capacity before resizing

---

src/header/common/mod.rs

Allow RangeUnit to be used from user crates.

refactor(headers): expose RangeUnit in hyper::header

---

Cargo.toml
examples/client_http2.rs
src/client/mod.rs
src/client/request.rs
src/client/response.rs
src/error.rs
src/http11.rs
src/http2.rs
src/lib.rs
src/message.rs
src/mock.rs

This PR adds initial support for HTTP/2 requests.
It introduces a new pair of traits: `HttpMessage` and `Protocol`.
The `HttpMessage` trait provides an API that abstracts the sending and receiving of HTTP messages away from the concrete implementation of the underlying protocol.
The `Protocol` trait provides an API for constructing new `HttpMessage`s.
The `Request` and `Response` structs are refactored to internally use a `Box<HttpMessage>` for their HTTP communication requirements.
The `Client` has a new public method: `with_protocol`. This provides an API for plugging in a particular `Protocol` implementation that will then be used for constructing the `HttpMessage` instances that are passed to the `Request` struct constructor.
The implementation of this API (i.e. the two traits) for …

feat(client): initial support for HTTP/2

---

src/error.rs

BREAKING CHANGE: Adds a new variant to public Error enum. The proper fix
is to stop matching exhaustively on `hyper::Error`.

feat(error): add private __Nonexhaustive variant to Error

---

README.md

Also, move the crates.io badge beyond the license badge to optimize the badge 
row's utility as a status dashboard as discussed in #525.

Add a license badge to README.md

---

benches/client.rs
src/error.rs
src/header/common/accept_ranges.rs
src/header/common/access_control_allow_origin.rs
src/header/common/authorization.rs
src/header/common/cache_control.rs
src/header/common/cookie.rs
src/header/common/expect.rs
src/header/common/host.rs
src/header/common/if_none_match.rs
src/header/common/if_range.rs
src/header/common/mod.rs
src/header/common/pragma.rs
src/header/common/set_cookie.rs
src/header/common/upgrade.rs
src/header/common/vary.rs
src/header/internals/item.rs
src/header/mod.rs
src/header/parsing.rs

Header::parse_header() returns now a hyper Result instead of an option
this will enable more precise Error messages in the future, currently
most failures are reported as ::Error::Header.
BREAKING CHANGE: parse_header returns Result instead of Option, related
code did also change

refactor(headers): errors for parse_header

---

examples/client.rs
examples/client_http2.rs
src/client/mod.rs
src/http/h1.rs
src/lib.rs
src/mock.rs
src/net.rs

Connector::connect already used &self, and so would require
synchronization to be handled per connector anyway. Adding Sync to the
Client allows users to setup config for a Client once, such as using a
single connection Pool, and then making requests across multiple
threads.
Closes #254
BREAKING CHANGE: Connectors and Protocols passed to the `Client` must
now also have a `Sync` bounds, but this shouldn't break default usage.

feat(client): impl Sync for Client

---

src/header/common/authorization.rs
src/header/common/mod.rs

this allows servers/clients using bearer tokens
to work out of the box without having to implement
their own bearer scheme. while this would be pretty
easy seems like a more general thing that is useful
for a lib like this

feat(headers): add bearer token support

---

src/lib.rs

The HTML root URL is not supposed to point at the index resource, but
represent the path that can be used to construct the full URL of the
crate's components.

docs(hyper): fix html root url

---

.travis.yml
Cargo.toml
README.md
examples/hello.rs
examples/server.rs
src/client/mod.rs
src/client/pool.rs
src/client/request.rs
src/error.rs
src/header/common/set_cookie.rs
src/http/h1.rs
src/http/h2.rs
src/http/message.rs
src/lib.rs
src/mock.rs
src/net.rs
src/server/mod.rs

- `Server::https` was changed to allow any implementation of `Ssl`.
- `Server` in general was also changed. This was to help the design of `Ssl`, and will also allow a future Pull Request to allow the `Server` to support an `Iterator` design, and accepting single requests; generally just not requiring that a `Handler` (and its task pool) be used.
- `HttpConnector` no longer uses SSL; use `HttpsConnector` instead. **NOTE: Servo**
- `Client` will use `DefaultConnector`, which will be `HttpsConnector` by default. If the openssl feature is disabled, it will be `HttpConnector`. Those using `Client::new()` should be unaffected.
cc #573 #131 #541 #575 @reem @retep998 @Manishearth

feat(ssl): redesign SSL usage

---

src/header/common/mod.rs
src/header/common/range.rs

I've started working on `Content-Range` header and realized that my previous implementation of `Range` header was wrong. `RangeSpecs` make sense only for byte ranges and all custom range units can have arbitrary strings as their values.
I've modified the code to reflect that, but there is one thing for which I need your feedback:
I've used `Range::Other` for custom ranges, as it IMO matches more closely naming in the RFC (`other-ranges-specifier`). The thing is that `Accept-Ranges` header uses `RangeUnit::Unregistered` for the same purpose, so it would make sense to decide on one them and use it consistently.
This is kinda a breaking change. However since the `Range` header was introduced only a week ago, I'm not sure, if I should mark it as such.

refactor(headers):  improve `Range` header adherence to HTTP spec

---

.travis.yml
benches/client.rs

In 53bba6e , ssl usage was improved. The existing benchmark
implementation wasn't adjusted though.
This commit fixes the client benchmark to work with the latest nightly
rust and instructs travis to try compile the benchmarks
when rustc nightly is used. This should prevent such kind of breakage
in future.

fix(benches): adjust to missing `set_ssl_verifier`

---

Cargo.toml

On OSX 10.10, attempting to run `cargo test` will yield a
[linker error](https://gist.github.com/Byron/b7a50cdcf7c60234335d).
Just removing the feature fixes the issue, even though I am not
sure if it is breaking something further down the line.

fix(cargo): fix linking on OSX 10.10

---

src/net.rs

Hi,
I've been having trouble connecting to some SNI-enabled websites, and noticed that the Ssl instance in wrap_client seems to be thrown away after set_hostname is called.  This commit passes the Ssl instance to SslStream and fixed my issue.
Regards,
Stacey Ell

fix(client): use Ssl instance in creation of SslStream

---

Cargo.toml
src/http/h2.rs
src/lib.rs

This PR moves hyper to use the latest version of solicit, where a few new features were. Only a few minor changes to the internals of the `h2` module were required.
Includes a regression test making sure that `error::Error` remains `Send + Sync`.
Closes #580

refactor(http2): move to solicit v0.4

---

src/client/request.rs
src/client/response.rs

This will always be the last URL that was used by the Request, which is
useful for determining what the final URL was after redirection.
BREAKING CHANGE: Technically a break, since `Response::new()` takes an
additional argument. In practice, the only place that should have been
creating Responses directly is inside the Client, so it shouldn't
break anyone. If you were creating Responses manually, you'll need to
pass a Url argument.

feat(client): add url property Response

---

src/error.rs
src/header/common/access_control_allow_origin.rs

Access-Control-Allow-Origin origins are URLs but they do not need to
be valid, they should just be compared as strings. So to support
invalid URLs hyper should use a string instead.
solves #562
BREAKING CHANGE: Access-Control-Allow-Origin does no longer use Url

refactor(headers): use String in Access-Control-Allow-Origin header

---

src/http/mod.rs

fix(http): no longer keep alive for Http1.0 if no Connection header

---

Cargo.toml
src/header/common/mod.rs
src/header/mod.rs
src/http/mod.rs
src/lib.rs
src/method.rs

This is behind a Cargo feature to avoid forcing downstream users to
depend on `serde`. It is needed for Servo IPC to work.

Add optional serialization of common types via `serde`.

---

src/status.rs

Implment the `Hash` trait for the `StatusCode` enum.
Resolves issue #614

feat(status): implement `Hash` for `StatusCode`

---

Cargo.toml
src/client/mod.rs
src/client/pool.rs
src/client/request.rs
src/http/h1.rs
src/http/h2.rs
src/http/message.rs
src/lib.rs
src/mock.rs
src/net.rs
src/server/mod.rs

While these methods are marked unstable in libstd, this is behind a
feature flag, `timeouts`. The Client and Server both have
`set_read_timeout` and `set_write_timeout` methods, that will affect all
connections with that entity.
BREAKING CHANGE: Any custom implementation of NetworkStream must now
implement `set_read_timeout` and `set_write_timeout`, so those will
break. Most users who only use the provided streams should work with
no changes needed.
Closes #315 
@reem r?

feat(net): add socket timeouts to Server and Client

---

src/net.rs

This allows HttpStream and HttpListener to be created from raw
sockets similar to their Tcp counterparts. It also fixes up the
signature from i32 to RawFd for the AsRawFd method.
This is particularly useful for out of process listeners, socket
activation and more.

feat(raw-fd): implement FromRawFd/FromRawSocket

---

src/net.rs
src/server/request.rs

- also adds downcasting to `NetworkStream`s, fixes #521 
- It's possible to try to get a reference to the NetworkStream inside HttpsStream<T>, by doing `req.ssl::<SslStream>()`. fixes #627

add ssl() method to server Requests

---

src/client/mod.rs
src/client/pool.rs
src/client/response.rs
src/http/h1.rs
src/mock.rs
src/net.rs

When an Http11Message knows that the previous response should not
have included a body per RFC7230, and fails to parse the following
response, the bytes are shuffled along, checking for the start of the
next response.
Closes #640

fix(client): be resilient to invalid response bodies

---

src/header/mod.rs

compare the raw representations of the headers for the lack of a better alternative
helpful when asserting HttpRequest/ HttpResponse in tests elsewhere

feat(headers): add PartialEq impl for Headers struct

---

src/client/mod.rs

I'm building a client interface on top of hyper for an rest API that makes use of the HTTP PATCH method. It felt a little awkward that there were methods for `get` `post` and `delete` but not `patch` so I wanted to make it less awkward for others.

feat(client): add patch method to Client builder interface

---

src/server/mod.rs
src/server/request.rs

Server keep-alive is now **off** by default. In order to turn it on, the
`keep_alive` method must be called on the `Server` object.
Closes #368

fix(server): use a timeout for Server keep-alive

---

.travis.yml
benches/client.rs
src/server/listener.rs

Also ensure that `cargo bench` runs successfully on travis; the old
`cargo bench ... || :` has the effect of ignoring any errors in it.

chore(nightly): remove ()'s and fix benchmarks for nightly

---

.travis.yml
benches/client.rs
src/client/mod.rs
src/server/listener.rs

Improve the compile-time of downstream crates that use RequestBuilder,
by not forcing them to remonomorphise and recompile its non-generic
methods when they use it: with this change, they can just call the
precompiled versions in the `hyper` object file(s). The `send` method is
the major culprit here, since it is quite large and complicated.
For an extreme example,
extern crate hyper;
fn main() {
hyper::Client::new().get("x").send().unwrap();
}
takes ~4s to compile before this patch (i.e. generic RequestBuilder) and
~2s after. (The time spent interacting with LLVM goes from 2.2s to
0.3s.)
BREAKING CHANGE: `RequestBuilder<U>` should be replaced by `RequestBuilder`.

refactor(client): make RequestBuilder non-generic

---

src/net.rs
src/server/listener.rs
src/server/mod.rs

This allows Servers to be started on existing TcpListeners.
Progress towards iron/iron#386

Add hooks for HttpListener and HttpsListener to be started from existing listeners.

---

Cargo.toml
src/header/common/cookie.rs
src/header/common/set_cookie.rs
src/header/shared/mod.rs
src/http/h2.rs

chore(dependencies): update openssl to 0.7 and cookie to 0.2

---

src/header/common/access_control_allow_credentials.rs
src/header/common/mod.rs

There is only one acceptable value for this header, "true", so
there header struct is unit-like (no fields nor data inside). See
documentation and tests for more info. Case insensitive.
Closes #655

feat(headers): Add Access-Control-Allow-Credentials header

---

Cargo.toml

~~A recent update in url triggered a version split in my application and
broke my build.~~
~~Since hyper is still compatible with 0.2, I think it might make sense to
still allow that version.~~

chore(cargo): Update url crate to 0.5

---

Cargo.toml
benches/client.rs
src/client/mod.rs
src/client/pool.rs
src/client/request.rs
src/http/h1.rs
src/http/h2.rs
src/http/message.rs
src/mock.rs
src/net.rs
src/server/mod.rs
src/server/request.rs

Methods added to `Client` and `Server` to control read and write
timeouts of the underlying socket.
Keep-Alive is re-enabled by default on the server, with a default
timeout of 5 seconds.
BREAKING CHANGE: This adds 2 required methods to the `NetworkStream`
trait, `set_read_timeout` and `set_write_timeout`. Any local
implementations will need to add them.
-----
Adding this in anticipation of bumping the minor version to `0.7`, so including other breaking changes.

feat(all): add socket timeouts

---

src/server/request.rs

fix(server): Removed check for GET/HEAD request when parsing body 

---

src/header/common/content_disposition.rs
src/header/parsing.rs

Move the extended parameter parser from the `Content-Disposition` header implementation into the common header parsing module. This allows crates that use Hyper to parse [RFC 5987](https://tools.ietf.org/html/rfc5987)-compliant header parameter values.
Add tests based on the examples given in the RFC.

feat(headers): add extended parameter parser to the public API

---

src/header/parsing.rs

Adds:
* the reverse of `parse_extended_value()`, via `fmt`
* derived traits, so that `ExtendedValue` can be used, for example, as a struct member
* docs for ExtendedValue members
With the first two features, I've implemented the (de)serialization of the [`username*` parameter for RFC 7616](https://tools.ietf.org/html/rfc7616#section-3.4).

Additional ExtendedValue API

---

src/client/mod.rs

Protocol doesn't extend Debug so we have to leave that out of the
output unfortunately.

feat(client): Implement Debug for Client

---

src/buffer.rs

in `maybe_reserve` we have such code
let new = self.buf.capacity() - self.buf.len();
unsafe { grow_zerofill(&mut self.buf, new) }
the original behavior of `grow_zerofill` in such case cause
rewriting the memory behind the allocated vector.

fix(buffer): prevent possible buffer overflow in `grow_zerofill`

---

src/status.rs

The official IANA list at
http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
has two new status codes that are missing from the hyper status list.

feat(status): add HTTP statuses 421 and 451

---

src/header/common/cache_control.rs
src/header/common/content_length.rs
src/header/common/mod.rs
src/header/common/range.rs
src/header/common/transfer_encoding.rs
src/header/parsing.rs

HeaderX: a
HeaderX: b
MUST be interpreted as
HeaderX: a, b
See: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
Fixes #683

Correctly handle repeated headers.

---

src/net.rs

SSL libraries other than OpenSSL don't necessarily have the ability to
easily create server and client side connections at the same time. This
is backwards compatible due to blanket impls.
Closes #756

feat(net): Split Ssl into SslClient and SslServer

---

.travis.yml

'sudo: false' is now default on Travis CI.

Remove now default 'sudo: false'.

---

src/client/mod.rs
src/client/pool.rs
src/client/request.rs
src/http/h1.rs

This works by configuring proxy options on a `Client`, such as `client.set_proxy("http", "127.0.0.1", "8018")`.
Closes #531

feat(client): add Proxy support

---

examples/client.rs
src/client/mod.rs
src/client/pool.rs
src/client/proxy.rs
src/client/request.rs
src/http/h1.rs
src/http/message.rs
src/mock.rs
src/net.rs
src/server/response.rs

fix(client): fix Host header when using a Proxy

---

Cargo.toml
src/lib.rs
src/net.rs

Additionally disables SSLv2 and SSLv3, as those are universally considered
unsafe.
Closes #472

feat(ssl): enable hostname verification by default for OpenSSL

---

src/net.rs
src/server/mod.rs

An oversight from the original implementation of the Ssl split.

fix(server): Switch Ssl to SslServer in bounds

---

src/client/pool.rs

Mutex's impl has a 'static bound on the inner type until 1.8, so we have
to explicitly specify that to keep compatible.

fix(client): Manually impl Debug for PooledStream

---

examples/hello.rs

I'm not exactly sure of the reason, but without this semicolon, the example only used one thread.
After adding the semicolon, threads spawned up as expected.
```
$ rustc --version
rustc 1.9.0 (e4e8b6668 2016-05-18)
```
Checked the threads in `htop` command.
And I'm using ubuntu. Please let me know if you need more details.

Without this semicolon, multiple threads didn't spawn properly

---

src/client/response.rs

In case someone reads the documentation for `client::Response` without
having read the documentation for the `client` module first, they might
wonder what the `Read` impl actually reads.
Let's clarify it by annotating the `Read` impl.

client: Make it clear what the `Read` impl for `Response` does

---

src/header/common/access_control_allow_credentials.rs
src/header/common/authorization.rs
src/header/common/cache_control.rs
src/header/common/content_disposition.rs
src/header/common/content_length.rs
src/header/common/cookie.rs
src/header/common/expect.rs
src/header/common/host.rs
src/header/common/if_range.rs
src/header/common/mod.rs
src/header/common/pragma.rs
src/header/common/prefer.rs
src/header/common/preference_applied.rs
src/header/common/range.rs
src/header/common/set_cookie.rs
src/header/common/strict_transport_security.rs
src/header/internals/mod.rs
src/header/internals/vec_map.rs
src/header/mod.rs

On (weak machine) consistent small benchmark I've been using to measure impact, these changes caused an increase from ~28k req/s to ~36k req/s.

perf(headers): use a VecMap, and check name against literals

---

src/client/connect.rs
src/client/mod.rs
src/header/common/accept_ranges.rs
src/header/common/content_range.rs
src/header/common/host.rs
src/header/common/prefer.rs
src/header/common/preference_applied.rs
src/header/common/range.rs
src/header/mod.rs
src/header/parsing.rs
src/header/shared/charset.rs
src/header/shared/entity.rs
src/http/buffer.rs
src/http/conn.rs
src/server/message.rs
src/server/response.rs

Some refactorings, most were suggested by clippy.

Clippy run and derive Default for Buffer

---

src/client/mod.rs

Let the user specify a custom TLS wrapper for proxied connections

---

src/http/conn.rs
src/http/h1/encode.rs
src/http/h1/parse.rs
src/http/mod.rs
tests/client.rs

This requires a Handler that uses chunked encoding to call `encoder.close()` when it is done.
Closes #831

feat(client): add method to end a chunked body for a Request

---

src/error.rs

Displays the inner error for Error types with inner errors instead of just displaying the description.
References #694

Display impl for Error shows better information

---

src/header/internals/item.rs
src/header/mod.rs

> If you get a mutable reference to a typed header it is possible to make
the two representations be out of sync. To avoid this, after parsing the
raw part it should be removed.
>
> Closes #821 
Rebase with a test added.
Closes #833

fix(headers): Remove raw part when getting mutable reference to typed header

---

src/header/common/access_control_allow_credentials.rs
src/header/common/access_control_allow_origin.rs
src/header/common/authorization.rs
src/header/common/cache_control.rs
src/header/common/connection.rs
src/header/common/content_disposition.rs
src/header/common/content_length.rs
src/header/common/cookie.rs
src/header/common/expect.rs
src/header/common/host.rs
src/header/common/if_none_match.rs
src/header/common/if_range.rs
src/header/common/mod.rs
src/header/common/origin.rs
src/header/common/pragma.rs
src/header/common/prefer.rs
src/header/common/preference_applied.rs
src/header/common/range.rs
src/header/common/referrer_policy.rs
src/header/common/set_cookie.rs
src/header/common/strict_transport_security.rs
src/header/common/upgrade.rs
src/header/common/vary.rs
src/header/internals/item.rs
src/header/mod.rs
src/header/parsing.rs
src/header/raw.rs

The `Raw` type repesents the raw bytes of a header-value.
Having a special type allows a couple of benefits:
- The exact representation has become private, allowing "uglier"
internals. Specifically, since the common case is for a header to only
have 1 line of bytes, an enum is used to skip allocating a Vec for only
1 line. Additionally, a Cow<'static, [u8]> is used, so static bytes
don't require a copy. Finally, since we can use static bytes, when
parsing, we can compare the incoming bytes against a couple of the most
common header-values, and possibly remove another copy.
- As its own type, the `Headers.set_raw` method can be generic over
`Into<Raw>`, which allows for more ergnomic method calls.
BREAKING CHANGE: `Header::parse_header` now receives `&Raw`, instead of
a `&[Vec<u8>]`. `Raw` …

feat(header): introduce header::Raw

---

src/net.rs

Openssl::with_cert_and_key is often useless in its current form: in most setups, you need to provide the intermediate certificate chain to openssl. One way would be to change with_cert_and_key to allow passing a third file containing the authority chain. But fortunately, we have another option: openssl accepts combined certificates (your certs, then whatever certs you need to link it to the widely distrubuted ones). This is not exotic, both nginx and apache use this setup.
As far as I can tell, this should not break anything, and would fix https support for all libraries relying on with_cert_and_key...

accept cert chain files as well as single cert files

---

src/http/conn.rs

Deduplicate and refactor code in `State.update`. The method is now more concise. Formatted with rustfmt because I got lazy to format it manually, but I may do that if it is preferable.

Dedup code in connection state update.

---

doc/guide/server.md

The `on_response` function requires the struct `Text` to have had `worker_rx` set, for the `question` path.

Fix guide example to save receiver for later use by response handler.

---

src/http/conn.rs
src/http/h1/parse.rs

- faster fmt::Write
- HTTP/1.1 Pipelining
- If server wants to write body just after writing head, call on_response_writable immediately, skipping a trip around the event loop (and epoll calls).

A couple performance boosts

---

README.md

As briefly talked about in #811.
If the 1.0 issue milestone had an issue for aync IO I'd remove that sentence since it's just going to get out of date.

Note on pre 1.0

---

src/header/internals/cell.rs
src/header/internals/item.rs
src/header/mod.rs

Make Headers::remove return the header

---

Cargo.toml

In the process of updating the dependencies of another far upstream package that eventually includes hyper, I noticed that `num_cpus` had finally stabilized and made a 1.0 release. There were no code changes in the `1.0` release from `0.2.13` (https://github.com/seanmonstar/num_cpus/commit/7aab1fbc30b9bf39e74b0624dc037af694ce4da3)
The tests for hyper pass on my machine.

refactor(version): bump version of num_cpus to 1.0

---

.travis.yml
doc/guide/server.md
examples/server.rs
src/client/mod.rs
src/server/request.rs
src/uri.rs

Fixes #896 and #897.
Also improve RequestUri tests.

feat(server): add path() and query() to Request

---

src/header/common/mod.rs
src/header/common/warning.rs

Implements Warning header from RFC7234
Closes #883

feat(headers): add Warning header

---

src/client/mod.rs
src/error.rs

In the scenario where a request is started on the `Client`, the client
has a full slab, and sockets for a *different* domain are idling in
keep-alive, the new request would previously cause the client to panic!.
This patch adds a `spawn_error` handler which attempts to evict an idle
connection to make space for the new request. If space cannot be made,
the error handler is run (passed `Error::Full`) and the `Handler` is
dropped.
This is a breaking change because of the new variant of `Error`.
Some inefficient use of `Vec` in the client was replaced with `VecDeque`
to support push/pop from either end.

Evict idle connections when client is full

---

src/http/conn.rs

We observed an issue where connection were not ever entering the
keep-alive state due to a bug with `State::update`. The issue is
resolved with resetting the write state to KeepAlive when it arrives as
KeepAlive. Otherwise, it would be marked incorrectly as Closed.
The `trace!` lines in here are useful for debugging keep-alive issues so
I've left them in.

fix(client): keep-alive works as intended now

---

src/client/connect.rs
src/client/mod.rs

When loading up a client suddenly with thousands of connections, the
default DNS worker count of four cannot keep up and many requests
timeout as a result. Most people don't need a large pool, so making this
configurable is a natural choice.

feat(client): DNS worker count is configurable

---

src/client/mod.rs
src/http/conn.rs
src/http/mod.rs
src/server/mod.rs

I've had a couple of instances during stress testing now where
Conn::ready would overflow its stack due to recursing on itself. This
moves subsequent calls to ready() into a loop outside the function.
`Conn::ready()` takes `mut self` so the loop needs to do an ownership dance to keep trying. Would love to hear a better way to achieve this.

fix(http): stackoverflow in Conn::ready

---

src/client/mod.rs
src/http/conn.rs
src/server/mod.rs

We've been seeing a strange number of timeouts in our benchmarking.
Handling spurious timeouts as in this patch seems to fix it!
Note that managing the `timeout_start` needs to be done carefully. If
the current time is provided in the wrong place, it's possible requests
would never timeout.

fix(http): Connection checks for spurious timeouts

---

src/header/common/referrer_policy.rs

Instead of parsing one value in the `ReferrerPolicy` struct, allow for a list and use the last value. I believe this is what the ticket mentions, but I could have misinterpreted.
Closes #882

Referrer-Policy Header

---

src/client/mod.rs
src/http/conn.rs

This includes improvements to client error handling, keep-alive strategy, and fixes a busy-loop. Sorry for putting these all in one PR, but they build on each other and it's still relatively short. Probably makes sense to review commit at a time.

Misc client fixes

---

src/net.rs

This should fix some busy looping when using OpenSSL. For example, if
the transport was blocked on a read, it wasn't surfaced to the
`http::Conn` and so the wrong interest was registered with the event
loop. Registering for the wrong interest triggered calls to
`http::Conn::ready()` which were unable to make progress.

fix(net): Implement `blocked()` for OpensslStream

---

src/header/common/referrer_policy.rs

Support for strict-origin and strict-origin-when-cross-origin in referer
policy required for imporving network security. This pull request will attempt
to add missing pieces of referrer policy.

feat(headers): Add strict-origin and strict-origin-when-cross-origin referer policy

---

src/buffer.rs

Hello!
I'm using the latest 0.9.x release on a project I'm working on, and I'm quite in need of this method. As I'd like to release my project on crates.io soon, I was hoping you would merge this in and then release a new version of hyper 0.9.x on crates.io. I understand that 0.9.x has effectively been abandoned in favor of 0.10, so I hope it won't be too much trouble.
Thanks!
Sergio

Add 'take_buf' method to BufReader.

---

src/header/common/access_control_allow_methods.rs
src/header/common/access_control_request_method.rs
src/header/common/allow.rs

`hyper::method::Method` is no longer accessible by users of hyper.
Must use `hyper::Method` instead.
All tests and examples now pass.

[Tokio Branch] Fix examples failing in `cargo test`

---

src/client/mod.rs

This allows the client to override the host header. The feature is
useful for times when an address is provided and the server has a
virtual host mapping.

fix(client): only set Host header when not present

---

src/body.rs
src/client/mod.rs
src/client/request.rs
src/client/response.rs
src/lib.rs
src/server/mod.rs
src/server/request.rs
src/server/response.rs

Create a `body::Body` struct, exposed as `hyper::Body` that wraps a `tokio_proto`-`Body`.
Added `std::From` methods to convert from `tokio_proto`-`Body` to `body::Body` and back.
Made naming of `Body` declarations somewhat consistent across `Server`, `Server Request`, `Server Response`, `Client`, `Client Request`, and `Client Response`.
Impl `Stream` for `body::Body` so that applications can read from the body as if it were a `tokio_proto::streaming`-`Body`
All examples still work and tests are passing (except those that were broken before this modification).
Part 1/2 to close #969

[Tokio Branch] Create a `body::Body` struct, exposed as `hyper::Body` that wraps a `tokio_proto`-`Body`.

---

src/client/connect.rs

These type aliases cause test build to fail due to strict LINT settings
If these types should be preserved (used outside the test suite), please let me know and I can instead disable the LINT for these types.

refactor(client): remove unused client type aliases

---

src/server/response.rs

`Response::set_status(&mut self, status: StatusCode)` sets the status of the response and does not return a mutable reference.

docs(server): fix Response::set_status() documentation

---

examples/client.rs
src/client/mod.rs
tests/client.rs

Hi,
Is there a reason these client functions require a &mut self? Makes
integrating this to our project much easier if they would be immutable.
Tests seem to pass.

fix(client): Client functions don't need &mut self

---

src/header/common/content_type.rs

docs(headers) Explain why content_type doesn't use generic `mime`.
For anyone that follows with the same question. 
Related to #991

Explain content_type assigned type

---

examples/server.rs
src/client/mod.rs
src/client/request.rs
src/error.rs
src/http/conn.rs
src/http/mod.rs
src/lib.rs
src/server/request.rs
src/uri.rs
tests/client.rs

Closes #1000
BREAKING CHANGE: The name of `RequestUri` has changed to `Uri`. It is no
longer an `enum`, but an opaque struct with getter methods.

feat(uri): redesign RequestUri type into Uri

---

benches/end_to_end.rs
examples/hello.rs
examples/server.rs
src/lib.rs
src/server/mod.rs
tests/server.rs

This commit refactors the `server` module as we discussed a bit offline.
The main changes are:
* The entry point is how `Http`, the implementation of `ServerProto`.
This type has a `new` constructor as well as builder methods to
configure it.
* A high-level entry point of `Http::bind` was added which returns a
`Server`. Binding a protocol to a port requires a socket address
(where to bind) as well as the instance of `NewService`. Internally
this creates a core and a TCP listener.
* The returned `Server` has a few methods to learn about itself, e.g.
`local_addr` and `handle`, but mainly has two methods: `run` and
`run_until`.
* The `Server::run` entry point will execute a server infinitely, never
having it exit.
* The `Server::run_until` method is intended as a graceful shutdown
mechanism. …

Refactor the server module

---

src/uri.rs

Remove usage of Url parse, add basic parse methods. 
Also add minimal error handling, default port/path handling (tests adjusted accordingly). 
https://github.com/hyperium/hyper/issues/1022

Refactor(uri): Remove usage of Url parse in Uri #1022

---

src/uri.rs

Remove Vec allocations in Uri parsing. Additionally, change some tests
to check the port.
https://github.com/hyperium/hyper/issues/1029

refactor(uri): Remove vec in uri parsing

---

src/uri.rs

Add also test parse authority without port

test(uri): fix URI parse error tests

---

src/client/connect.rs
src/client/mod.rs
src/client/request.rs
src/http/h2/mod.rs
src/uri.rs

test(lib): use public hyper::Url everywhere

---

examples/hello.rs
examples/server.rs

The "Finished" struct and "finished" method have been deprecated[0]
and don't show up in the futures docs. Prefer non-deprecated
features for users exploring the examples.
[0] https://github.com/alexcrichton/futures-rs/blob/0.1.10/src/future/mod.rs#L25

refactor(examples): remove use of depricated futures features

---

src/client/request.rs
src/http/buf.rs
src/http/conn.rs
src/http/h1/parse.rs
src/uri.rs

perf(header): Make Uri use MemSlice internally

---

src/uri.rs

Add a code block around the URI explanation to make it legible and add a missing backquote

docs(uri): fix rendering errors

---

benches/end_to_end.rs
src/client/mod.rs
src/client/request.rs
src/http/body.rs
src/http/chunk.rs
src/http/conn.rs
src/http/h1/encode.rs
src/http/io.rs
src/http/mod.rs
src/server/mod.rs
src/server/response.rs

This allows the outgoing stream (server::Response and client::Request) to be customized. The default is still `hyper::Body`, as it will be a fast, easy-to-use type. But now you can define the body stream to any type, `where T: Stream<Error=hyper::Error>, T::Item: AsRef<[u8]>`.
This address a large amount of what has been discussed in #953

feat(http): allow specifying custom body streams

---

src/server/mod.rs
src/server/request.rs

This implements `From<Message> for Request` and `Into<Message> for
Response`, allowing an `Http` instance to be used with a `TcpServer`
from tokio-proto.
Closes #1036
BREAKING CHANGE: This makes `Request.remote_addr` an
`Option<SocketAddr>`, instead of `SocketAddr`.
-----
@alexcrichton This would make hyper's `Http` compatible with `TcpServer`. Requiring a secondary trait to be able to get a `SocketAddr` felt like more of a pain, so instead I've settled on allowing the address to be an `Option`. Does it seem like `TcpServer` could gain the ability to collect the `SocketAddr` later, such as for 0.2, and we can make use of it then? If so, I can file a tracking bug.

feat(server): make Http compatible with TcpServer

---

src/uri.rs

`Url::parse` panicked if a questionmark is in the fragment part:
```
panicked at 'attempt to subtract with overflow', src/uri.rs:207
```
This was found by [cargo-fuzz](https://github.com/rust-fuzz/cargo-fuzz)

fix(url): fix panic when questionmark is in fragment

---

src/http/chunk.rs

The new From<Chunk> for Bytes uses self instead of chunk in its
implementation of From::from.  Change it to chunk to fix the build.

fix(http): Fix commit fac3d70c0b716157ba689ae2b8a0089b6afc9bdc

---

src/header/common/accept.rs
src/header/common/etag.rs
src/header/shared/entity.rs
src/header/shared/quality_item.rs

Bugs found using fuzzing in:
* `QualityItem` (fixed)
* `ETag` (fixed)
* `Authorization` header field (both simple and bearer schemes)
* `ContentType` header
* maybe more as the fuzzer is still running...
Do you want to include fuzzers in this repository?

[WIP] fix bugs in header field parsers

---

tests/client.rs

fix "use of deprecated item: renamed to `send`"

make tests pass

---

src/header/mod.rs

Add HeaderView.raw() which behaves identically to Headers.get_raw().

feat(headers): add HeaderView.raw()

---

benches/end_to_end.rs
examples/client.rs
src/client/connect.rs
src/client/mod.rs
src/client/request.rs
src/error.rs
src/header/common/content_disposition.rs
src/header/parsing.rs
src/http/h1/parse.rs
src/http/str.rs
src/lib.rs
src/uri.rs

Closes #1089 
BREAKING CHANGE: 
The `Url` type is no longer used. Any instance in the
`Client` API has had it replaced with `hyper::Uri`.
This also means `Error::Uri` has changed types to
`hyper::error::UriError`.
The type `hyper::header::parsing::HTTP_VALUE` has been made private,
as an implementation detail. The function `http_percent_encoding`
should be used instead.

feat(lib): remove extern Url type usage

---

src/header/common/preference_applied.rs
src/header/internals/item.rs
src/header/mod.rs
src/header/raw.rs

BREAKING CHANGE: This removes several deprecated methods for converting
Headers into strings. Use more specialized methods instead.

refactor(header): remove deprecated Header to_string APIs

---

src/client/mod.rs

This is useful for external structs which own (or have a reference to) a `Client` but have no access to the event loop the client is associated with.

feat(client): add Client::handle

---

CONTRIBUTING.md

Fix markdown in contributing so it displays correctly on github, and
also because of the irony.

docs(CONTRIBUTING): Fix markdown

---

src/version.rs

Hello. 
I'm using hyper to take apart some log requests and construct new requests from them. This is a simple change that matches a String back to the enum. The default case uses same unreachable!() macro that display uses.
Not sure if this has been addressed before, but since I needed it to go forward, figured I'd put a PR together for it.
Thanks,
liam
- [ x] The commit messages match the guidelines in https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md#git-commit-guidelines

feature(version): impl FromStr for HttpVersion

---

src/buffer.rs

this adds the ability to deconstruct a buffer into all of its parts
and the ability to create a buffer from all of its parts, this lets
users deconstruct the buffer, edit the reader, then build it back up
again without losing any information
Currently a whole heap of changes is coming to rust-websocket, some of the changes require that we handle streams generically and therefore we need better interoperability with other buffered reader implementations. The large changes (which had to be done all at once) are in cyderize/rust-websocket#80, and include the ability to upgrade a hyper request to a websocket connection.

feat(buffer): add from_parts and into_parts functions

---

src/net.rs

This both avoids a possible source of panics and also avoids eating a
file descriptor for each worker thread. When running with a lot of
those, this can start eating up quite a lot of the process's file
descriptor quota.

fix(server): don't dup the listener TCP socket.

---

src/http/body.rs
src/http/chunk.rs

The real reason to provide these implementations is so that `concat` on
the `Body` can work to easily join all the chunks into 1.

feat(chunk): implement Extend and IntoIterator for Chunk

---

src/header/common/location.rs
src/header/common/mod.rs
src/header/common/referer.rs
src/header/common/server.rs
src/header/common/user_agent.rs
src/header/mod.rs

Change the internal implementation of some simple headers to make them
more allocator friendly. Also add a constructor method to allow changing
the implementation in the future again.
The headers are:
- Location
- Referrer
- Server
- UserAgent
This change was suggested in #1104.
I've left out the Origin header for now because the internal implementation is different.
BREAKING CHANGES:
- Old code that creates the header structs directly will stop working.
- It's not possible to implement DerefMut for a Cow<'static,str>. Code
that needs to modify header after creation will stop working.

refactor(header): make some headers more allocator friendly

---

src/header/common/origin.rs

Change the internal representation of Origin to be more allocator
friendly. The internals of the Origin header are now private to allow
changing them in the future.
This change was suggested in #1104.
BREAKING CHANGES:
- Old code that accesses the Origin struct directly will stop working.

refactor(header): make Origin header more allocator friendly

---

src/client/response.rs
src/http/h1.rs

This ultimately allows end users to retrieve the current cipher from an SSL stream, which is needed for the Web.

Introduce Response::get_ref

---

src/server/mod.rs

As the title suggests, this adds a `local_addr` method to `Server` to retrieve the address that was resolved. This makes it possible to retrieve the resolved address when a `Server` instance is created with the `Server::http` or `Server:https` methods.

feat(server): add local_addr to retrieve resolved address

---

src/client/request.rs

Allow users to access the body of the request.
Useful when one wants to modify the request based
on the data in the body, e.g. to add checksum headers.

client(feat): add an accessor for the request body

---

src/header/common/origin.rs

Add support for Opaque origin header, serializing it to `null`.
https://html.spec.whatwg.org/multipage/browsers.html#concept-origin
Closes #1065

feat(headers): support Opaque origin headers

---

src/header/common/te.rs
src/header/shared/encoding.rs

This commit addresses issue 1109.
The `TE` header is used by a client to specify which
transfer encodings other than `chunked` it will accept.
It also specifies whether HTTP trailers are acceptable.
This commit also adds a `Trailers` variant to the
`hyper::header::shared::Encoding` enum.

feat(headers): add `TE` header struct

---

src/header/common/cookie.rs
src/header/internals/vec_map.rs

The `Cookie` header now has `get` and `set` methods, to tree the list of
cookies as a map.
Closes #1145
cc @dorfsmay

feat(header): change `Cookie` to be map-like

---

.travis.yml

* Move to the Trusty distro, since Precise is nearing end of life this year (https://blog.travis-ci.com/2017-04-17-precise-EOL)
* Add a `--verify` flag to avoid kcov segfaults. This was the reason why a 0% coverage was reported
* Link dead code to get more pessimistic results
---
The move to Trusty was also partially due to difficulties with running a `sudo`-less coverage testing with `kcov`. I have no hard evidence, but I had segfaults all the time in my personal project (even with `--verify`!) until I switched to Trusty.

chore(travis): fix Travis coverage testing

---

src/header/common/cookie.rs

Test corner cases that are easy to miss when coding such as equal sign
in the cookie value and empty and empty value.
The first thing I did when installing this new version was to run those manually and thought there was value in adding them, as they'd be easy to get wrong.
The extra formatting changes are due to rustfmt from my editor.

test(header): test valid corner cases

---

src/header/common/content_type.rs

This PR adds an utility function for`Content-Type: application/octet-stream` header.

feat(headers): add ContentType::octet_stream() constructor

---

src/header/common/cookie.rs

In the spirit of Postel's law, ignore invalid cookies rather than
completely discard the entire Cookie header, which is what the current
code does, and which will lead to confusion when dealing with headers
with invalid cookies injected by proxies and intermediate apps servers.
Cookies are injected at multiple different layers between the browser and the end server, proxies, load balancers, security appliances, A/B testing appliances, etc... some of them inject invalid cookies, it's fine to discard those, but in I'm opinion it is wrong to discard every cookie because one field is bad. The separation of cookies between semi-colon makes it easy enough to cleanly separate cookies, ignore the invalid ones, and keep the good ones.

Ignore invalid cookies

---

Cargo.toml
src/header/common/authorization.rs
src/lib.rs

See #1028. This is a cherry-pick of 529ad56 with fixed conflicts and using the newest version of the crate.
CC @M3rs

Backport to 0.10.x: refactor(header): Change to base64 serialize

---

Cargo.toml
src/header/common/access_control_allow_credentials.rs
src/header/common/access_control_allow_headers.rs
src/header/common/access_control_expose_headers.rs
src/header/common/access_control_request_headers.rs
src/header/common/connection.rs
src/header/common/content_disposition.rs
src/header/common/expect.rs
src/header/common/strict_transport_security.rs
src/header/common/upgrade.rs
src/header/common/vary.rs
src/header/mod.rs

BREAKING CHANGE: Some headers used `UniCase`, but now use
`unicase::Ascii`. Upgrade code to `Ascii::new(s)`.

refactor(lib): update unicase to 2.0

---

src/server/listener.rs

Errors are not that uncommon here when using TLS since the accept includes the TLS handshake. `error` is typically reserved for "someone needs to be paged" which is not the case here.

Drop logging verbosity of listener accept error

---

src/uri.rs

Fixes #1176.
All tests are passing so hopefully this didn't break anything!

fix(uri): fix parse for empty path and '/' or '?' in fragment

---

src/server/mod.rs

docs(server): refer to `bind` method, not `serve`

---

src/lib.rs

This macro isn't used anywhere, std now has an unimplemented macro
if we want to use it, and the nightly compiler now warns that this
unused.  This warning is a failure when compiling tests.

fix(lib): Remove unused unimplemented! macro.

---

src/client/response.rs
src/server/mod.rs

It's not particularly unexpected for the other end to drop off, and
error level logging is reserved for serious issues that need to be
corrected.
There are two error level logs remaining - when trying to attach a body
to messages that aren't supposed to have one, and when a non-UTF header
is encountered. Both of these would only be encountered due to
programmer error.

fix(logging): Don't error log for IO errors

---

src/header/common/cookie.rs
src/header/common/mod.rs

The commit dd03e723 changed Cookie implementation, but it also hided
Cookie header internal structure. So currently we don't have any way
to iterate cookie.
Add iter.

fix(header): Allow iterate cookie

---

src/http/body.rs
src/http/conn.rs
src/server/mod.rs

These seem mostly to be renames, with the exception of Unpark -> Notify, which includes a functional change. Needed so that travis will build with the `#![deny(warnings)]`.
In the test set using Notify, I'm unsure exactly what the `id` passed around should be referring to. Here I've ignored it when receiving, and just sent `0`, though that may not be the best solution.

fix(http,server): Update tests to use non-deprecated futures methods.

---

src/client/mod.rs

Remove requirement when calling client::Config::connector() that the connector implements Connect.
Removing this requirement allows users to set the connector back to UseDefaultConnector. Previously,
this was not possible.
I'm not sure if there's any specific reason for requiring Connect on this method, as far as I can tell from past commits it was just an included part in the original design?
My use case for this is setting the connector back to `UseDefaultConnector`, as well as opening up the possibility for a `UseHttpsConnector` or a similar marker type to be used in a wrapper builder around `Config`.
Tests fail, but as far as I can tell this is only because of deprecated things that hyper is using. Locally, if `#![deny(warnings)]` is temporarily commented out, all tests pass.

fix(client): remove config requirement for Connect

---

src/version.rs

The `FromStr` trait was implemented in the master branch too, `AsRef<str>` is not but it's rather useful when serializing and deserializing types (which is what I'm currently doing with my upcoming mocking/replaying library for reqwest).

feat(version): implement FromStr and AsRef<str> for Version

---

benches/server.rs

Added some benches to test TransferEncoding::chunked. I added two, one for just Hello World, and one for a lot of Hello Worlds.

test(server): add benches for TransferEncoding::chunked

---

src/header/common/content_length.rs
src/header/common/transfer_encoding.rs
src/http/request.rs

Following a brief discussion with @seanmonstar on `#rust`:
Update the docs for `Content-Length` and `Transfer-Encoding` to mention that they are mutually exclusive, and that setting one will unset the other, in accordance with RFC7230.
Also expand the docs for `Request::set_body` to say that chunked encoding is used by default, and mention how to disable this feature.

docs(headers): clarify TransferEncoding xor ContentLength

---

src/http/conn.rs
src/http/h1/decode.rs
src/http/io.rs

**Disclaimer**: Modifies `unsafe` (very slightly) in `read_from_io`
Summary: Its a pretty big CR, but I just change the types around.
More stuff:
Ideally, `io` and `decoder` would not be coupled, but that is above my pay grade.
`conn -> io, decoder`
Currently, this is what the dependencies look like:
`conn -> decoder -> io`
`conn`: Uses `Poll`
`decoder`:  Does not use `Poll`
`io`: Should use `Poll`
So I need to push `Poll` through decoder which, on the one hand, kinda sucks because there are more characters around, and it makes the tests harder to write. On the other hand, its the only good way to refactor `Buffered` to use things like `AsyncRead` and `AsyncWrite`.
Thoughts?

refactor(http): return poll more

---

src/header/common/content_type.rs

Fix a typo in ContentType header's doc

---

src/http/conn.rs
src/http/io.rs
src/http/mod.rs
tests/server.rs

feat(server): Handle 100-continue

---

Cargo.toml

Just a simple dependency update.

chore(dev): upgrade base64 to 0.6

---

src/http/response.rs

The Response body was previously inaccessible to application code. This
change allows applications that may wish to alter the Response based on
previous creation (or not) of the body to do so.
n.b. discussion in #1216 indicates this function may change in
0.12 or be removed in favour of some other api.
Closes #1216.

feat(server): Provide reference to Response body

---

src/http/conn.rs
src/http/h1/parse.rs
src/http/mod.rs
src/lib.rs
tests/client.rs
tests/server.rs

By knowing if the incoming Request was a HEAD, or checking for 204 or
304 status codes, the server will do a better job of either adding
or removing `Content-Length` and `Transfer-Encoding` headers.
Closes #1257

fix(server): improve detection of when a Response can have a body

---

src/header/common/authorization.rs

See https://tools.ietf.org/html/rfc7617

docs(headers): clarify Basic auth

---

src/http/h1/encode.rs
src/http/io.rs
src/mock.rs

Improved codegen, without allocations or function calls

perf(http): prefer ErrorKind::WouldBlock

---

src/http/body.rs

This change adds the ability to use Cow<'static, [u8]> and Cow<'static, str> for the body of a
HTTP request or response.
This makes it easier to create abstractions that serve static web pages, redirect messages and the
like.

feat(http): add Body::from(cow) for bytes and strings

---

src/lib.rs

fix(lib): Export hyper::RawStatus if the raw_status feature is enabled

---

src/header/common/content_type.rs

This only add new constructor ContentType::xml()
Cheers

feat(header): add ContentType::xml() constructor

---

src/server/mod.rs

Http and Server placed Send + Sync bounds on NewService implementations which
were not actually required given tokio's event loop model. Remove them to reduce
limitations on end users of hyper.

refactor(server): remove unneeded Send + Sync

---

src/proto/body.rs

When cow is a Cow::Owned, cow.to_owned() returns a Cow::Owned, which leads to infinite recursion.
Extract the owned or borrowed values from the cow to ensure progress is made in either case.

fix(http): avoid infinite recursion when Body::from is called with Cow::Owned.

---

src/uri.rs

Scheme check never true given preceding else if

refactor(uri): remove parsing condition

---

CONTRIBUTING.md

Fill the missing link in the CONTRIBUTING.md 
Closes no (known) open issue

<docs>: add link to easy issues

---

src/header/common/content_length.rs
src/header/common/pragma.rs
src/proto/response.rs

docs(headers): fix >-quote formatting

---

Cargo.toml
src/client/connect.rs
src/client/dns.rs

Fixes #1330
This got slightly more complex than I initially thought due to trying to make a future-proof API by:
- not exposing any `futures::sync::oneshot::*` types
- catering for the possibility of `HttpConnector` wanting to execute different types of blocking tasks
---

feat(client): allow custom executors for HttpConnector

---

.travis.yml
examples/client.rs
examples/hello.rs
examples/server.rs
src/client/mod.rs
src/proto/body.rs
src/proto/conn.rs
src/proto/dispatch.rs
src/proto/h1/parse.rs
src/proto/io.rs
src/proto/mod.rs
src/server/mod.rs
tests/client.rs
tests/server.rs

For now, this adds `client::Config::no_proto`, `server::Http::no_proto`,
and `server::Server::no_proto` to skip tokio-proto implementations, and
use an internal dispatch system instead.
`Http::no_proto` is similar to `Http::bind_connection`, but returns a
`Connection` that is a `Future` to drive HTTP with the provided service.
Any errors prior to parsing a request, and after delivering a response
(but before flush the response body) will be returned from this future.
See #1342 for more.
Test included that shows `no_proto` with the Client fixes #1353.

feat(lib): add support to disable tokio-proto internals

---

README.md

Use a docs.rs badge where appropriate. This is all subjective of course, I feel this is a bit nicer a way to present these links.

docs: a bit more intuitive docs links

---

README.md

Just using [shields](https://img.shields.io/badge/docs-master-green.svg) to make the docs badges more consistent.  Feel free to close this if you think it isn't an improvement.

docs(readme): make docs badges more consistent

---

src/client/connect.rs
src/client/dns.rs

This change allows us to skip going to the thread pool for dns lookup in cases where the host itself is already a valid ipv4 or ipv6 address.
This is useful for performance reasons, as well as to allow passing in a no-op executor in cases where it's known that only static IPs will be connected to.

feat(client): skip dns resolution when host is a valid ip addr

---

src/client/pool.rs
tests/client.rs

fix(client): don't leak connections with no keep-alive

---

src/proto/conn.rs
src/proto/dispatch.rs

This is important for TLS connections in particular
Closes #1380
I don't think this handles the client side properly.

Shut down the connection when done with it

---

src/proto/conn.rs
src/proto/dispatch.rs
src/server/mod.rs
tests/server.rs

feat(server): Allow keep alive to be turned off for a connection

---

examples/send_file.rs
examples/send_file_index.html

Here is an example of serving files in a separate thread. It should cover most cases where a separate thread is required, such as accessing a database.
There are actually two approaches illustrated here. One reads the whole file into memory, the other streams the file in chunks, but requires a second thread for the Response body. I don't like this two threaded approach, but haven't been able to figure out a way around it. Suggestions for a better approach would be appreciated.
I am working on an update to the guide pages to go with this example (which I will submit along with the Request body processing guide pages I'm working on.)

docs(server): Add an example of serving files

---

Cargo.toml
src/header/common/link.rs
src/header/common/mod.rs
src/header/common/pragma.rs
src/header/common/referrer_policy.rs
src/header/shared/charset.rs

Adds  `#[allow(unused_imports)]` to `AsciiExt` imports to fix tests. Updates `base64` to `0.9.0`.

Updates to 0.10.x

---

README.md

The 1.0 milestone has currently no issues but the 0.12 milestone has. So instead of adjusting the README.md for each upcoming mileston, i propose to just link to all milestones

"1.0 milestone" => "milestones"

---

src/client/cancel.rs
src/client/dispatch.rs
src/client/mod.rs
src/common/mod.rs
src/proto/h1/dispatch.rs

Uses a more reliable way of detecting that the connection has been closed, by keeping that knowledge in a separated close/cancel token, instead of relying on the mpsc channel knowing if either side is dropped, or that a `ClientMsg::Close` variant had been sent.
Closes #1433

fix(client): more reliably detect closed pooled connections

---

src/header/common/authorization.rs

I couldn't figure out why my "username:password" strings kept failing to parse
into a Basic auth header, until I realized that the implementation expects
it to be base-64 encoded, which would be the case if it was coming from HTTP.
I'm not sure if this is the best place to document it, but hopefully it will
make it more clear for other people / me when I forget.
Perhaps a better approach would be to document somewhere that all `FromStr` impls for
headers are there for parsing request headers, and not really for creating them.

docs(headers): document the fact that <Basic as FromStr>::from_str takes a base-64 encoded string

---

src/client/pool.rs

So when we hit the keep-alive timeout, we cannot open a new connection because we had a leftover item in the connecting map. This seems to fix the issue, but I'm not sure is this how kosher and did I break something else.

Drop the connecting item from pool when dropping an idle connection

---

examples/hello.rs
src/server/mod.rs

Fixes #1358 
This pull request introduces a new sleep_on_error configuration option. It is used to swallow IO errors when the Hyper server is accepting requests. That way developers do not have to worry about IO errors in case the server is under heavy load and runs out of available file descriptors. Better DoS protection.
* Is sleep_on_error a good name? I copied that from https://github.com/tailhook/tk-listen
* What should be the default value? Currently sleep_on_error is false for backwards compatibility and developers need to enable it. I would argue that Hyper should be secure by default and it should be set to true.

 fix(server): Sleep on socket IO errors 

---

Cargo.toml

Error:
```
error[E0277]: `tokio::reactor::Timeout` doesn't implement `std::fmt::Debug`
--> src/server/mod.rs:108:5
|
108 |     timeout: Option<Timeout>,
|     ^^^^^^^^^^^^^^^^^^^^^^^^ `tokio::reactor::Timeout` cannot be formatted using `:?` because it doesn't implement `std::fmt::Debug`
|
= help: the trait `std::fmt::Debug` is not implemented for `tokio::reactor::Timeout`
= note: required because of the requirements on the impl of `std::fmt::Debug` for `std::option::Option<tokio::reactor::Timeout>`
= note: required because of the requirements on the impl of `std::fmt::Debug` for `&std::option::Option<tokio::reactor::Timeout>`
= note: required for the cast to the object type `std::fmt::Debug`
error: aborting due to previous error
If you want more information on this error, try using "rustc …
```

fix(dependencies): Hyper does not compile with tokio-core < 0.1.11

---

src/proto/h1/conn.rs
src/proto/h1/encode.rs
src/proto/h1/role.rs
src/proto/mod.rs
src/server/conn.rs
src/server/mod.rs
tests/server.rs

In a similar vein as #1454, this adds needed support for servers to accept HTTP upgrade requests.
There isn't a specific API at the `hyper::Server` level, but can be done with `hyper::server:conn::Connection`.
Closes #1323

Server Protocol Upgrade support

---

src/proto/h1/role.rs

fix(server): prevent to output Transfer-encoding when server upgrade

---

Cargo.toml

Just a small patch, but my `with_executor` changes got merged into futures, so we can point to the main futures repo now instead.

fix(lib): move to futures master

---

benches/server.rs
examples/client.rs
examples/hello.rs
examples/send_file.rs
src/client/conn.rs
src/client/connect.rs
src/client/dispatch.rs
src/client/mod.rs
src/client/pool.rs
src/client/tests.rs
src/error.rs
src/proto/body.rs
src/proto/h1/conn.rs
src/proto/h1/dispatch.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h1/role.rs
src/proto/mod.rs
src/server/conn.rs
src/server/mod.rs
tests/client.rs
tests/server.rs

**The `Error` is now an opaque struct**, which allows for more variants to
be added freely, and the internal representation to change without being
breaking changes.
For inspecting an `Error`, there are several `is_*` methods to check for
certain classes of errors, such as `Error::is_parse()`. The `cause` can
also be inspected, like before. This likely seems like a downgrade, but
more inspection can be added as needed!
The `Error` now knows about more states, which gives much more context
around when a certain error occurs. This is also expressed in the
description and `fmt` messages.
**Most places where a user would provide an error to hyper can now pass
any error type** (`E: Into<Box<std::error::Error>>`). This error is passed
back in relevant places, and can be useful for logging. This …

feat(error): revamp `hyper::Error` type

---

src/client/connect.rs

Add configuration on `HttpConnector` to set `SO_NODELAY` on client
HTTP sockets.
Closes #1473

feat(client): add support to set SO_NODELAY on client HTTP sockets

---

benches/end_to_end.rs
benches/server.rs
examples/hello.rs
examples/multi_server.rs
examples/params.rs
examples/send_file.rs
examples/server.rs
examples/web_api.rs
src/error.rs
src/proto/h1/io.rs
src/server/conn.rs
src/server/mod.rs
src/server/tcp.rs
tests/integration.rs
tests/server.rs
tests/support/mod.rs

The `hyper::Server` is now a proper higher-level API for running HTTP
servers. There is a related `hyper::server::Builder` type, to construct
a `Server`. All other types (`Http`, `Serve`, etc) were moved into the
"lower-level" `hyper::server::conn` module.
The `Server` is a `Future` representing a listening HTTP server. Options
needed to build one are set on the `Builder`.
As `Server` is just a `Future`, it no longer owns a thread-blocking
executor, and can thus be run next to other servers, clients, or
what-have-you.
Closes #1322
Closes #1263
BREAKING CHANGE: The `Server` is no longer created from `Http::bind`,
nor is it `run`. It is a `Future` that must be polled by an
`Executor`.
The `hyper::server::Http` type has move to
`hyper::server::conn::Http`.

feat(server): re-design `Server` as higher-level API

---

README.md

Some links used HTTP. The badge image, specifically, caused an HTTPS warning on crates.io.
I also updated the website link from https://hyperium.github.io to https://hyper.rs

docs(README): Use HTTPS, update website link

---

.travis.yml
Cargo.toml
examples/client.rs
examples/hello.rs
examples/multi_server.rs
examples/params.rs
examples/send_file.rs
examples/server.rs
examples/web_api.rs
src/client/connect.rs
src/client/mod.rs
src/client/pool.rs
src/client/tests.rs
src/common/exec.rs
src/error.rs
src/lib.rs
src/mock.rs
src/rt.rs
src/server/conn.rs
src/server/mod.rs
src/server/tcp.rs

A Cargo feature `runtime` is added, which is enabled by default, that
includes the following:
- The `client::HttpConnector`, which uses `tokio::net::TcpStream`.
- The `server::AddrStream`, which uses `tokio::net::TcpListener`.
- The `hyper::rt` module, which includes useful utilities to work with
the runtime without needing to import `futures` or `tokio` explicity.
Disabling the feature removes many of these niceties, but allows people
to use hyper in environments that have an alternative runtime, without
needing to download an unused one.

feat(rt): make tokio runtime optional

---

src/client/conn.rs
src/client/mod.rs
src/proto/h1/conn.rs
src/proto/h1/role.rs
src/proto/mod.rs
tests/client.rs

This introduces support for the HTTP/1 Client to write header names as title case when encoding
the request.
Need to work on tests.
Closes #1492

feat(client): add support for title case header names at the socket level

---

src/client/connect.rs

Add `set_local_address` to the `HttpConnector`.
This configures the client to bind the socket to a local address of
the host before it connects to the destination. This is useful on
hosts which have multiple network interfaces, to ensure the request is
issued over a specific interface.
Includes an example to show how it is used and regression-check the API (copied from the existing client example). Please let me know if I should be adding any tests, and if so where.
Closes #1498

feat(client): support local bind for HttpConnector

---

examples/client.rs
src/client/conn.rs
src/proto/h1/dispatch.rs
src/server/conn.rs

The first commit fixes `cargo test` for me.
The second commit ~~backports~~ forwardports the fix to issue #1471 to master. Hopefully it was just forgotten and not omitted intentionally, because otherwise implementing server upgrades is more difficult.

Fix example & cherry-pick server::conn::Parts.service to master

---

src/server/conn.rs

fix(server): add upgrading process to poll_without_shutdown()

---

src/server/conn.rs

The provided method is a variant of `Connection::into_parts()`, which avoids a panic when the connection is using h2.

feat(server): add try_into_parts() to conn::Connection

---

src/server/conn.rs
src/server/mod.rs

A new configuration `http1_only` to `Builder` and `Connection` are added, which indicates that the upgrading to h2 does not perform when a parsing error occurs.
Fixes #1512.

feat(server): add http1_only configuration to conn::Connection

---

src/body/body.rs
src/error.rs
tests/client.rs

This allows a client to indicate that the request body should be cut off
in an abnormal fashion so the server doesn't simply get a "valid" but
truncated body.

Add Sender::abort

---

src/error.rs

cause2 is a bad name, but I couldn't think of anything obviously better
off the top of my head.

Add Error::cause2 and Error::into_error

---

src/body/body.rs
src/proto/h1/conn.rs
src/proto/h1/decode.rs
src/proto/h1/dispatch.rs
tests/client.rs

Fixes #1545.
I'm not sure about:
- what to do if the incoming body is longer than the content-length; is it ok to abort? I think Firefox does that
- the test (code and location)

Make Body know about incoming Content-Length

---

src/proto/h2/mod.rs
tests/integration.rs

Update `strip_connection_headers` function to strip connection headers
before sending.
Closes: #1551

Strip connection headers before sending

---

src/headers.rs
src/proto/h2/client.rs
src/proto/h2/server.rs
tests/integration.rs
tests/server.rs

feat(http2): set Content-Length on outgoing messages

---

src/proto/h2/mod.rs

This is implemented sligntly differently than what the TODO comment
said, but matches with tower-h2's implementation. h2 already handles the
buffering of the pending chunk and capacity management for it, so we
just want to make sure there's some capacity available (i.e. the
previous chunk has been fully written out).
Closes #1548

feat(h2): implement flow control for h2 bodies

---

Cargo.toml
examples/README.md
examples/upgrades.rs
src/body/body.rs
src/client/conn.rs
src/client/mod.rs
src/common/io/mod.rs
src/common/io/rewind.rs
src/common/mod.rs
src/error.rs
src/lib.rs
src/mock.rs
src/proto/h1/conn.rs
src/proto/h1/decode.rs
src/proto/h1/dispatch.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h1/role.rs
src/proto/h2/client.rs
src/proto/h2/server.rs
src/proto/mod.rs
src/server/conn.rs
src/server/mod.rs
src/upgrade.rs
tests/client.rs
tests/server.rs

This proposes a way to offer an easier way to manage HTTP upgrades than using the lower-level `client::conn` and `server::conn` APIs. This includes both `Upgrade` + `101 Switching Protocols`, and `CONNECT` tunneling.
It makes use of the `Body` type that is returned by hyper. When the HTTP1 state machine notices an attempt to trigger an upgrade in either the client or the server, the returned `Body` will have some additional state to allow getting a `Future` of an eventual upgrade: `Body::on_upgrade(self) -> impl Future`.
This `on_upgrade` future, if successful, will return a new `hyper::upgrade::Upgraded` type that fully owns the original IO transport, after the upgrade. The `Upgraded` can itself be used as an `AsyncRead`/`AsyncWrite` for convenience (and automatically including any …

Add higher-level HTTP upgrade support to Client and Server

---

src/body/body.rs
src/proto/h2/client.rs
src/proto/h2/server.rs
tests/server.rs

Update `Body::content_length` to return the content length of when `Body::Kind` is `H2`, instead of returning `None`. `Kind::H2` also holds the value of the `content-length` header as well as the `h2::RecvStream`.
Closes: #1546

Get content-length for Incoming HTTP2 Bodies

---

Cargo.toml
src/client/mod.rs
src/error.rs
tests/client.rs

While the upgrades feature enabled HTTP upgrades in both and the server and client, and the goal was for `CONNECT` requests to work as well, only the server could use them for `CONNECT`. The `Client` had some specific code rejecting `CONNECT` requests, and this removes it and prepares the `Client` to handle them correctly.

feat(client): enable CONNECT requests through the `Client`

---

src/client/mod.rs
src/client/pool.rs
src/client/tests.rs
src/common/lazy.rs
src/common/mod.rs
src/mock.rs

If a checkout wins, meaning an idle connection became available before
a connect future completed, instead of just dropping the connect future,
it spawns it into the background executor to allow being placed into
the pool on completion.
Alternative solution for #1584

fix(client): try to reuse connections when pool checkout wins

---

.travis.yml
src/client/connect.rs
src/client/dns.rs

First PR, criticism welcome!
Update client connector to attempt a parallel connection using alternative address family, if connection using preferred address family takes too long.
Some questions:
* What should be a default value for timeout before we attempt other connections? Currently is 300ms.
* How to write a test for this? For manual testing I used edited /etc/hosts and iptables to simulate non-functioning IPv6. Maybe same could be done for Travis? Unsure about Appveyor.
Closes: #1316

feat(client): implement rfc 6555 (happy eyeballs)

---

src/client/tests.rs
src/proto/h1/conn.rs
tests/integration.rs
tests/support/mod.rs

If a user makes use of `Body::is_end_stream` to optimize so as to not
need to do make a final poll just to receive `None`, previously the
connection would not have progressed its reading state to a finished
body, and so the connection would be closed.
Now, upon reading any chunk, the connection state will check if it
can know that the body would be finished, and progresses to a body
finished state sooner.
The integration tests were amplified by adding a naive hyper proxy
as a secondary test, which happens to make use of that optimization,
and thus caught the issue.

fix(http1): reduce closed connections when body is dropped

---

src/body/chunk.rs
src/proto/h1/io.rs
src/proto/h1/role.rs

These were trivially safe, but it's still a good idea to avoid `unsafe` here, even if just for PR purposes.

refactor(lib): replace Vec::set_len(0) with clear

---

src/server/mod.rs
src/server/tcp.rs

Heya :wave:, this implements https://github.com/hyperium/hyper/issues/1602. I'm pretty sure there's a few rough edges to this PR, but I wanted to kick things off anyway.
The result type for `from_tcp()` is now:
```rust
Result<Builder<tokio_tcp::Incoming>, Box<dyn error::Error>> {
```
I wasn't sure what the best way to approach the errors was; any pointers here would be fantastic!
I wasn't sure what the runtime features are for (`no_std` related perhaps?), but figured I'd follow the prior art and add them where it seemed appropriate.
Rustfmt tends to run on every save; sorry if it changed things it shouldn't have. Happy to go back in and revert changes - but also happy to leave it if it doesn't matter :grin:
I ended up going with `.from_tcp()` because I felt it was the most descriptive, …

add Server::from_tcp()

---

src/lib.rs

This PR intends to fix the error at `cargo doc` caused by warnings.

chore(*): enable `#[deny(warnings)]` at only testing

---

src/proto/h1/conn.rs
tests/server.rs

Change behaviour of connection or server response when the request is
version 1.0 and the Connection: keep-alive header is not present.
1. If the response is also version 1.0, then connection is closed if the
server keep-alive header is not present.
2. If the response is version 1.1, then the keep-alive header is added
when downgrading to version 1.0.
CLOSES: #1614

fix(server): add fix for keep-alive connection on http version 1.0

---

src/common/drain.rs
src/common/mod.rs
src/server/conn.rs
src/server/mod.rs
src/server/shutdown.rs

This adds a simple graceful shutdown ability to the server. It's a "combinator" on `hyper::Server`, and takes a generic user-supplied future to "select" on. Notably, if people aren't using this, they aren't paying the book-keeping cost at all.
- If the server incoming stream finishes (like `TcpListener::incoming()`, or any other), what should happen? Should that be another way that starts the graceful shutdown? Or is that more a sign of something more urgent happening?
- Answer: this will just return immediately. This normally only happen if users did something like `incoming.take(x)`. To prevent that from closing up abruptly, you could chain, like `incoming.take(x).chain(stream::empty())`.
- If there is an error trying to accept a connection (or spawning the HTTP connection task), …

Server Graceful Shutdown

---

src/proto/h2/client.rs
src/proto/h2/mod.rs
src/proto/h2/server.rs
tests/integration.rs

The HTTP/2 spec allows TE headers in requests if the value is
"trailers". Other TE headers are still stripped.
Closes #1642

fix(http2): allow TE "trailers" request headers

---

src/proto/h1/role.rs

rustc issue: https://github.com/rust-lang/rust/issues/55105
Steps to reproduce:
```
rustup target add armv7-linux-androideabi
RUSTFLAGS="-Ctarget-feature=+neon" cargo build --target armv7-linux-androideabi --release
```
Output without this change:
```
Compiling hyper v0.12.11 (/home/simon/projects/servo-deps/hyper)
LLVM ERROR: ran out of registers during register allocation
error: Could not compile `hyper`.
```

Split record_header_indices loop to work around rustc/LLVM bug, on relevant targets

---

Cargo.toml
examples/README.md
examples/single_threaded.rs
src/common/drain.rs
src/common/exec.rs
src/common/mod.rs
src/proto/h2/mod.rs
src/proto/h2/server.rs
src/server/conn.rs
src/server/mod.rs
src/server/shutdown.rs

Until this commit, servers have required that `Service` and their
`Future` to be `Send`, since the server needs to spawn some internal
tasks to an executor, and by default, that is `tokio::spawn`, which
could be spawning to a threadpool. This was true even if the user were
certain there was no threadpool involved, and was instead using a
different single-threaded runtime, like
`tokio::runtime::current_thread`.
This changes makes all the server pieces generic over an `E`, which is
essentially `Executor<PrivateTypes<Server::Future>>`. There's a new set
of internal traits, `H2Exec` and `NewSvcExec`, which allow for the type
signature to only show the generics that the user is providing. The
traits cannot be implemented explicitly, but there are blanket
implementations for `E: …

feat(server): allow `!Send` Servers

---

examples/hello.rs
src/client/connect/http.rs
src/client/connect/mod.rs
src/client/mod.rs
tests/client.rs

- Adds `client::connect::Connected::extra()`, which allows connectors to
specify arbitrary custom information about a connected transport.
If a connector provides this extra value, it will be set in the
`Response` extensions.
Closes #1402
-----
This is an alternative to #1592

feat(client): adds `HttpInfo` to responses when `HttpConnector` is used

---

src/client/connect/dns.rs
src/client/connect/http.rs
src/client/connect/mod.rs
tests/client.rs

This introduces a `Resolve` trait to describe asynchronous DNS
resolution. The `HttpConnector` can be configured with a resolver,
allowing a user to still use all the functionality of the
`HttpConnector`, while customizing the DNS resolution.
To prevent a breaking change, the `HttpConnector` has its `Resolve`
generic set by default to `GaiResolver`. This is same as the existing
resolver, which uses `getaddrinfo` inside a thread pool.
Closes #1517

feat(client): add `Resolve`, used by `HttpConnector`

---

Cargo.toml
src/client/connect/dns.rs
src/lib.rs

Unlike the default resolver, this avoids spawning extra dedicated
threads but only works on the multi-threaded Tokio runtime.
Closes #1676

feat(dns): tokio_threadpool::blocking resolver

---

src/buffer.rs
src/server/mod.rs

Happy to expand on details if necessary.

force close stream if keep-alive disabled. don't allocate when taking a buffer.

---

src/client/conn.rs
src/client/connect/mod.rs
src/client/mod.rs
src/client/pool.rs
src/client/tests.rs
src/mock.rs
tests/client.rs

- Adds `Connected::negotiated_h2()` method to signal the connection must
use HTTP2. `Connect` implementations should set this if using ALPN.
If a connection to a host is detected to have been upgraded via ALPN,
any other oustanding connect futures will be canceled, and the waiting
requests will make use of the single HTTP2 connection.
The `http2_only` builder configuration still works the same, not
requiring ALPN at all, and always using only a single connection.
Closes #1485 
cc @sfackler @pimeys

feat(client): add ALPN h2 support for client connectors

---

examples/hello.rs
src/server/conn.rs
src/server/mod.rs
src/server/shutdown.rs
src/server/tcp.rs
src/service/make_service.rs
src/service/mod.rs
src/service/new_service.rs

This adjusts the way `Service`s are created for a `hyper::Server`. The
`MakeService` trait allows receiving an argument when creating a
`Service`. The implementation for `hyper::Server` expects to pass a
reference to the accepted transport (so, `&Incoming::Item`). The user
can inspect the transport before making a `Service`.
In practice, this allows for things like getting the remote socket
address, or the TLS certification, or similar.
To prevent a breaking change, there is a blanket implementation of
`MakeService` for any `NewService`. Besides implementing `MakeService`
directly, there is also added `hyper::service::make_service_fn`.
Closes #1650

Change `NewService` to `MakeService` with connection context

---

src/client/connect/http.rs
src/client/connect/mod.rs
src/client/mod.rs

`client` module
* Change port to port_part
* Keep tests as is and make test work 
The port function is deprecated so the function is port_part now. 
Keep same behavior using new function.

fix(client): fix deprecated errors on port from http

---

src/proto/h1/conn.rs
src/server/conn.rs
src/server/mod.rs
tests/server.rs

This option determines whether a read EOF should close the connection
automatically. The behavior was to always allow read EOF while waiting
to respond, so this option has a default of `true`.
Setting this option to `false` will allow Service futures to be canceled
as soon as disconnect is noticed.
Closes #1716
cc @luben

feat(server): add `http1_half_close(bool)` option

---

benches/end_to_end.rs
src/proto/h1/io.rs

The default read strategy for HTTP/1 connections is now adaptive. It
increases or decreases the size of the read buffer depending on the
number of bytes that are received in a `read` call. If a transport
continuously fills the read buffer, it will continue to grow (up to the
`max_buf_size`), allowing for reading faster. If the transport
consistently only fills a portion of the read buffer, it will be shrunk.
This doesn't provide much benefit to small requests/responses, but
benchmarks show it to be a noticeable improvement to throughput when
streaming larger bodies.
Closes #1708

perf(http1): implement an adaptive read buffer strategy

---

src/server/conn.rs
src/server/mod.rs
src/server/shutdown.rs
src/service/make_service.rs
src/service/mod.rs

It's sealed, and has a blanket implementation, and so should only be
used as bounds. Even still, its hidden from the docs.
Closes #1727 
cc @vorner

feat(service): export `hyper::service::MakeServiceRef`

---

README.md

Many people will find `hyper` when searching for a Rust HTTP crate. Reqwest is not nearly so easy to find unless you know what you are looking for, but is what a lot of people looking for a rust http library need. Let's point them in the right direction.
I recently came across a new Rust user on Reddit who had found the hyper crate, but was trying to use libcurl bindings to make http requests because they hadn't managed to find reqwest.

Mention / link to reqwest in README

---

src/client/connect/dns.rs

When building a caching resolver it would be useful to be able to have `HashMap<Name, Vec<IpAddr>>` and similar. This is currently not possible because `Name` does not implement `Eq` or `Hash`. Here I add this and a few other standard traits that felt appropriate.

Add useful trait impls to Name

---

src/client/connect/mod.rs

This change adds a constructor field for `Destination` this allows the `Connect` trait implementors like `HttpConnector` to be used with the lower level `hyper::client::conn::*`. This was mostly needed for the first pass at the `tower-hyper` implementation and to allow it to use `HttpConnector` and other `Connect` impls as a way to build `tower_hyper::client::Connection`'s.
library for ref usage: https://github.com/LucioFranco/tower-hyper

Add `Destination::try_from_uri` to allow external clients to use `Connect`

---

src/client/conn.rs
src/client/mod.rs

This allows users to configure a limit to client connections' read and
write buffers.
Closes #1748

feat(client): add `conn::Builder::max_buf_size()`

---

Cargo.toml
src/proto/h2/client.rs
tests/integration.rs

This reverts commit 7b7dcc8f68227b1c2dac5dcab4a68348ebe70ca1.

fix(http2): revert http2 refactor causing a client hang

---

src/server/tcp.rs

It consumes the `AddrStream` and returns the underlying TcpStream.

Add `into_inner` to `AddrStream`

---

src/server/mod.rs

Similarly to client::Builder::http1_max_buf_size
I am not sure for the name, should it be `http1_max_buf_size` or it applies to both h1 and h2?

Add max_buf_size setting in the server::Builder

---

src/service/make_service.rs
src/service/service.rs

`FnMut` is a super trait of `Fn`, so these bounds changes should not be breaking.
cc @sfackler I believe you'd asked about this before.

feat(service): allow `FnMut` with `service_fn`

---

src/proto/h1/dispatch.rs
src/proto/h2/server.rs
src/server/conn.rs
src/service/make_service.rs
src/service/new_service.rs
src/service/service.rs

This PR adds the method `poll_ready` to `Service` and `MakeService`, which provides the ability to these services for notifying the readiness whether to accept connections or requests.
These methods corresponds to `tower_service::Service::poll_ready` and prevents to ignore calling this method when using tower's services in `hyper::Server` or `hyper::server::conn::Connection`.
The added methods have the default implementation and has no effect on existing code that implements `Service`/`MakeService` directly.

fix(server): add `poll_ready` to `Service` and `MakeService`

---

Cargo.toml
build.rs
src/error.rs

Implement Error::source when available

---

src/proto/h2/server.rs
src/server/conn.rs
src/server/mod.rs

feat(server): add `http2_max_concurrent_streams` builder option

---

src/client/conn.rs
src/client/mod.rs
src/proto/h2/client.rs
src/server/conn.rs
src/server/mod.rs

Add `fn http2_initial_stream_window_size` and `fn
http2_initial_connection_window_size` for client and server.
Closes #1771 
Signed-off-by: Kevin Leimkuhler <kevinl@buoyant.io>

feat(client, server): set stream/conn. window size

---

src/proto/h1/role.rs

fix(server): prohibit the length headers on successful CONNECT

---

src/error.rs
src/proto/h2/mod.rs
src/proto/h2/server.rs
tests/server.rs

feat(http2): check `Error::source()` for an HTTP2 error code to send in reset

---

examples/web_api.rs

The previous version only showed a JSON GET API.
Deserializing the body of a POST request is not
trivial so the example should show it.
The new example takes the JSON body sent in a
POST request, deserializes it, adds a field, then
serializes it and sends it back.

docs(server): show JSON deserialization in API example

---

src/client/pool.rs

I observed that in a few cases, hyper client cannot reuse h1 connections. After some log analysis, I think this is because [`PoolInner::put`](https://github.com/hyperium/hyper/blob/c0e08a41ccf18d82d2a90266a812261c3e52a202/src/client/pool.rs#L590) may happen between [`Pool::take`](https://github.com/hyperium/hyper/blob/c0e08a41ccf18d82d2a90266a812261c3e52a202/src/client/pool.rs#L203) and [`Pool::waiter`](https://github.com/hyperium/hyper/blob/c0e08a41ccf18d82d2a90266a812261c3e52a202/src/client/pool.rs#L309).
I believe merging these two operations will help.

Fix few case can't reuse connection

---

CHANGELOG.md
Cargo.toml
src/http/h1.rs

Not sure if you still care about 0.10.x at all, but because the Iron framework uses it, and we have an app still using Iron, I've fixed a bug that was causing data truncation on slow connections.
If socket writes ever failed (e.g. with ErrorKind::WouldBlock), HttpWriter::SizedWriter would still record those bytes as sent, which would result in a truncated write. Reordering those lines as per my commit allows higher layers to properly retry writing.

Fix error-handling state bug in SizedWriter

---

src/client/conn.rs
src/client/dispatch.rs
src/client/mod.rs
src/client/pool.rs
src/client/tests.rs
src/error.rs
src/proto/h1/conn.rs
src/proto/h1/dispatch.rs
src/proto/h1/mod.rs
src/proto/h1/role.rs
src/proto/h2/client.rs
src/proto/h2/mod.rs
src/server/conn.rs
src/upgrade.rs
tests/client.rs

- Placed all cases of "unexpected bytes" errors into the
`UnexpectedMessage` variant.
- Placed all cases of "unexpected EOF" errors into the
`IncompleteMessage` variant. Description is now generic about
"connection closed before message completed", instead of mentioning
"request" or "response.
- Added `Error::is_incomplete_message()` accessor to help checking for
unexpected closures.
- Renamed some variants to be clearer when viewing the `Debug` format.
- Collected all "user" errors into an internal `User` enum, to prevent
forgetting to update the `is_user()` method.

refactor(error): improve organization of `Error` kinds

---

src/proto/h1/role.rs
tests/server.rs

fix(server): skip automatic Content-Length header for HTTP 304 responses

---

build.rs
src/client/connect/mod.rs

Add TryFrom<Uri> impl for Destination, for compiler version >= 1.34.
Add basic unit tests for TryFrom impl
Ref Issue: Implement TryFrom for Destination #1808

feat(client): Implement TryFrom for Destination

---

.travis.yml
examples/echo.rs
examples/params.rs
examples/send_file.rs
examples/web_api.rs
src/body/body.rs
src/body/payload.rs
src/client/conn.rs
src/client/connect/dns.rs
src/client/connect/mod.rs
src/client/mod.rs
src/common/exec.rs
src/error.rs
src/mock.rs
src/proto/h1/decode.rs
src/proto/h1/dispatch.rs
src/proto/h1/role.rs
src/proto/h2/server.rs
src/server/conn.rs
src/server/mod.rs
src/server/shutdown.rs
src/service/make_service.rs
src/service/new_service.rs
src/service/service.rs
src/upgrade.rs
tests/client.rs
tests/server.rs
tests/support/mod.rs

chore(lib): add `dyn` keyword to trait objects

---

src/common/mod.rs
src/common/task.rs
src/proto/h1/dispatch.rs

Adds a `YieldNow` helper, since I believe there may be a couple other places that could make use of this, like the accept loop in `SpawnAll`.
Closes #1828 
cc @ry

fix(http1): force always-ready connections to yield after a few spins

---

src/client/connect/http.rs

Signed-off-by: Dietmar Maurer <dietmar@proxmox.com>

style(client) `HttpConnector`: use consistent naming - s/buf/buffer/

---

examples/hello.rs

Something like this?
There is a call on `make_service_fn` and `service_fn`. Is it possible to make it even simpler?

Update the example hello

---

examples/client.rs
src/client/connect/dns.rs
src/client/connect/http.rs

The first part of #1853, at least, which moves the blocking `getaddrinfo` call off the main executor and into a tokio-threadpool.

Use a tokio-threadpool for the GaiResolver

---

examples/echo.rs

I tried to update this as well but not sure how to deal with that `req.into_body().map(....`
Perhaps you have some example to how me how to update this example?

Update example echo - ready to merge

---

src/body/body.rs
src/client/conn.rs
src/client/connect/http.rs
src/client/mod.rs
src/server/conn.rs
src/server/mod.rs
src/service/make_service.rs
src/service/service.rs

Fix and update doc tests to async/await.
Reference https://github.com/hyperium/hyper/issues/1850
This PR combines two closed PRs #1867 and #1866.
* Remove unnecessary `extern crate`.
* Remove unnecessary imports such as `futures::Future`, `hyper::rt::Future`. 
* Use `futures_util` instead of using `futures` crate directly.
* Use `async fn` and `await` syntax instead of `futures` operators.
* Use `async move` block to return a `Future`.
* Use `tokio::sync::oneshot` instead of the one from `futures` crate.
* Use `hyper:rt::main` (reexport of `tokio::main` macro) to wrap main function.

Update doc tests to async/await

---

Cargo.toml
benches/pipeline.rs
benches/server.rs

Ref #1848 (benchmark)
Update two benchmark test suites to async/await compatible version
- `benches/server.rs`
- `benches/pipeline.rs`
**This PR**
```
test raw_tcp_throughput_large_payload   ... bench:     279,058 ns/iter (+/- 46,907) = 3584 MB/s
test raw_tcp_throughput_small_payload   ... bench:      17,689 ns/iter (+/- 1,665) = 9 MB/s
test throughput_chunked_large_payload   ... bench:     290,225 ns/iter (+/- 11,122) = 3446 MB/s
test throughput_chunked_many_chunks     ... bench:     782,491 ns/iter (+/- 144,581) = 1287 MB/s
test throughput_chunked_small_payload   ... bench:      25,768 ns/iter (+/- 11,800) = 6 MB/s
test throughput_fixedsize_large_payload ... bench:     291,120 ns/iter (+/- 39,375) = 3435 MB/s
test throughput_fixedsize_many_chunks   ... bench:     535,915 ns/iter (+/- …
```

Update benchmark suites to async/await compatible version

---

benches/end_to_end.rs
benches/server.rs

Ref #1848 
Update `end_to_end` benchmark to async/await version
❌ 
**No.** 
All benchmarks related to `h2` client did not pass. Need an update of `h2` client implementation.
This pull request
```bash
running 11 tests
test http1_body_both_100kb       ... bench:      69,467 ns/iter (+/- 8,586) = 2948 MB/s
test http1_body_both_10mb        ... bench:   5,035,217 ns/iter (+/- 939,403) = 4164 MB/s
test http1_get                   ... bench:      38,466 ns/iter (+/- 5,911)
test http1_parallel_x10_empty    ... bench:     241,262 ns/iter (+/- 50,905)
test http1_parallel_x10_req_10mb ... bench:  33,437,364 ns/iter (+/- 2,445,027) = 313 MB/s
test http1_post                  ... bench:      39,928 ns/iter (+/- 7,916)
test http2_get                   ... FAILED
test http2_parallel_x10_empty    ... …
```

[Blocked] Update end_to_end benchmark to async/await

---

examples/send_file.rs
src/common/drain.rs
src/server/tcp.rs

This fixes building with the tokio master branch head.
Refactoring will be required to actually use the new `accept` async fn.
Build was broken by: https://github.com/tokio-rs/tokio/commit/6d8cc4e4755abbd0baac9abf154837b9be011a07

fix(server): worked-around deprecation of `poll_accept` method in tokio

---

src/client/connect/mod.rs

fix(client): impl<T: Connect> Connect for Box<T>

---

Cargo.toml
src/client/connect/dns.rs
src/client/connect/http.rs
src/server/conn.rs
src/server/mod.rs
src/server/tcp.rs
tests/client.rs
tests_disabled/server.rs

This is only upgrade.
`tokio-reactor` and `tokio-tcp` is merged into `tokio-net`
`tokio-threadpool` became part of `tokio-executor`

Upgrade tokio

---

Cargo.toml
benches/end_to_end.rs
src/body/body.rs
src/client/conn.rs
src/client/mod.rs
src/proto/h2/client.rs
src/proto/h2/mod.rs
src/proto/h2/server.rs
src/server/conn.rs
src/server/mod.rs
src/server/shutdown.rs

Re-enables HTTP2 client and server support.
Closes #1851

Re-enable HTTP2 support

---

benches/end_to_end.rs
benches/pipeline.rs
benches/server.rs
examples/client.rs
examples/client_json.rs
examples/echo.rs
examples/hello.rs
examples/multi_server.rs
examples/params.rs
examples/proxy.rs
examples/send_file.rs
examples/single_threaded.rs
examples/state.rs
examples/tower_server.rs
examples/upgrades.rs
examples/web_api.rs
src/client/conn.rs
src/client/connect/http.rs
src/client/mod.rs
src/lib.rs
src/server/conn.rs
src/server/mod.rs
src/service/make_service.rs
src/service/service.rs
tests/client.rs
tests/server.rs

`async_await` is stabilized in https://github.com/rust-lang/rust/pull/63209.
This commit fixes `hyper` build with latest nightly compiler.

refactor: remove async_await feature gate

---

Cargo.toml
src/body/body.rs
src/body/payload.rs
src/proto/h1/dispatch.rs
src/proto/h2/client.rs
src/proto/h2/mod.rs
src/proto/h2/server.rs
tests/client.rs
tests/server.rs

This changes Payload to be a trait alias of http_body::Body and seals Payload so that the only way to implement it is via http_body::Body. `content_length` was also removed in favor of the more flexible size hint api in http body.
If we're all happy with this I can cut a release of http body and push the cargo.toml change.
cc @seanmonstar @carllerche 
Signed-off-by: Lucio Franco <luciofranco14@gmail.com>

Update `Payload` to be a trait alias of `http_body::Body`

---

src/client/connect/dns.rs

Since master is using the latest futures, I'm pretty sure we're safe to assume rustc > 1.30

refactor(dns) migrate deprecated trim_{left,right} -> trim_{start,end}

---

Cargo.toml
benches/end_to_end.rs
src/client/connect/dns.rs
src/client/connect/http.rs
src/client/mod.rs
tests/client.rs
tests/support/mod.rs

BREAKING CHANGE: Calls to `GaiResolver::new` and `HttpConnector::new` no
longer should pass an integer argument for the number of threads.

feat(client): change `GaiResolver` to use a global blocking threadpool

---

Cargo.toml
examples/tower_client.rs
src/client/conn.rs
src/client/connect/http.rs
src/client/mod.rs
src/client/service.rs

Still WIP, need to get crates out for MakeService and MakeConnection.
This mainly introduces the most minimal change to support tower based clients.
cc @seanmonstar

Initial push to add tower based clients

---

src/body/body.rs
src/proto/h1/dispatch.rs
tests/client.rs
tests/server.rs

The previous version is renamed to `try_send_data`.
BREAKING CHANGE: Usage of `send_data` should either be changed to
async/await or use `try_send_data`.

feat(body): change `Sender::send_data` to an `async fn`.

---

src/common/drain.rs
src/server/tcp.rs

introduced by #1890 while `Pin::new_unchecked` is used across this project which is more efficient

Remove `FutureExt::boxed` to unify project style

---

Cargo.toml
src/common/drain.rs
src/proto/h2/server.rs
src/server/conn.rs
src/server/mod.rs
src/server/shutdown.rs

Remove all pin-related `unsafe` code from Hyper, as well as the
now-unused 'pin-utils' dependency.

refactor(lib): Use pin-project crate to perform pin projections

---

src/proto/h1/role.rs
tests/client.rs

fix(client): allow client GET requests with explicit body headers

---

Cargo.toml
src/server/accept.rs
src/server/conn.rs
src/server/mod.rs
src/server/shutdown.rs
src/server/tcp.rs
tests/support/mod.rs

The `Accept` trait is used by the server types to asynchronously accept
incoming connections. This replaces the previous usage of `Stream`.
Part of #1920
BREAKING CHANGE: Passing a `Stream` to `Server::builder` or
`Http::serve_incoming` must be changed to pass an `Accept` instead. The
`stream` optional feature can be enabled, and the a stream can be
converted using `hyper::server::accept::from_stream`.

feat(server): introduce `Accept` trait

---

Cargo.toml
src/body/body.rs
src/lib.rs
src/server/tcp.rs

Part of #1920 
BREAKING CHANGE: Using a `Body` as a `Stream`, and constructing one via
`Body::wrap_stream`, require enabling the unstable `stream` feature.

feat(body): put `Stream` impl for `Body` behind `stream` feature

---

examples/send_file.rs

The lifetime workaround is no longer required due to changes in
rustc. This removes the line and comment from the example.
Tested on `rustc 1.39.0-nightly (34e82a7b7 2019-09-10)`

refactor(examples): remove lifetime workaround in send_file example

---

Cargo.toml

`pin-project` now [interoperates correctly with `#[cfg()]`](https://github.com/taiki-e/pin-project/pull/77).

chore(dependencies): update pin-project to 0.4.0-alpha.10

---

src/body/body.rs
src/error.rs

(cherry picked from commit bb365f689defcf529bf546eb684177dbe801b0ba)

(0.12.x) feat(body): identify aborted body write errors

---

Cargo.toml
src/client/connect/http.rs
src/server/tcp.rs
tests/client.rs
tests/server.rs

chore(dependencies): update tokio, h2, and tower-make

---

Cargo.toml
src/client/connect/dns.rs
src/client/connect/http.rs
src/client/connect/mod.rs
src/client/mod.rs
src/common/exec.rs
src/error.rs
src/lib.rs
src/server/conn.rs
src/server/mod.rs

The `HttpConnector` and `AddrListener` types which make use of
`tokio::tcp` have been made their own optional feature. This allows
using them without requiring the *full* tokio runtime.

feat(lib): add optional `tcp` feature, split from `runtime`

---

CHANGELOG.md

change stream to unstable-stream
closes: #1966

docs(version): fix typo

---

Cargo.toml

`bytes` is bumped due to the addition of `Bytes::advance` in 0.4.6. `h2`
0.1.13 introduced the `.is_io()` and `into_io()` methods.
Bumping `tokio-threadpool` to 0.1.16 removes a dependency on `rand` from
the crate which reduces the size and avoids minimum version dependency
issues in that dependency tree.
---
Trying to make `-Z minimum-versions` work on some of my crates. Will bump `bytes` on `master` as well since I suspect it is necessary there too.

cargo: bump minimum versions

---

Cargo.toml

`Bytes::advance` was introduced in this version.
---
`master`-oriented version of #1974. Probably not the end of the story here; `tokio` needs a similar sweep for the versions required on `master`.

fix(cargo): require bytes 0.4.6

---

src/client/connect/dns.rs
src/client/connect/http.rs

This takes the same strategy as golang, where the timeout value is
divided equally between the candidate socket addresses.
If happy eyeballs is enabled, the division takes place "below" the
IPv4/IPv6 partitioning.

feat(client): Add connect timeout to HttpConnector

---

src/service/mod.rs

This function has been otherwise removed and the link was broken.

docs(service): remove reference to service_fn_ok

---

src/proto/h1/conn.rs
src/proto/h1/dispatch.rs
src/server/conn.rs
src/server/mod.rs
tests/server.rs

Detecting a read hangup is a useful way to determine that a connection
has closed. It's also possible that a client shuts down its read half
without closing the connection, but this is rarer. Thus, by default,
hyper will now assume a read EOF means the connection has closed.
BREAKING CHANGE: The server's behavior will now by default close
connections when receiving a read EOF. To allow for clients to close
the read half, call `http1_half_close(true)` when configuring a
server.
Closes #1764

feat(server): change `http1_half_close` option default to disabled

---

src/proto/h1/conn.rs
tests/server.rs

fix(server): ignore expect-continue with no body in debug mode

---

src/client/connect/dns.rs
src/client/connect/http.rs

feat(client): Add connect timeout to HttpConnector (0.12 backport)

---

src/client/connect/http.rs
src/client/connect/mod.rs
src/client/mod.rs
src/service/mod.rs
src/service/oneshot.rs
tests/client.rs

The `Connect` trait is now essentially an alias for
`Service<Destination>`, with a blanket implementation as such, and is
sealed.
Closes #1902
BREAKING CHANGE: Any manual implementations of `Connect` must instead
implement `tower::Service<Destination>`.

feat(client): change `Connect` trait into an alias for `Service`

---

examples/single_threaded.rs
src/server/mod.rs

add generic for the executor to server impl block
resolves https://github.com/hyperium/hyper/issues/1988

fix(server): local_addr() with executor (0.12)

---

src/client/connect/http.rs

The recently-added connect timeout does not cover resolving hostnames, which could also stall on an OS-level timeout if there are issues reaching the DNS server.
As discussed in #1987, this wasn't needed for master due to `Resolve` becoming a `Service` but it's still useful for 0.12.

feat(client): add resolve timeout to HttpConnector (to 0.12)

---

src/client/connect/dns.rs
src/client/connect/http.rs
tests/client.rs

Closes #1903
BREAKING CHANGE: The `Resolve` trait is gone. All custom resolves should
implement `tower::Service` instead.
The error type of `HttpConnector` has been changed away from
`std::io::Error`.

feat(client): change `Resolve` to be `Service<Name>`

---

src/client/connect/dns.rs
src/client/connect/http.rs

It is not possible to connect to an IPv4 address from an IPv6 address or vice-versa so don't waste time trying. If no remote addresses match then a "missing connect error" will now occur.

feat(client): filter remote IP addresses by family of given local IP address

---

Cargo.toml
examples/single_threaded.rs
src/rt.rs

The `hyper::rt::Executor` trait allows defining custom executors to be
used with hyper's `Client` and `Server`.
Closes #1944
BREAKING CHANGE: Any type passed to the `executor` builder methods must
now implement `hyper::rt::Executor`.
`hyper::rt::spawn` usage should be replaced with `tokio::task::spawn`.
`hyper::rt::run` usage should be replaced with `#[tokio::main]` or
managing a `tokio::runtime::Runtime` manually.

feat(rt): introduce `rt::Executor` trait

---

src/body/mod.rs

The `hyper::body::HttpBody` trait is a re-export from the `http-body`
crate. This allows libraries to accept "HTTP bodies" without needing to
depend on hyper.
BREAKING CHANGE: All usage of `hyper::body::Payload` should be replaced
with `hyper::body::HttpBody`.

feat(body): replace the `Payload` trait with `HttpBody`

---

Cargo.toml

This unblocks some work that I'm doing in `tracing` where I'm updating `tracing-tower` to the versions that use `std::future::Future`.

chore(dependencies): update tower-service to 0.3

---

benches/connect.rs
examples/client.rs
src/client/connect/dns.rs
src/client/connect/http.rs
src/client/connect/mod.rs
src/client/mod.rs
tests/client.rs
tests/server.rs

This changes "connectors" to be called with a `Uri` instead of `Destination`. The `Destination` type wasn't providing anything extra over an `http::Uri`.

feat(client): remove `Destination` for `http::Uri` in connectors

---

.travis.yml
Cargo.toml
src/body/body.rs
src/lib.rs
src/server/accept.rs
tests/server.rs

Rename `unstable-stream` feature to `stream` and enable by default

---

.github/workflows/CI.yml

I added `fail-fast: false` because i've seen random failures on windows and macOS for tests.
- `client::pool::tests::test_pool_timer_removes_expired`
- `client::connect::http::tests::client_happy_eyeballs`

GitHub Actions: Name steps and use matrix.include for features etc.

---

Cargo.toml
benches/body.rs
examples/client.rs
examples/client_json.rs
examples/echo.rs
examples/params.rs
examples/web_api.rs
src/body/aggregate.rs
src/body/mod.rs
src/body/to_bytes.rs
src/common/buf.rs
src/common/mod.rs
src/proto/h1/io.rs
tests/client.rs
tests/support/mod.rs

Adds utility functions to `hyper::body` to help asynchronously
collecting all the buffers of some `HttpBody` into one.
- `aggregate` will collect all into an `impl Buf` without copying the
contents. This is ideal if you don't need a contiguous buffer.
- `to_bytes` will copy all the data into a single contiguous `Bytes`
buffer.

feat(body): add `body::aggregate` and `body::to_bytes` functions

---

.github/workflows/CI.yml
src/body/body.rs
src/body/mod.rs
src/client/connect/dns.rs
src/client/connect/mod.rs
src/client/mod.rs
src/server/conn.rs
src/server/mod.rs
src/service/mod.rs

The `cargo doc` step was failing, and CI didn't notice. This should help catch doc failures earlier.

chore(CI): add cargo doc step to CI

---

src/client/connect/http.rs
src/client/connect/mod.rs
src/client/mod.rs

This is *just* a "trait alias". It is automatically implemented for all
`Service<Uri>`s that have the required bounds. It's purpose being public
is to ease setting trait bounds outside of hyper. Therefore, it doesn't
have any exposed associated types, to prevent otherwise relying on any
super-traits that hyper requires.

feat(client): expose `hyper::client::connect::Connect` trait alias

---

src/proto/h1/role.rs
src/proto/mod.rs
tests/client.rs

fix(http1): fix response with non-chunked transfer-encoding to be close-delimited

---

src/headers.rs
src/proto/h2/client.rs

This patch adds content-length header for client request according to rfc7230.
Current implementation adds content-length header for every client request if there is no one. However, according [rfc7230](https://tools.ietf.org/html/rfc7230#section-3.3.2): ` A user agent SHOULD NOT send a Content-Length header field when the request message does not contain a payload body and the method semantics do not anticipate such a body.`
Moreover, in [rfc7230](https://tools.ietf.org/html/rfc7231#section-4), there are similar comments for HTTP Method GET, HEAD, DELETE, CONNECT. For example, `A payload within a GET request message has no defined semantics; sending a payload body on a GET request might cause some existing implementations to reject the request.`
In our situation, current implementation …

fix(http2): add client content-length header accroding to rfc7230

---

src/service/make.rs
src/service/mod.rs
src/service/util.rs

And expose them in docs. Since Clone and Copy can't be propagated out
via `impl Service` I believe it is better to expose them now.
`tower::service_fn` already implement `Clone` and `Copy.

feat: Implement Clone/Copy on ServiceFn and MakeServiceFn

---

src/body/body.rs
src/proto/h1/dispatch.rs
src/proto/h2/client.rs
src/proto/h2/mod.rs
src/proto/h2/server.rs
src/proto/mod.rs

Replaces the `Option<u64>` content-length with a `DecodedLength`, which
stores its unknown-ness as `u64::MAX`.

perf(body): reduce memory size of Body by a u64

---

src/body/body.rs
src/common/mod.rs
src/common/watch.rs
src/proto/h1/conn.rs
src/proto/h1/dispatch.rs
src/proto/h1/mod.rs
tests/server.rs

Before, if a client request included an `Expect: 100-continue` header,
the `100 Continue` response was sent immediately. However, this is
problematic if the service is going to reply with some 4xx status code
and reject the body.
This change delays the automatic sending of the `100 Continue` status
until the service has call `poll_data` on the request body once.
Closes #838

fix(http1): only send `100 Continue` if request body is polled

---

src/body/body.rs
src/client/connect/http.rs
src/client/pool.rs
src/client/tests.rs
src/common/mod.rs
src/error.rs
src/mock.rs
src/proto/h1/conn.rs
src/proto/h1/decode.rs
src/proto/h1/io.rs
src/proto/mod.rs
tests/client.rs
tests/server.rs
tests/support/mod.rs

It was a long time ago one had to write `::std` to make rustc recognize the path. Now just `std` works fine.

style: use just std instead of ::std in paths

---

src/server/tcp.rs

This was specifically added to peek for the first byte to determine if the connection is HTTP or HTTPS.
I copied the documentation from tokio.

feat(server): add poll_peek to AddrStream

---

src/body/body.rs
src/client/conn.rs
src/client/mod.rs
src/proto/h2/bdp.rs
src/proto/h2/client.rs
src/proto/h2/mod.rs
src/proto/h2/server.rs
src/server/conn.rs
src/server/mod.rs

This adds support for calculating the Bandwidth-delay product when using
HTTP2. When a DATA frame is received, a PING is sent to the remote.
While the PING acknowledgement is outstanding, the amount of bytes of all
received DATA frames is accumulated. Once we receive the PING
acknowledgement, we calculate the BDP based on the number of received
bytes and the round-trip-time of the PING. If we are near the current
maximum window size, the size is doubled.
It's disabled by default until tested more extensively.
cc #1960

feat(http2): add adaptive window size support using BDP

---

src/client/mod.rs
src/client/pool.rs
tests/client.rs
tests/support/mod.rs

- Renamed `keep_alive_timeout` to `pool_idle_timeout`.
- Renamed `max_idle_per_host` to `pool_max_idle_per_host`.
- Deprecated `keep_alive(bool)` due to confusing name. To disable the
connection pool, call `pool_max_idle_per_host(0)`.

feat(client): rename `client::Builder` pool options

---

Cargo.toml

Without this, you can end up with tokio 0.2.4 and hyper 0.13.5 in your
project, leading to a compile error like this:
```
error[E0599]: no method named `try_recv` found for struct `tokio::sync::mpsc::unbounded::UnboundedReceiver<client::dispatch::Envelope<T, U>>` in the current scope
--> src/client/dispatch.rs:161:26
|
161 |         match self.inner.try_recv() {
|                          ^^^^^^^^ method not found in `tokio::sync::mpsc::unbounded::UnboundedReceiver<client::dispatch::Envelope<T, U>>`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0599`.
error: could not compile `hyper`.
```

Force tokio to be at least 0.2.5

---

Cargo.toml
src/client/connect/http.rs

Closes https://github.com/hyperium/hyper/issues/2205

Switch from net2 to socket2

---

src/body/body.rs
src/common/mod.rs
src/common/sync_wrapper.rs

A stream wrapped into a Body previously needed to implement `Sync` so
that the Body type implements this autotrait as well (which is needed
due to limitations in async/await). Since a stream only offers one
method that is called with an exclusive reference, this type is
statically proven to be Sync already. In theory it should be fine to add
an `unsafe impl Sync`, but this commit instead adds a Mutex that is
never locked to prove that this approach is correct.
This makes it easier to construct response bodies for client code.
For more discussion on this see [rust-internals](https://internals.rust-lang.org/t/what-shall-sync-mean-across-an-await/12020/12).

feat(body): remove Sync bound for Body::wrap_stream

---

src/client/conn.rs
src/proto/h2/client.rs
src/proto/h2/server.rs
src/server/conn.rs

The default of 16K is taken from h2.

feat(http2): allow configuring the HTTP/2 frame size

---

src/client/mod.rs
src/server/mod.rs

feat(http2): configure HTTP/2 frame size in the high-level builders too

---

Cargo.toml
src/client/conn.rs
src/proto/h2/server.rs
src/server/conn.rs
src/server/shutdown.rs

pin-project will deprecate the project attribute due to some unfixable
limitations.
Refs: https://github.com/taiki-e/pin-project/issues/225
*Although the deprecation of the project attribute has not been released yet, this PR is submitted in advance to avoid the CI from being broken by deprecated warnings.*

Remove uses of pin_project::project attribute

---

src/client/connect/dns.rs

If the runtime is dropped while a DNS request is being made, it can
lead to a panic. This patch checks if the task was cancelled, and
returns a generic IO error instead of panicking in that case.
The following code reproduces the problem on my macOS machine:
```
use hyper::Client;
use tokio::runtime;
type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;
fn main() {
let rt = runtime::Builder::new()
.threaded_scheduler()
.core_threads(1)
.enable_all()
.build()
.unwrap();
// spawn a request and then drop the runtime immediately
rt.spawn(fetch_url());
}
async fn fetch_url() -> Result<()> {
let url: hyper::Uri = "http://example.com".parse()?;
let client = Client::builder().build_http::<hyper::Body>();
let res = client.get(url).await?;
println!("Response: {}", …
```

fix(client): don't panic in DNS resolution when task cancelled

---

examples/README.md
examples/service_struct_impl.rs
src/service/mod.rs

Add `examples/service_struct_impl.rs`, which provides an up-to-date
example of implementing MakeService and Service on custom types.
The `Svc` struct has a Counter, which demonstrates how to instantiate
shared resources in the `MakeSvc` and pass the resource to the
services. Updates the `examples/README.md` and the doc in
`src/service/mod.rs`.
Closes #1691

docs(service): add example of `impl Service`

---

src/proto/h1/conn.rs
src/server/tcp.rs

Using `ready!` in a few places, and avoids getting a future only to poll it manually.

Some simplifications

---

src/client/mod.rs

There's a blanket implementation of `tower_service::Service` for `&mut S` but not for `&S`. Since `hyper::Client::request` takes `&self` only, `&Client` can implement `Service`, allowing users to take advantage of Tower's abstraction without additional ownership restrictions.

feat(client): impl tower_service::Service for &Client

---

Cargo.toml
src/client/mod.rs
src/lib.rs

I've moved Hyper from `log` to `tracing`. Existing `log`-based users shouldn't notice a difference, but `tracing` users will see higher performance when filtering data. This isn't the _end_  of the `tracing` integration that can happen in `Hyper` (e.g., Hyper can start using spans, typed fields, etc.), but _something_ is better than nothing. I'd rather address those points, including examples, in followups.
I've attached a screenshot of the `hello` example working, but the logged information is pulled from `tracing`, not `log`.

feat(lib): Move from `log` to `tracing` in a backwards-compatible way

---

Cargo.toml
src/proto/h1/date.rs

This removes the deprecated `time` crate, and switches to a small implementation using `SystemTime` and an optimized render format specifically needed by the `Date` header.
Running the new benchmarks in `hyper::proto::h1::date`, `check` stayed the same, and `render` went from 400ns to 80ns.

Use httpdate for server date header

---

src/client/connect/http.rs

clarify HttpConnector::new_with_resolver doc, link to hyper::client::connect::dns

---

src/proto/h1/conn.rs
src/proto/h1/io.rs
src/proto/h1/role.rs

Add `trace` level spans to record time spent parsing and encoding headers.

Add spans for parse_headers and encode_headers

---

src/server/conn.rs

Added a module-level, basic example for the `Http` struct in the `server::conn` module. This PR is a work in progress
Begins to address #2272

docs(server): Example for conn modules

---

src/body/body.rs

According to @seanmonstar, bodies being closed in a normal fashion when an error occurs in the spawned task holding the sender is a frequent gotcha. It caught me as well.
This note would have prevented a lot of debugging in my case.
(Let me know if you'd prefer different wording!)

body::Sender: Add a note about abnormal body closing

---

src/client/conn.rs
src/client/mod.rs
src/proto/h1/conn.rs
src/proto/h1/io.rs
src/server/conn.rs
src/server/mod.rs

Add a way to force queued strategy

---

src/client/connect/mod.rs
src/client/mod.rs

These are useful when unit testing connector layers that do things like handling proxies, so you don't need to spin up an entire HTTP request to see if the returned connection state is correct or not. Ideally we'd expose an accessor for the extra info as well, but that's not currently in a form that's easy to work with.

Add accessors to `Connected` fields

---

hyper-capi/examples/Makefile

It also sets rpath to link with the hyper_capi lib in the build dir.

hyper_capi/examples: add makefile to build the example

---

Cargo.toml
src/client/connect/dns.rs
src/client/connect/http.rs

feat(client): allow both IPv6 and IPv4 local addresses

---

src/proto/h2/ping.rs
tests/server.rs

When enabling HTTP2 server keep alive, only the first ping is sent after the configured interval.
Afterwards, no more pings are sent.
More details on this issue: #2310 
The suggested solution checks if `ping_sent_at` has already been cleared by `Ponger::poll` when `KeepAliveState::PingSent` state is active. A test is added to make sure the server produces more than one ping when configured to do so.

Fix server keep alive to send more than one ping

---

src/proto/h1/conn.rs
src/proto/h1/encode.rs

PR #2264 introduced a bug where calling `end_body` on close-delimited
encoders would not actually close the connection. This is because the
call to `encoder.end()` now returns `Ok(None)` for close-delimited
encoders, to prevent the error from being propagated as though the user
body ended too early. However, when `Ok` is returned, the write state is
only advanced to `Closed` if the encoder returns `true` from `is_last`.
This means that when the body is close-delimited, ending the body does
nothing, leaving the connection in keepalive.
This causes a hang in Linkerd, where we proxy HTTP requests connections
by returning a client body in a response. If the upstream server closes
the connection, we need to rely on the close always being propagated to
the connection with our client. This bug …

fix(h1): ending close-delimited body should close

---

examples/http_proxy.rs

The comment shows using a domain name, this doesn't actually work as no DNS lookups are done.

docs: fix http_proxy comment

---

Cargo.toml
src/body/body.rs
src/cfg.rs
src/client/conn.rs
src/client/connect/mod.rs
src/client/dispatch.rs
src/client/mod.rs
src/client/pool.rs
src/common/exec.rs
src/common/io/rewind.rs
src/error.rs
src/headers.rs
src/lib.rs
src/proto/h1/date.rs
src/proto/h2/server.rs
src/proto/mod.rs
src/server/conn.rs
src/server/mod.rs
src/server/shutdown.rs

cc #2251
BREAKING CHANGE: This puts all HTTP/2 methods and support behind an
`http2` cargo feature, which will not be enabled by default. To use
HTTP/2, add `features = ["http2"]` to the hyper dependency in your
`Cargo.toml`.

feat(http2): Make HTTP/2 support an optional feature

---

Cargo.toml
src/body/body.rs
src/cfg.rs
src/client/conn.rs
src/client/mod.rs
src/client/pool.rs
src/common/mod.rs
src/error.rs
src/headers.rs
src/lib.rs
src/proto/h1/conn.rs
src/proto/h1/dispatch.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h2/client.rs
src/proto/h2/mod.rs
src/proto/h2/ping.rs
src/proto/mod.rs
src/service/mod.rs

cc #2223
BREAKING CHANGE: The HTTP client of hyper is now an optional feature. To
enable the client, add `features = ["client"]` to the dependency in
your `Cargo.toml`.

feat(client): Make `client` an optional feature

---

Cargo.toml
src/body/body.rs
src/cfg.rs
src/common/exec.rs
src/common/io/rewind.rs
src/common/mod.rs
src/error.rs
src/headers.rs
src/lib.rs
src/proto/h1/conn.rs
src/proto/h1/dispatch.rs
src/proto/h1/encode.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h1/role.rs
src/proto/h2/mod.rs
src/proto/mod.rs
src/service/mod.rs

BREAKING CHANGE: The HTTP server code is now an optional feature. To
enable the server, add `features = ["server"]` to the dependency in
your `Cargo.toml`.

feat(server): Make the `server` code an optional feature

---

Cargo.toml
src/client/connect/http.rs

We still need `socket2` specifically for TCP keepalive, but we may just
end up removing that soon?
Signed-off-by: Eliza Weisman <eliza@buoyant.io>

refac: use tokio's TcpSocket for more sockopts

---

Cargo.toml
examples/client_json.rs
examples/web_api.rs
src/body/to_bytes.rs
src/proto/h1/encode.rs
src/proto/h1/io.rs

This branch updates `bytes` and `http-body` to the latest versions. The
`http-body` version that uses `bytes` 0.6 hasn't been released yet, so
we depend on it via a git dep for now. Presumably Hyper and `http-body`
will synchronize their releases.
Other than that, this is a pretty mechanical update. Should fix the
build and unblock the `h2` update to use vectored writes.

feat: update `bytes` to 0.6, update http-body

---

examples/http_proxy.rs
examples/upgrades.rs
src/body/body.rs
src/upgrade.rs
tests/client.rs
tests/server.rs

Closes #2086 
BREAKING CHANGE: The method `Body::on_upgrade()` is gone. It is
essentially replaced with `hyper::upgrade::on(msg)`.

feat(upgrade): Moved HTTP upgrades off `Body` to a new API

---

Cargo.toml
src/client/conn.rs
src/client/mod.rs
src/common/io/mod.rs
src/common/io/rewind.rs
src/proto/h1/conn.rs
src/proto/h1/io.rs
src/server/conn.rs
src/server/mod.rs
src/server/tcp.rs
src/upgrade.rs

Tokio's `AsyncWrite` trait once again has support for vectored writes in
Tokio 0.3.4 (see tokio-rs/tokio#3149.
This branch re-enables vectored writes in Hyper. Using vectored writes
in HTTP/2 requires a git dependency on a `h2` branch that adds writev
support in `h2`.
I've removed the adaptive write buffer implementation
that attempts to detect whether vectored IO is or is not available,
since the Tokio 0.3.4 `AsyncWrite` trait exposes this directly via the
`is_write_vectored` method. Now, we just ask the IO whether or not it
supports vectored writes, and configure the buffer accordingly. This
makes the implementation somewhat simpler.
This makes a pretty noticeable performance improvement in the
HTTP/1 end to end benchmarks.
Before:
```
http1_body_both_100kb …
```

feat(lib): re-enable writev support

---

Cargo.toml

fixes #2326
I wasn't sure what the right way to update the changelog was, so I just used my best guess. Let me know if I should do something differently.

remove dependency on `tracing`'s `log` feature

---

Cargo.toml
src/client/connect/http.rs

Additionally, only depend on pnet_datalink to reduce compile times.
Closes #2347

Upgrade libpnet depedency to 0.27.2 [#2347]

---

Cargo.toml

Upgrades to a version not making invalid assumptions about the memory layout of std::net::SocketAddr
Helps unblock https://github.com/rust-lang/rust/pull/78802. See that PR for more details.

Upgrade socket2 dependency

---

examples/gateway.rs

The PathAndQuery already contains the leading slash, which erroneously
sets the proxied path to "//.." and not "/..".

fix(examples) remove extra slash for uri

---

src/client/connect/dns.rs
src/client/connect/http.rs

The DNS resolver part of `HttpConnector` used to require resolving to
`IpAddr`s, and this changes it so that they resolve to `SocketAddr`s.
The main benefit here is allowing for resolvers to set the IPv6 zone ID
when resolving, but it also just more closely matches
`std::net::ToSocketAddrs`.
Closes #1937
BREAKING CHANGE: Custom resolvers used with `HttpConnector` must change
to resolving to an iterator of `SocketAddr`s instead of `IpAddr`s.

feat(client): change DNS Resolver to resolve to SocketAddrs

---

src/proto/h1/role.rs

We use hyper in a proxy-like way where an incoming HTTP/2 request is
proxied to a HTTP/1 backend and it was reported that the warnings
were a limiting factor in the total throughput of the system.
While it can be worked around by explicitly setting the request version
to HTTP_11, it seems likely other people will hit this performance snag,
and I don't see much value in warning for this particular condition, so
I suggest removing them.

fix(client): drop HTTP_2 -> HTTP_11 coerce warning

---

src/body/body.rs
src/proto/h1/dispatch.rs
src/proto/h1/role.rs
src/proto/mod.rs
src/upgrade.rs

Move OnUpgrade state from Body to http::Request/http::Response extensions.
Fixes #2340.

Chore: Move OnUpgrade state from Body to Request/Response

---

src/proto/h1/decode.rs
tests/client.rs

Previously, hyper returned an "Invalid chunk end CR" error on chunked
responses with trailers, as described in RFC 7230 Section 4.1.2. This
commit adds code to ignore the trailers.
Closes #2171

fix(h1): ignore chunked trailers

---

src/proto/h1/decode.rs
tests/client.rs

Original PR:
> Previously, hyper returned an "Invalid chunk end CR" error on chunked
> responses with trailers, as described in RFC 7230 Section 4.1.2. This
> commit adds code to ignore the trailers.
>
> Closes #2171
This PR backports it to 0.13.

fix(http1): backport "ignore chunked trailers (#2357)" to 0.13

---

src/client/connect/http.rs

Socket option errors are converted to warnings. This closes #2359. But I am not sure if it is better to return error if "set_keepalive" fails in line 595.

refactor(client): log socket option errors instead of returning error (#2359)

---

Cargo.toml
src/body/to_bytes.rs
src/client/connect/http.rs
src/client/dispatch.rs
src/client/pool.rs
src/common/buf.rs
src/common/io/mod.rs
src/proto/h1/encode.rs
src/proto/h1/io.rs
src/proto/h2/mod.rs
src/proto/h2/ping.rs
src/server/tcp.rs
src/upgrade.rs
tests/client.rs

feat(lib): Upgrade to Tokio 1.0

---

src/client/connect/http.rs
src/proto/h2/client.rs

Companion to https://github.com/hyperium/h2/pull/503 which does not manage to improve things as much  (421370 / 433142 = 0.97282184595).
There could be more gains here but it would require more invasive changes as a lot more functions ends up getting parametrized by `T: AsyncRead + AsyncWrite` which ends up beeing `AddrStream` for servers and `TcpStream` for clients. This seems possible to change to `TcpStream` for servers as well though, at least for simple setups as hyper itself never uses the `AddrStream` wrapper. However that is a breaking change and in uses where you more manually construct the server `AddrStream` may then be useful again (I have gotten the code down to 407528 / 433142 = 0.9408646587 in a branch which changes this).
```
cargo llvm-lines --release --example http_proxy …
```

Minimize the amount of instantiated code

---

src/server/server.rs

The docs on `Server` are missing the required `tcp` feature.

Set doc_cfg attributes for `tcp` feature gated Server methods

---

src/client/client.rs

Saving the next dev that copy pastes this example from banging their head trying to figure out what's wrong with their DNS 😁

docs(client): fix typo in httpbin.org domain

---

src/body/mod.rs

Fix a minor papercut: you can't implement `hyper::body::HttpBody::size_hint` without importing `SizeHint` from another crate.

feat(body): reexport http_body::SizeHint

---

src/client/dispatch.rs
src/proto/h1/dispatch.rs
src/proto/h2/client.rs

While looking further into #2388 I noticed `UnboundedReceiver` was getting pinned even though [`UnboundedReceiver::poll_recv`](https://docs.rs/tokio/1.0.2/tokio/sync/mpsc/struct.UnboundedReceiver.html#method.poll_recv) takes `&mut self`. This detail was probably missed in the migration from tokio 0.3, which [previously used `Stream::poll_next`](https://github.com/hyperium/hyper/pull/2369/files#diff-414def8886b02bb26f69e6e93e08fa35e230e7faf2b37cf1614cdf58fe987a5dL153-R154), but can now be applied, unblocking #2393.

Remove useless uses of Pin

---

Cargo.toml
src/body/body.rs
src/client/conn.rs
src/client/connect/http.rs
src/client/mod.rs
src/client/pool.rs
src/common/drain.rs
src/common/exec.rs
src/common/mod.rs
src/headers.rs
src/proto/h1/dispatch.rs
src/proto/h2/mod.rs
src/proto/h2/server.rs
src/proto/mod.rs
src/server/accept.rs
src/server/conn.rs
src/server/server.rs
src/server/shutdown.rs
src/server/tcp.rs
src/service/mod.rs
src/service/oneshot.rs

Will fix #2388.
~~Blocked on taiki-e/pin-project-lite#3.~~ ([workaround](https://github.com/hyperium/hyper/issues/2388#issuecomment-758304097))
~~Blocked on taiki-e/pin-project-lite#25.~~ (see comment below)

Switch to pin-project-lite

---

src/body/aggregate.rs
src/body/to_bytes.rs

The to_bytes and aggregate don't check how long the body is, so the user
better be aware.
Relates to #2414.

docs(lib): Warn about no length check

---

src/common/buf.rs

Some implementations of the Buf trait have an optimized version (for
example Bytes) of copy_to_bytes, opportunistically use that one.
For some background, I was implementing a similar type and had a look there and noticed it is not implemented. Or is there some reason why it _shouldn't_ be implemented?

Specialize BufList::copy_to_bytes

---

Cargo.toml
src/client/conn.rs
src/client/connect/http.rs
src/client/dispatch.rs
src/client/pool.rs
src/common/drain.rs
src/proto/h1/dispatch.rs
src/proto/h2/mod.rs
src/proto/h2/server.rs
src/server/accept.rs
src/server/conn.rs
src/server/server.rs
src/server/shutdown.rs
src/server/tcp.rs
src/service/oneshot.rs

It seems that the pin-project-lite isn't noticing the `cfg(feature = "..")` attributes on enum variants or fields, and *also* our CI didn't notice the failure of combining `--features http1,client,server`.
I'm reverting this change since it's the fastest way for me to unbreak and get a new release out.
Closes #2421 
cc @jplatte @taiki-e

Revert pin project lite

---

.github/workflows/CI.yml

This allows catching the issue like https://github.com/hyperium/hyper/issues/2421.
> > _also_ our CI didn't notice the failure of combining `--features http1,client,server`.
>
> This can be fixed by using `cargo hack --feature-powerset` ([all combination of features](https://github.com/taiki-e/cargo-hack#--feature-powerset)) instead of `cargo hack --each-feature` ([each feature](https://github.com/taiki-e/cargo-hack#--each-feature)) in CI. 
> However, if we use `--feature-powerset`, there will be more than 700 feature combinations, so we may need to use `--depth` ([specify a max number of simultaneous feature flags of --feature-powerset](https://github.com/taiki-e/cargo-hack/issues/58)) flag to limit the number of combinations.
We have too many features to check the full powerset (776), …

chore(ci): use --feature-powerset --depth 2 in features check

---

src/server/mod.rs

This is required to surface the required feature (`tcp`) in the generated docs
for `hyper::server::conn::{AddrIncoming, AddrStream}`. Before this change,
their docs only mentioned the features needed for the `hyper::server::conn` mod
itself.
Fixes #2425

docs(server): use cfg_feature! on hyper::server::conn::tcp instead of #[cfg]

---

src/proto/h1/role.rs

This PR backports https://github.com/hyperium/hyper/commit/8f93123efef5c1361086688fe4f34c83c89cec02 to 0.12, which is the first affected branch (but fix was made and released for 0.13+).
I know it's old and unmaintained, and don't really expect a new release, but we still use it in some LTS products. If it's still used elsewhere it may make more sense to share the backports here than to do it in a private fork.

Backport fix for multiple Transfer-Encoding to 0.12 branch

---

src/client/client.rs
src/client/conn.rs
src/client/dispatch.rs
src/common/lazy.rs
src/server/conn.rs

I thought the `Unpin` relaxation in `Lazy` could be used to remove some more combinators in `connect_to`, but it seems that `future::select` is to restrictive, and won't work with `pin_mut!`. Left it in anyway, in case it ends up useful elsewhere

refactor: Use async/await more

---

Cargo.toml
src/server/mod.rs

`tower` 0.4.5 introduced `Shared` which is a `MakeService` that produces
services by cloning an inner service. This works quite well with `hyper`
if your service doesn't need the incoming connection and implements
`Clone`.
However that might not be entirely obvious so I thought it made sense to
add an example to the docs.
I wasn't quite sure if the example should go in the server or service
module docs but since there already is an example using
`make_service_fn` in the server docs I opted to add it there. Let me
know if you'd rather have it somewhere else.

docs(server): add server example using `tower::make::Shared`

---

src/client/client.rs

omitting default port from Host header

---

examples/README.md

It's time to update example version.

docs(version): use hyper v0.14 and full feature

---

src/body/body.rs

Since these two functions are not methods on the `Body`, they aren't very discoverable. So a note in the docs would definitely be helpful.

Body docs: Link to to_bytes and aggregate

---

src/headers.rs
tests/client.rs

Support multiple Content-Length values on same line

---

Cargo.toml
src/client/connect/http.rs
src/server/tcp.rs

I've limited the changes as much as possible, e.g. I didn't add any `use` statements.
/cc @eliza some TODOs have your name on them, might want to look if there still valid.

Update to socket2 v0.4.0

---

src/client/client.rs
src/client/conn.rs
src/lib.rs
src/proto/h1/conn.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h1/role.rs
tests/client.rs

The two first commits work around some issues I had with VS Code and rust-analyzer.

Allow HTTP/0.9 responses behind a flag (fixes #2468)

---

src/ffi/body.rs
src/ffi/client.rs
src/ffi/http_types.rs
src/ffi/io.rs
src/ffi/macros.rs
src/ffi/mod.rs
src/ffi/task.rs

Make C API functions that return pointers return null in case of a
panic, instead of aborting.
Add ffi_fn! macro rules that enable error values to be returned by
writing "?= <value>" or "?: <closure>" after an ffi function's body.
Incremental to #2397

Return null instead of aborting in C API by extending ffi_fn! macro

---

Cargo.toml

Previous version would return wrong results for `Ord`.

Update httpdate to v1.0

---

.github/workflows/CI.yml

Socket2 v0.4 requires Rust 1.46.
Closes #2482.

Increase MSRV to 1.46

---

capi/gen_header.sh
src/ffi/mod.rs

As I understand it, "cargo rustc" in gen_header.sh generates a ton of
errors, but still manages to generate an object that can be used by
cbindgen to generate hyper.h.
However, I tried to make a separate change to add more fields to
hyper.h, and learned that "cargo rustc" stops if it reaches 50 errors,
which I reached. I was able to buy some headroom and fix a number of
the compilation errors by adding imports to the fake Cargo.toml we
generate in gen_header.sh.
I wasn't sure how to resolve imports like "crate::Result" which appear
to reference the top-level src/error.rs, and print an error when they
are compiled in gen_header.sh. But I only need to buy headroom under
the 50 error count for now, which I was able to do by adding the
imports.
It is possible that someone more familiar with …

chore(ffi): fix compile errors and warnings

---

examples/http_proxy.rs
src/server/conn.rs
src/server/server.rs

Turns out I didn't implement the server-side public setters for #2480, oopsie.

Implement forgotten settings for case preserving

---

examples/http_proxy.rs

A `String` authority will be converted to `SocketAddr` (https://docs.rs/tokio/1.5.0/tokio/net/trait.ToSocketAddrs.html) via under-the-hood DNS lookups. The proxy only needs to check whether the authority part exists (the uri is an absolute uri) to support requests to domain names. This would make the example even more useful.
Another change I packed into this PR is to slightly simplify the `tunnel` method using `tokio::io::copy_bidirectional`. I'm open for objections if this introduces some side effects that I'm unware of.

Support requets to domain names in example http_server

---

src/lib.rs

Need to use no_inline doc to fix broken links
https://github.com/hyperium/http/blob/1179d6fa90fc6d680c718450b18f223cb0b25aeb/src/lib.rs#L187

docs(headers) no_inline doc on HeaderMap

---

src/client/client.rs

Small docs improvement to mention that cloning a `Client` is cheap and
will reuse the connection pool.
Fixes https://github.com/hyperium/hyper/issues/2239

docs(client): document the guarantees of cloning a `Client`

---

src/server/mod.rs

It can sometimes be tricky to discover where to use `move` closures,
`async move {}`, and `.clone()` when creating a server. This adds a
slightly more bigger example that will hopefully help some.
Fixes https://github.com/hyperium/hyper/issues/2446

docs(server): add bigger example to server module

---

src/common/sync_wrapper.rs

I noticed this triggered an error on nightly, so removing.

docs(common): remove favicon doc from sync_wrapper module

---

src/client/client.rs
src/client/conn.rs
src/proto/h2/client.rs

Setting streams to 0 makes h2 work on wasm platforms without `Instant::now` implementation.
Related to:
* https://github.com/hyperium/h2/pull/511
* https://github.com/hyperium/h2/pull/537

Allow to config h2 max concurrent reset streams.

---

src/error.rs
tests/client.rs

The discussion in #2462 opened up some larger questions about more comprehensive approaches to the error API, with the agreement that additional methods would be desirable in the short term. These methods address an immediate need of our customers, so I would like to get them in first before we flesh out a future solution.
One potentially controversial choice here is to still return `true` from `is_parse_error()` for these variants. I hope the naming of the methods make it clear that the new predicates are refinements of the existing one, but I didn't want to change the behavior of `is_parse_error()` which would require a major version bump.

feat(error): add predicates for too-large and status parse errors

---

src/proto/h2/ping.rs

This introduces a delay to sending a ping to calculate the BDP that
becomes shorter as the BDP is changing, to improve throughput quickly,
but then also becomes longer as the BDP stabilizes, to reduce the amount
of pings sent. This improved the performance of the adaptive window
end_to_end benchmark.
It should also reduce the amount of pings the remote has to deal with,
hopefully preventing hyper from triggering ENHANCE_YOUR_CALM errors.
cc #2526

perf(http2): reduce adaptive window pings as the BDP stabilizes

---

src/client/client.rs
tests/client.rs

Previously, Hyper would unconditionally reject requests with `Version::HTTP_2` if `http2_only(true)` was not provided when building the client. This change allows such requests to succeed as long as the underlying connection is actually negotiated as HTTP/2.

feat(http2): allow HTTP/2 requests by ALPN when http2_only is unset

---

Cargo.toml
src/body/length.rs
src/client/client.rs
src/error.rs
src/proto/h2/client.rs
src/proto/h2/mod.rs
src/proto/h2/server.rs
src/upgrade.rs
tests/client.rs
tests/server.rs

There are quite a few details to sort out, grep for `FIXME(nox)`.

Implement CONNECT support over HTTP/2

---

Cargo.toml
src/client/conn.rs
src/client/connect/http.rs
src/client/pool.rs
src/common/drain.rs
src/common/lazy.rs
src/proto/h1/dispatch.rs
src/proto/h2/mod.rs
src/proto/h2/server.rs
src/server/accept.rs
src/server/conn.rs
src/server/server.rs
src/server/shutdown.rs
src/server/tcp.rs
src/service/oneshot.rs

Second try, turned out to require a bunch more changes in `src/client/conn.rs` and `src/server/conn.rs` due to the `ProtoClient` and `ProtoServer` enums which previously had `cfg`-conditional variants (which aren't supported by pin-project-lite). Now the variants that previously were disabled by `cfg(not(feature = "http1"))` and `cfg(not(feature = "http2"))` are instead made to be uninhabited.
The code would be a decent amount simpler if the non-exhaustive variants could be omitted in `match`es (https://github.com/rust-lang/rust/issues/51085).

refactor(lib): Switch from pin-project to pin-project-lite (again)

---

src/error.rs
src/proto/h1/role.rs

Initial implementation that aims to solve #2534 by returning a `Parse::Internal` error instead of panic.  
I intentionally added a new Parse error instead of a new Kind since i think this is still relevant and the diff is much cleaner.
cc @nox  for [this message](https://github.com/hyperium/hyper/issues/2534#issuecomment-835436759), if this is very important to add here, let me know.

Return Parse::Internal error if there's an illegal header name or value

---

src/error.rs

Replaced the comparisons with `matches!`. This should reduce a bit of
code generation that isn't really needed.

refactor(error): remove PartialEq derives for error kind enums

---

capi/examples/upload.c
capi/include/hyper.h
src/ffi/http_types.rs
src/ffi/mod.rs
src/proto/h1/conn.rs
src/proto/h1/dispatch.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h1/role.rs
src/proto/mod.rs

This defines an extension type used in requests for the client that is
used to setup a callback for receipt of informational (1xx) responses.
The type isn't currently public, and is only usable in the C API.
cc #2565

feat(ffi): add hyper_request_on_informational

---

src/proto/h2/mod.rs

That Proxy-Authenticate and Proxy-Authorization are forbidden over h2
is not actually specified anywhere, plus h2 also supports CONNECT
requests, which are specifically made to do requests over a proxy,
and those proxies may require authentication, sometimes through
Proxy-Authorization.
Note that there is an openwebdocs project that just started to clear
up any MDN-induced confusion in implementations:
> https://github.com/openwebdocs/project/issues/43
Also, Daniel Stenberg (curl) also recently commented about
Proxy-Connection not being stripped out by curl, Hyper may want to
also remove Proxy-Connection from the list for that reason:
> https://twitter.com/bagder/status/1415967315817082880

fix(h2): preserve proxy authentication headers

---

examples/params.rs

To make the documentation more helpful.

feat(server): add an example for get method.

---

src/error.rs

This should resolve the "unused" warnings in CI.

refactor(error): mark TransferEncodingInvalid variant only with server feature

---

capi/include/hyper.h
src/ffi/task.rs

The docs for `hyper_waker_wake` were accidentally copied over from `hyper_waker_free`, so I rewrote it.

docs(ffi): copy-paste error

---

src/client/client.rs
src/client/conn.rs
src/ffi/client.rs

These options are currently available on the high-level builder only.
Along the way, rename the setters to follow the public API conventions and add docs.
Closes #2461

Expose http09 and http1 options on low-level client connection builders.

---

src/proto/h1/role.rs

Fix the header title-casing to work with consecutive dashes. Previously with two dashes in a row the first dash would uppercase the second dash which would then not count, so `weird--header` would be cased as `Weird--header` instead of `Weird--Header`.

fix(headers): apply header title case for consecutive dashes

---

capi/examples/upload.c
src/ffi/body.rs
src/ffi/client.rs
src/ffi/error.rs
src/ffi/http_types.rs
src/ffi/io.rs
src/ffi/macros.rs
src/ffi/task.rs

This changes all the extern C functions in `hyper::ffi` to check passed
pointer arguments for being `NULL` before trying to use them. Before, we
would just assume the programmer had passed a good pointer, which could
result in segmentation faults. Now:
- In debug builds, it will assert they aren't null, and so if they are,
a message identifying the argument name will be printed and then the
process will crash.
- In release builds, it will still check for null, but if found, it will
return early, with a return value indicating failure if the return type
allows (such as returning NULL, or `HYPERE_INVALID_ARG`).
Closes #2620

refactor(ffi): check pointer arguments for NULL

---

capi/examples/Makefile

Sorry, it used the wrong object to build `upload`...

examples/Makefile: fix typo in the upload build

---

src/proto/h1/role.rs

This patch fixes #2532
It uses methods implemented ~~[in this PR](https://github.com/seanmonstar/httparse/pull/97)~~ [in this PR](https://github.com/seanmonstar/httparse/pull/98), so CI might fail before it gets merged

Use new methods for parsing with uninitialized headers from httparse

---

capi/examples/upload.c
capi/include/hyper.h
src/ffi/http_types.rs
src/proto/h1/role.rs

The response wasn't properly "wrapped", which builds up the original case map too. Noted in #2565.

fix(ffi): on_informational callback had no headers

---

src/body/length.rs
src/cfg.rs
src/client/client.rs
src/client/conn.rs
src/client/connect/dns.rs
src/client/connect/http.rs
src/client/dispatch.rs
src/client/pool.rs
src/client/service.rs
src/common/exec.rs
src/common/mod.rs
src/error.rs
src/lib.rs
src/proto/h1/conn.rs
src/proto/h1/decode.rs
src/proto/h1/dispatch.rs
src/proto/h1/encode.rs
src/proto/h1/io.rs
src/proto/h1/role.rs
src/proto/h2/client.rs
src/proto/h2/mod.rs
src/proto/h2/ping.rs
src/proto/h2/server.rs
src/proto/mod.rs
src/server/conn.rs
src/server/mod.rs
src/server/server.rs
src/server/shutdown.rs
src/server/tcp.rs
src/upgrade.rs

I discovered in https://github.com/tokio-rs/axum/pull/286 that two items from hyper that axum uses (`Server`, `server::conn::AddrStream`) are not available without one of `http1`, `http2` being activated even though it seemed like they could be made available. This PR makes them available (among some other refactorings), albeit with `Server` not actually being usable.

Export more things with Cargo features [server, !http1, !http2]

---

src/proto/h1/conn.rs
src/proto/h1/dispatch.rs
src/proto/h1/io.rs

A client connection that read a full response while the request body was
still flushing would see incorrect behavior, since the pool would let it
be checked out again for a new request. In debug builds, it would then
panic, but in release builds it would intermix the 2nd request bytes
with the body of the previous request.
In practice, this only ever happens if a server replies with a full
response before reading the full request, while also choosing to not
close that connection. Most servers either wait for the full request, or
close the connection after the new response is written, so as to stop
reading.
Closes #2643

fix(client): don't reuse a connection while still flushing

---

capi/include/hyper.h
src/ffi/http_types.rs

Add a second FFI interface for setting the URI of a request with three separate schema, authority, and path/query strings, rather than one URI string.
I'd like to add this new API to simplify integration with programs like curl where the URL has already been parsed to some degree by the client. This new function, backed by `Url::builder()` will allow passing more components through as-is, rather than concatenating them into a URL string in C and then parsing it again in Rust.

feat(ffi): add hyper_request_set_uri_parts

---

Cargo.toml
examples/client_json.rs

- remove ```extern crate``` import to comply with 2018 edition
- change from ```use bytes::Buf``` to ```use hyper::body::Buf```, remove one extra import of the bytes module

fix(examples): updated imports in examples

---

src/upgrade.rs

Allow using `Request<T>`/`Response<T>` for any given T with `upgrade::on` instead of just restricting it to `hyper::Body`.
#2086 mentioned moving the upgrades API off of the Body type with part of the motivation being:
>This also makes it more annoying for users who may wish adjust their `http::Request<Body>` into some `http::Request<Doodad>`.
But the current API is still restricted to just the `hyper::Body` body type which seems more strict than it needs to be.

feat(upgrade): allow http upgrades with any body type

---

src/body/to_bytes.rs
src/client/mod.rs

The first commit fixes #2687, the second one fixes a very similar issue regarding a client doctest.

docs(client, body): fix doctests failing when certain features are disabled

---

Cargo.toml
src/error.rs
src/proto/h1/conn.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h1/role.rs
src/server/conn.rs
src/server/server.rs
tests/server.rs

Implements a timeout for reading the request header. The timer starts either when the connection is established (first request) or when the first byte is read from the header (subsequent requests reusing the same connection). The entire header must be read before the specified timeout is elapsed.
This is the first step towards protecting from Slowloris types of attacks
Supersedes #2661 by fixing https://github.com/hyperium/hyper/pull/2661#discussion_r728809455
Partially fixes #2457
Closes #2661

feat(h1): add server header read timeout

---

src/error.rs
src/proto/h1/role.rs
tests/server.rs

Previous behavior returned a 404 Bad Request. Conforms to HTTP 1.1 RFC.
Closes #2701

fix(http1): return 414 when URI contains more than 65534 characters

---

src/proto/h1/role.rs
tests/server.rs

According to rfc2616#section-14.20 the header value is case-
insensitive. Certain clients (including Java's std lib
https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.net.http/share/classes/jdk/internal/net/http/Exchange.java#L408)
send the expectation as `100-Continue` and this should be handled
by the server.
(This is an attempt to address https://github.com/hyperium/hyper/issues/2708)

fix(server): use case-insensitive comparison for Expect: 100-continue

---

src/body/body.rs
src/body/length.rs
src/proto/h2/server.rs
tests/server.rs

An HTTP/2 stream may include a set of headers, and a flag signalling
END-STREAM, even if a `content-length` isn't included. hyper wouldn't
notice, and so the `Body` would report a size-hint of `0..MAX`. hyper
now notices that the stream is ended, and couldn't possibly include any
bytes for the body, and thus will give a size-hint of `0` exactly.
Closes #2712

fix(http2): received `Body::size_hint()` now return 0 if implicitly empty

---

Cargo.toml
src/client/client.rs
src/client/conn.rs
src/proto/h2/client.rs
src/proto/h2/server.rs
src/server/conn.rs
src/server/server.rs

This value is like a high-water mark. It applies per stream. Once a
stream has buffered that amount of bytes to send, it won't poll more
data from the `HttpBody` until the stream has been able to flush under
it.

feat(http2): add `http2_max_send_buf_size` option to client and server

---

Cargo.toml
src/proto/h1/role.rs

serde_json already uses this and I've already submitted a PR for http. This will let new builds of hyper only have a single version of itoa again.

chore(dependencies): update to itoa 1

---

src/client/connect/dns.rs

Use Box<str> in hyper::client::connect::dns::Name, so
its size is 16 bytes, not 24 bytes.  As Name never
change its contents, read-only Box<str> is perfectly OK.

refactor(client) use Box<str> in ..::dns::Name

---

src/client/pool.rs

We have reports of runtime panics (linkerd/linkerd2#7748) that sound a
lot like rust-lang/rust#86470. We don't have any evidence that these
panics originate in hyper, but #2385 reports a similar issue.
Even though this is almost definitely a bug in Rust, it seems most
prudent to actively avoid the uses of `Instant` that are prone to this
bug.
This change replaces uses of `Instant::elapsed` and `Instant::sub` with
calls to `Instant::saturating_duration_since` to prevent this class of
panic.

Avoid panics in uses of `Instant`

---

src/error.rs

This is an alternate solution to https://github.com/hyperium/hyper/issues/2732 that doesn't change `hyper::Error`'s `Display` impl (like https://github.com/hyperium/hyper/pull/2542 does).
It adds `Error::message` which returns the message that is unique to the error, without the message from the source. That way users can create a newtype around `hyper::Error` and use this in the `Display` impl to work around https://github.com/hyperium/hyper/issues/2732.
Fixes https://github.com/hyperium/hyper/issues/2732

feat(error): add `Error::message`

---

src/client/conn.rs
src/ext.rs
src/lib.rs
src/proto/h2/client.rs
src/proto/h2/server.rs
src/server/conn.rs
src/server/server.rs

Needs https://github.com/hyperium/h2/pull/565 first.

feat(h2): implement the extended CONNECT protocol from RFC 8441

---

src/client/client.rs

added cfg attr to denote required tcp feature in docs for Client::new method
Closes: #2759

docs(client): Add tcp feature for Client::new docs

---

src/client/connect/http.rs

The `HttpConnection` struct now adds `local_addr` information from `TcpStream` to the `HttpInfo` struct
This resolves the issue #2767

Add local_addr information from TcpStream to the HttpInfo struct

---

src/error.rs
src/proto/h1/conn.rs
src/proto/h1/encode.rs

When a request or response includes a `content-length` header, but then the `impl HttpBody` ends before all the data has been written, the returned error message has been improved from:
```
error from user's HttpBody stream: body write aborted
```
to:
```
user body write aborted: early end, expected 49 more bytes
```

refactor(error): improve error message when user body ends early

---

src/common/exec.rs
src/server/conn.rs
src/server/mod.rs
src/server/server.rs
src/server/server_stub.rs
src/server/shutdown.rs

The actual code for `Server` was previously organized very confusingly: it was thrice layered with `SpawnAll` and `Serve` which both appeared in conn.rs despite not having anything to do with the lower-level conn API. This PR changes that, removing all layering and having the code for the higher-level `Server` appear inside `server.rs` only.

Move non-conn code out of conn.rs

---

capi/examples/client.c
capi/examples/upload.c

Hello there! I saw the blog posts regarding this project's campaign for 1.0. 🥳
I figured I could help out with the C examples by making the code style regarding early returns more consistent. I found that (prior to this PR) the examples tended to mix between coding styles. On a personal note, I much prefer reading code with early returns anyway since there are less indentations/nested braces to worry about. 😅
So with that said, this PR simply refactors instances of nested error-handling logic as early returns. The result is more "linear" code with less indentations. Hooray!
To help make the review easier, I have also separated the commits into the specific decisions I took while refactoring. Hope this helps out a little bit with the documentation for the C API. Thanks!

Refactor(capi): make early returns consistent in C examples

---

src/server/tcp.rs

Expose local address of tcp connection in AddrStream for the purpose mentioned in #2773. It is safe to call underlying `getsockname`, because socket is already connected to the peer at the point of `socket.local_addr()?` execution.

fix(server): use local address in AddrStream

---

capi/include/hyper.h
src/client/conn.rs
src/ext.rs
src/ffi/client.rs
src/ffi/http_types.rs
src/proto/h1/conn.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h1/role.rs

Libcurl expects that headers are iterated in the same order that they
are recieved. Previously this caused curl tests 580 and 581 to fail.
SUMMARY OF CHANGES: Add a new data structure to HeaderCaseMap that
represents the order in which headers originally appear in a HTTP
message. This datastructure is `Vec<(Headername, multimap-index)>`.
This vector is ordered by the order which headers were recieved.
This new datastucture is used in hyper_headers_foreach to iterate
through headers in the correct order.
CLOSES ISSUE: #2780
BEAKING CHANGE: HeaderCaseMap::append now requires that names passed
into it impl Into<HeaderName> + Clone. Currently all types that impl
IntoHeaderName (in hyper and http) also impl these traits already.

fix(ffi): Change hyper_headers_foreach to iterate in recieved order

---

src/proto/h1/conn.rs

Hello there! This PR features assorted refactoring techniques that hopefully improves readability. No behavior change is expected.
Most of the refactoring involved using the [`matches!` macro](https://doc.rust-lang.org/core/macro.matches.html) instead of explicit Boolean `match` expressions. Other refactoring involved transforming logic to early returns. The overall result is that the code is now a little bit less nested. 🎉
With that said, please feel free to inform me if some of the changes need improvement. Thanks!

Refactor: assorted code readability improvements in `h1/conn.rs`

---

src/proto/h1/role.rs
tests/server.rs

Head responses should not have content-length implicitly set by hyper.
Fixes #2835

fix(http1): don't add content-length to head resp

---

docs/ROADMAP.md

The VISION outlines a decision-making framework, use-cases, and general shape
of hyper. This roadmap describes the currently known problems with hyper, and
then shows what changes are needed to make hyper 1.0 look more like what is in
the VISION.
[Rendered](https://github.com/hyperium/hyper/blob/roadmap/docs/ROADMAP.md)
(Another step in the [hyper 1.0 timeline](https://seanmonstar.com/post/676912131372875776/hyper-10-timeline).)

Propose the 1.0 Roadmap

---

docs/ISSUES.md
docs/ROADMAP.md
docs/VISION.md

Signed-off-by: r <ryanrussell@users.noreply.github.com>

docs(various): Improve readability

---

src/ext.rs

running default build command
```rust
cargo build
```
reports
```bash
warning: unused import: `http::header::HeaderName`
--> src/ext.rs:4:5
|
4 | use http::header::HeaderName;
|     ^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
```

refactor(lib): resolve unused import

---

src/ext.rs
src/ext/h1_reason_phrase.rs
src/ffi/http_types.rs
src/proto/h1/role.rs
tests/client.rs
tests/server.rs

Add a new extension type `hyper::ext::ReasonPhrase` gated by a new feature flag `http1_reason_phrase`. When enabled, store any non-canonical reason phrases in this extension when parsing responses, and write this reason phrase instead of the canonical reason phrase when emitting responses.
Reason phrases are a disused corner of the spec that implementations ought to treat as opaque blobs of bytes. Unfortunately, real-world traffic sometimes does depend on being able to inspect and manipulate them.
My main outstanding question is: should this new feature flag be included in `full`? Excluding it means this patch also has to modify the CI configuration in order to run the `client` and `server` tests.

feat(ext): support non-canonical HTTP/1 reason phrases

---

src/server/conn.rs
src/server/mod.rs
src/server/tcp.rs
src/service/make.rs

Remove `AddrStream` type, it provides no benefit over `tokio::net::TcpStream`.
Closes issue #2850
This is my first contribution to this project, so I may have missed something. I am happy to take any feedback. Thanks!
- I'm not quite sure if my changes to `AddrIncoming.poll_next_` method are correct, or if that method is actually used anywhere.
- `AddrStream` is used in documentation related to `make_service`, but as I understand it, `make_service` will be removed anyway in a different PR. Ref issue #2854

feat(server): remove addrstream struct

---

src/proto/h1/role.rs

Fix: https://github.com/hyperium/hyper/issues/2888

fix(http1): fix h1_header_read_timeout_running

---

.github/workflows/CI.yml
docs/MSRV.md

`indexmap` now requires 1.56...

chore(lib): bump MSRV to 1.56

---

.github/workflows/CI.yml
Cargo.toml
benches/body.rs
benches/server.rs
examples/echo.rs
examples/send_file.rs
examples/web_api.rs
src/body/body.rs
src/common/mod.rs
src/error.rs
src/lib.rs
src/server/accept.rs
tests/client.rs
tests/server.rs

Removes the `stream` cargo feature and any usage of `Stream`, including `Body::wrap_stream`, `impl Stream for Body` and `accept::from_stream`.
A few tests were broken, and some examples. Quite extensive changes were needed to fix some of them, which I wasn't able to do in this PR. As discussed on Discord I left TODO comments on the remaining broken tests, tagged with the PR number (#2896).
This PR partially fixes issue #2855.

Remove stream cargo feature

---

capi/include/hyper.h
src/ffi/client.rs

feat(ffi): add http1_allow_multiline_headers

---

src/client/conn/http1.rs
src/client/conn/http2.rs
src/client/conn/mod.rs
src/client/dispatch.rs

This creates `client::conn::http1` and `client::conn::http2` modules,
both with specific `SendRequest`, `Connection`, and `Builder` types.
cc #2842

feat(client): introduce version-specific client modules

---

src/proto/h1/role.rs
tests/client.rs

This used to simply replace any `\r` and `\n` with a space. While that much is valid, it wouldn't replace leading HTABs, which are also used to start a folded line. The specification also says 1-or-more, and curl chooses to make that exactly 1. By trimming while unfolding, we get the same output.
@nox did you want to check that while this does change the number of whitespaces that might be in a header field, this hopefully shouldn't break your use cases?

fix(http1): trim obs-folded headers when unfolding

---

benches/pipeline.rs
benches/server.rs

Re-enable two of the `benches` disabled in #2929, using `hyper::server::conn` rather than the higher-level `Server` struct which is getting removed.
I tested the updated benches by running them on this branch and also on the commit before #2929, and they have the same performance. I tried to implement graceful shutdown, but I'm not sure how to do it without `Server`. I see there is an issue (#2862) to add a helper for this to `hyper-util`, but if it can be implemented without it I am happy to keep trying.
PS. I don't have a firm grasp on async yet, so please let me know if I did something weird :smile: 
Partially closes #2930

[WIP] fix(benches): re-enable the recently disabled benches

---

examples/echo.rs
examples/hello.rs
examples/http_proxy.rs
examples/multi_server.rs
examples/params.rs
examples/send_file.rs
examples/service_struct_impl.rs
examples/upgrades.rs
examples/web_api.rs
src/body/body.rs
src/body/mod.rs
src/body/to_bytes.rs
src/client/conn/http1.rs
src/client/conn/http2.rs
src/client/conn/mod.rs
src/client/dispatch.rs
src/ffi/body.rs
src/ffi/client.rs
src/ffi/http_types.rs
src/lib.rs
src/proto/h1/dispatch.rs
src/proto/h1/role.rs
src/proto/h2/client.rs
src/proto/h2/server.rs
src/server/conn.rs
src/service/util.rs
tests/client.rs
tests/server.rs
tests/support/mod.rs

Resolves https://github.com/hyperium/hyper/issues/2963
This currently branches off of https://github.com/hyperium/hyper/pull/2961

Rename body to recv temporarily

---

src/body/body.rs
src/body/mod.rs
tests/client.rs

Make `body::Sender` and `Body::channel` (currently named `Recv::channel`) private, and update the tests that relied on these types. As far as I can see there were only two affected tests, as well as the `end_to_end` benchmark which is currently disabled (#2930). 
I ended up using `#[allow(unused)]` a few places in `body` after making the aforementioned types private, please let me know if you'd like me to take a different approach.
This closes #2962

feat: make body::Sender and Body::channel private

---

Cargo.toml
benches/support/mod.rs
benches/support/tokiort.rs
src/client/conn/http1.rs
src/client/conn/http2.rs
src/client/conn/mod.rs
src/common/mod.rs
src/common/time.rs
src/proto/h1/conn.rs
src/proto/h1/dispatch.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h1/role.rs
src/proto/h2/client.rs
src/proto/h2/ping.rs
src/proto/h2/server.rs
src/rt.rs
src/server/conn.rs
tests/client.rs
tests/server.rs
tests/support/mod.rs
tests/support/tokiort.rs

This adds a `hyper::rt::Timer` trait, and it is used in connection
builders to configure a custom timer source for timeouts.
Closes #2846 
Closes #2847 
Closes #2848 
Continues #2904

feat(rt): add Timer trait

---

Cargo.toml
benches/support/tokiort.rs
src/client/conn/http2.rs
src/client/conn/mod.rs
src/client/mod.rs
src/common/exec.rs
src/common/io/rewind.rs
src/common/mod.rs
src/common/time.rs
src/error.rs
src/lib.rs
src/proto/h1/conn.rs
src/proto/h1/decode.rs
src/proto/h1/dispatch.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h1/role.rs
src/proto/h2/client.rs
src/proto/h2/ping.rs
src/proto/h2/server.rs
src/server/conn.rs
tests/client.rs
tests/server.rs
tests/support/mod.rs

This removes the `runtime` cargo feature flag. 
Removing tokio as a opt-in runtime means the `common::exec::Exec::Default` variant will always panic. This should be refactored in a follow-up PR/issue, so that the user must always provide an executor (ref discussion in review comment). 
Closes #2857

feat(client, server): remove runtime cargo feature

---

.github/workflows/CI.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

.github/workflows/CI.yml
capi/README.md
src/ffi/mod.rs

Rust 1.64.0 stabilizes `cargo rustc --crate-type`, so hyper can use stable instead.

Use stable rust for building C API

---

src/server/server.rs
src/server/tcp.rs

According to https://en.wikipedia.org/wiki/Keepalive, TCP Keepalive has three parameters:
*  `Keepalive time` is the duration between two keepalive transmissions in idle condition. 
* `Keepalive interval` is the duration between two successive keepalive retransmissions, if acknowledgement to the previous keepalive transmission is not received.
* `Keepalive retry` is the number of retransmissions to be carried out before declaring that remote end is not available.
Currently, however, only the first  parameter `Keepalive time` is configurable in hyper.
This CR is a proposed enhancement for a backward compatible change on the `0.14.x` branch so that all the three TCP Keepalive parameters would become configurable.
FYI per empirical evidence enabling TCP keepalive with `intervals` and …

Supports configuration of all TCP Keepalive parameters per https://en.wikipedia.org/wiki/Keepalive

---

src/server/conn/http1.rs
src/server/conn/http2.rs
src/server/conn/mod.rs

This creates submodules of `hyper::server::conn` for HTTP/1 and HTTP/2. Each module contains a `Builder` and `Connection`, with options and methods specific to their version.
This takes over what was started in #2996.

feat(server): `server::conn::http1` and `server::conn::http2` modules

---

src/body/body.rs
src/body/mod.rs
src/error.rs
src/server/conn/http1.rs

In the recent work to split the `server::conn::Http` into protocol-specific halves, the author of that change left the inner `proto` in an `Option` (and left a comment asking if this was needed any more).  This used to be needed as part of the fallback processing (allowing the fallback to `take()` the HTTP/1 `proto` and break it into `Parts` in order to rebuild the HTTP/2 `proto`).
Now, since we're definitely using HTTP/1 we can just store the `proto` directly and, in the process delete a bunch of `unwrap` calls 💯.  We need to be able to `take` the HTTP/1 `Connection` in a few places (when an `UpgradeableConnection` is upgraded for example) but we can scope down the places where we have to `unwrap` an `Option` that's _almost always_ `Some`.
I also tidied up a few instances of dead code …

server::conn::http1::Connection always holds a proto

---

examples/echo.rs
examples/hello.rs
examples/http_proxy.rs
examples/multi_server.rs
examples/params.rs
examples/send_file.rs
examples/service_struct_impl.rs
examples/upgrades.rs
examples/web_api.rs
src/body/incoming.rs
src/body/mod.rs
src/client/conn/http1.rs
src/client/conn/http2.rs
src/client/dispatch.rs
src/ffi/body.rs
src/ffi/client.rs
src/ffi/http_types.rs
src/lib.rs
src/proto/h1/dispatch.rs
src/proto/h1/role.rs
src/proto/h2/client.rs
src/proto/h2/server.rs
src/server/conn/http1.rs
src/server/conn/http2.rs
src/server/conn/mod.rs
src/service/util.rs
tests/client.rs
tests/server.rs
tests/support/mod.rs

The concrete "recv stream" body type is renamed to `Incoming`.
Closes #2971

feat(body): rename `Recv` to `Incoming`

---

Cargo.toml
src/client/conn/http1.rs

feat(client): allow ignoring HTTP/1 invalid header lines in requests

---

src/server/tcp.rs

fix(server): fix compile-time cfgs for TCP keepalive options

---

src/proto/h2/client.rs

There exists a race condition in ClientTask::poll() when the request that is sent via h2::client::send_request() is pending open. A task will be spawned to wait for send capacity on the sendstream. Because this same stream is also stored in the pending member of h2::client::SendRequest the next iteration of the poll() loop can call poll_ready() and call wait_send() on the same stream passed into the spawned task.
Fix this by always calling poll_ready() after send_request(). If this call to poll_ready() returns Pending save the necessary context in ClientTask and only spawn the task that will eventually resolve to the response after poll_ready() returns Ok.

fix(server): Fix race condition in client dispatcher (#2419)

---

src/proto/h2/client.rs

This cherry-picks the fix for the HTTP/2 concurrency race condition from #3041.

Cherry-pick 3041 to master

---

tests/client.rs

This is a part of https://github.com/hyperium/hyper/issues/1675 issue. It
slightly reduces the number of duplicated code by using one common function for
init a logger and creating a test server.

refactor(test):#1675 use fns for creating test server

---

examples/echo.rs

While I was working on the hyper website server echo guide, I noticed this endpoint in the echo example is still disabled (by me :smile:). I was able to re-enable it and it does what it's supposed to, but I'm not sure if this is the idiomatic way to do it now. 
I looked around for another example (or test) for how to do this, but struggled to find something that matched the full flow (get body from request, mutate it without collecting it and return it in a response).

feat(examples): re-enable echo uppercase endpoint

---

tests/server.rs

This is a continuation of work on #1675 issue. It slightly reduces the number of duplicated code by using one common function for init a logger and creating tcp listener for tests.

refactor(test): use setup fns for logger/listeners

---

benches/support/tokiort.rs
src/common/mod.rs
src/common/time.rs
src/proto/h1/role.rs
src/proto/h2/ping.rs
src/rt.rs

This both avoids an unnecessary extra layer of boxing and removes some dubious unsafe code.
Closes #3028

refactor(rt): Clean up Timer trait

---

src/server/conn/http2.rs

Gets rid of `Builder::with_executor` as it's already provided in `Builder::new`.
Closes #3087

Remove `server::http2::Builder::with_executor`

---

src/client/conn/http1.rs

This PR contains 2 changes:
1. style has been formatted by `cargo fmt` in `src/client/conn/http1.rs`, which I think it's fine.
2. change `HTTP2` to `HTTP1` in docs of `hyper::client::conn::http1::Builder::executor`.
Closes #3086

Correct the docs of `hyper::client::conn::http1::Builder::executor`

---

src/server/server.rs

fix incomplete changes introduced from #2828

fix(h2): add http2_max_header_list_size to hyper::server::Builder

---

src/client/conn/http1.rs
src/client/conn/http2.rs
src/server/conn/http1.rs
src/server/conn/http2.rs

Remove feature gates on methods where the parent module is already gated on said Cargo feature. These gates seem to be leftovers from the split of connection builders into per-http-version modules.
Since the `client::conn::http1` and `server::conn::http1` modules are gated on the `http1` feature, we can remove `http1` gates within those modules.
Likewise for `client::conn::http2`, `server::conn::http2`, and the `http2` feature.

style(client, server): Remove redundant http1, http2 feature gates

---

.github/workflows/CI.yml
.github/workflows/bench.yml

Old versions of `actions/checkout` use node runtime versions that are deprecated on GitHub's runners. These versions also use deprecated environment variable setting syntax. These two problems combine to produce a lot of warnings that clutter CI output ([example here](https://github.com/hyperium/hyper/actions/runs/3752937788)).

chore(ci): upgrade actions/checkout to latest major version

---

Cargo.toml

This is no longer needed since https://github.com/hyperium/hyper/pull/2929 landed (and then https://github.com/hyperium/hyper/pull/2949 really burned the forest) - this change saves 4 crates from the build.
The other (non-`dev`) crates reported by `cargo udeps` are harder to eliminate:
* `httpdate` used by `server AND (http1 OR http2)`
* `want` used by `client AND (http1 OR http2)`
* `tracing` used by `http1 OR http2`
Requirements of the form `A AND (B OR C)` are unrepresentable perfectly in `Cargo.toml` even with the new features syntax but we might be able to do something sensible here.  If it's a reasonable assumption that `(http1 OR http2)` is logically always true (since hyper is pretty nerfed without at least one of these) then we could make `server` depend on `httpdate` and …

Remove unused `dev-dependency` on `pnet_datalink`

---

.github/workflows/CI.yml
.github/workflows/bench.yml

The @actions-rs GitHub org as a whole is unmaintained, and actions from this org will start failing around July 2023 due to [planned](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) [deprecations](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) announced by GitHub. This PR replaces the `actions-rs/toolchain` action with [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), which is actively maintained and provides the same features.
A quick look at the CI timings shows no regressions in Rust toolchain install time.

chore(ci): replace unmaintained actions-rs/toolchain action

---

examples/http_proxy.rs
src/client/conn/http1.rs
src/client/conn/http2.rs
src/ext.rs
src/ffi/client.rs
src/server/conn/http1.rs
src/server/conn/http2.rs
src/server/conn/mod.rs
tests/client.rs
tests/server.rs

Fixes #3085 
Should I also change thet non-public methods in `proto::h1::conn`?
- `set_http1_header_read_timeout`
- `set_h1_parser_config`

Remove version specific prefixes from builders

---

Cargo.toml

The `__internal_happy_eyeballs_tests` feature is not used anywhere within this repo, now that the[ `client::connect` module lives in `hyper-util`](https://github.com/hyperium/hyper-util/blob/0e0591e32532b27311d3cc04c33b9515abfb76fa/src/client/connect/http.rs#L881). So, let's remove the feature declaration from `Cargo.toml`.

chore(ci): remove unused __internal_happy_eyeballs_tests feature

---

src/client/conn/http1.rs
src/ffi/client.rs
src/server/conn/http1.rs
tests/server.rs

HTTP/2 needs to spawn internal tasks in order to process each stream separately, but HTTP/1 does everything in one task and thus doesn't need access to an executor.  This unused field seems to have been hidden from the linter because it was marked `pub(super)` so I've removed the same visibility marker on the server side's `timer` field.
This overlaps a little with https://github.com/hyperium/hyper/issues/3017 since (at least for HTTP/1) there's no need to name the types of futures that need to be spawnable.

HTTP/1 doesn't need an executor

---

benches/end_to_end.rs
benches/support/mod.rs

Most of #2930. The parallel HTTP/1 requests, and the chunk bodies, are still disabled.

test(benches): re-enable end_to_end benchmarks

---

benches/end_to_end.rs
src/client/conn/http2.rs
src/common/exec.rs
src/ffi/client.rs
tests/client.rs
tests/server.rs
tests/support/mod.rs

Closes #3128 
This PR removes `Exec::Default` so that we avoid panicking by asking users to provide Executor right away. `Exec::Default` serves no purpose after #2975.
Also refactors `hyper::client::conn::Http2::Builder::new` as part of the removal.

feat(client): remove `common::Exec::Default`

---

src/common/exec.rs
src/proto/h2/server.rs
src/rt/bounds.rs
src/rt/mod.rs
src/server/conn/http2.rs
src/service/mod.rs

Resolves #2051, resolves #3097 
- Moved, sealed, renamed `ConnStreamExec` to `Http2ConnExec` and made it public.
- Changed `pub(super)` restriction of `HttpService` to `pub`.

Make private traits in public api, sealed and public

---

src/proto/h1/conn.rs
tests/server.rs

Backport 0.14.x: prevent sending 100-continue if user drops request body

---

src/client/conn/http1.rs
src/client/conn/http2.rs
src/client/dispatch.rs

These were private in 0.14, used by the Pool to know whether it could checkout a connection. It seems fine to make them public, other channel-like things have similar functions. For instance, Tokio's MPSC `Sender` has `is_closed()`.

feat(client): add `is_ready()` and `is_closed()` methods to `SendRequest`

---

src/client/client.rs
src/client/connect/mod.rs

Add `poison` method to `Connected`. This allows callers to mark a connection as poisoned which prevents the pool from reusing it on subsequent requests. `is_open` will consider poisoning prior to returning a connection to the pool.

feat(client): add poison to Connected

---

src/client/client.rs
src/client/connect/mod.rs
tests/client.rs

Add `capture_connection` functionality. This allows callers to retrieve the `Connected` struct of the connection that was used internally by Hyper. This is in service of https://github.com/hyperium/hyper/issues/2605.
This pairs with a coming PR that adds a `poison` API to `Connected` — the pair of these APIs makes it possible to avoid reusing connections that the client deems to be bad.
Example usage:
```rust
use hyper::client::connect::{capture_connection, CaptureConnection};
let mut request = http::Request::builder()
.uri("http://foo.com")
.body(())
.unwrap();
let captured_connection = capture_connection(&mut request);
let client = hyper::Client::new();
// success or failure, it will still work fine.
let _ = client.request(request).await;
let connection_info = …
```

feat(client): add capture_connection

---

examples/hello.rs

This PR adds comments to the `hello.rs` example. This came out of some discussion I had with @seanmonstar.

Add comments to the examples/hello.rs example

---

.github/workflows/CI.yml
Cargo.toml
src/client/conn.rs
src/client/conn/http1.rs
src/client/conn/http2.rs
src/client/dispatch.rs
tests/client.rs

This patch backports client/conn/http1 and http2 modules from 1.0 to ease transition. It allows code still using 0.14.x to switch to the per-version Connection types available in 1.0.
Updating (part of) #3063

feat(client): add 1.0 compatible client conn API

---

Cargo.toml
examples/tower_client.rs
src/client/client.rs
src/client/conn.rs
src/client/service.rs
src/ffi/client.rs
tests/client.rs
tests/server.rs

Splitting up #3063, this includes just the deprecated stuff. It builds off #3155, so that must merge first.

feat(client): deprecate client::conn::{Builder, handshake}

---

src/client/conn.rs
src/server/conn.rs

Unpin require Box::pin, I think it's redundant
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c929314c2abaebffd7bd079863047f55

Remove redundant Unpin 'static constraint

---

src/server/conn.rs
src/server/server.rs
tests/server.rs

This is based on https://github.com/hyperium/hyper/pull/3102 which needs to be merged before this.
I had some difficulty with deprecations inside the `pin-project-lite` macros, it doesn't seem to be possible to set `#[cfg_attr(feature = "deprecated", allow(deprecated))]`on the fields of a struct inside `pin_project!`. That `server::conn::Connection` is inside `pin_project!` makes it difficult to deprecate as well. :thinking: I'll need to come back to this tomorrow. For example, in `hyper/server/server.rs`:
```rust
pin_project! {
/// A listening HTTP server that accepts connections in both HTTP1 and HTTP2 by default.
///
/// `Server` is a `Future` mapping a bound listener with a set of service
/// handlers. It is built using the [`Builder`](Builder), and the future
/// completes when the …
```

feat(server): deprecate server conn structs

---

src/server/mod.rs
src/server/server.rs

This adds the allow(deprecated) to the server module, since adding it to the server struct won't apply correctly due to it being wrapped in `pin_project!`.

Fix(server): server deprecation warnings

---

.github/workflows/CI.yml
Cargo.toml

That leaves only two places where the MSRV needs to be updated.

Get the MSRV for the build job from the package metadata

---

Cargo.toml

socket2 seems not to be used now.

chore: Remove unused dependency

---

src/ffi/task.rs

This reverts commit 187b8f2af984da78b84c28c94b900f16fedf90d8. It changed the generation of the `hyper.h` file.
cc @LegionMammal978

Revert "fix(ffi): add `repr(transparent)` to `hyper_context` (#3191)"

---

examples/gateway.rs

Hello,
I have found the typo in the example.

style(examples): fix typo

---

.github/workflows/CI.yml

- Replaces actions actions-rs/cargo with run. As it is unmaintained, it warns `Node.js 12 actions are deprecated.`
- Uses taiki-e/install-action, which installs tools without building them and taiki-e/cache-cargo-install-action, which caches the built binaries. These actions saves ci time to install tools.

chore(ci): replace actions-rs with run and use taiki-e/install-action or taiki-e/cache-cargo-install-action

---

src/rt/mod.rs

Copy pasting the tokio executor example doesn't work because the struct doesn't implement clone. This PR adds `#[derive(Clone)]` to the example.

docs(rt): fix executor example

---

src/rt/mod.rs

Make the purpose of `Executor` clearer by explaining why it is necessary.

docs(rt): make purpose of `Executor` trait clearer

---

examples/echo.rs

Updated echo example service root path instructions to work for Windows users out-of-the-box.
Tripped over this during some midnight coding 😵‍💫
I put this change through a full loop[^1] of testing on:
- macbook (apple silicon)
- pc (windows 10, x86_64)
- linux ([devcontainer.json](https://pastebin.com/9iF6KzRQ))
No regressions discovered.
If bypassing the reporting step was inappropriate, I will abandon this PR and create an issue accordingly 👍🏻 
[^1]: repeating the process pictured above

fix(example): change suggestion for windows compatability

---

examples/README.md

As discussed: #3099. This PR includes:
- updating dependencies to hyper 1.0
- linking to hyper 1.0 guides
- fixes for spelling and formatting
Copied every example into a fresh project and tallied all of the necessary dependencies. Then I referenced [hyper's toml file](https://github.com/hyperium/hyper/blob/master/Cargo.toml) and copied the master branch dependency versions.
Tested by dropping the new batch of dependencies into a freshly gen'd cargo project and copying in every example in turn and making sure it runs.
Tested on:
`rustc 1.69.0 (84c898d65 2023-04-16)`
Which now gives me pause in regard to MSRV 🤔. Perhaps not, since this is a version specific update.
I will make any necessary changes to this work to achieve the desired results 👍🏻

docs(examples): update dependencies (#3099)

---

examples/service_struct_impl.rs
src/service/service.rs
src/service/util.rs
tests/server.rs

change Service::call to take &self instead of &mut self. Because of this change, the trait bound in the service::util::service_fn and the trait bound in the impl for the ServiceFn struct were changed from FnMut to Fn. This change was decided on for the following reasons:
- It prepares the way for async fn, since then the future only borrows &self, and thus a Service can concurrently handle multiple outstanding requests at once.
- It's clearer that Services can likely be cloned
- To share state across clones you generally need Arc<Mutex<_>> that means you're not really using the &mut self and could do with a &self
This commit closses issue: #3040
BREAKING CHANGE: The Service::call function no longer takes a mutable reference to self. The FnMut trait bound on the service::util::service_fn …

refactor(service): change Service::call to take &self

---

Cargo.toml
src/body/incoming.rs
tests/client.rs

`hyper` has already used `futures-core` via `futures-util` at many places. We could reduce some costs to maintain dependencies by doing it consistently.

chore(dependencies): use futures-core via futures-util consistently

---

README.md
src/lib.rs

Updated all remaining incorrect guide links that I was able to find with ctrl+shift+f 👀.
At some point it will be appropriate to update the site to forward `/guide` to 1.0 instead of 0.14.
https://github.com/hyperium/hyperium.github.io/blob/c94a621c2b95a4a824194e20da031d8cf7f1ce05/_legacy/index.md?plain=1#L1-L7
... perhaps when 1.0 lands 🤔 
Always

fix(docs): update guide links

---

benches/support/tokiort.rs
src/rt/mod.rs
src/rt/timer.rs

closes #3027 
This pr adds a downcast for the `Sleep` trait.

feat: add downcast on `Sleep` trait

---

src/proto/h1/conn.rs
src/proto/h1/dispatch.rs
tests/server.rs

This is from #3233, I've fixed up the failing test.
---
fix issue in the graceful shutdown logic
which causes the connection future to hang
when graceful shutdown is called prior to any
requests being  made. This fix checks to see
if the connection is still in its initial state
when disable_keep_alive is called, and starts the
shutdown process if it is.
Closes #2730

fix(http1): http1 server graceful shutdown fix

---

examples/single_threaded.rs
src/client/conn/http1.rs
src/client/conn/http2.rs

I am sorry if i missed those in #3184

remove send bounds and add example also for http1

---

examples/single_threaded.rs

This is a follow up PR for #3266 adding some explanation.

Example docs

---

src/client/conn/http2.rs
src/server/conn/http2.rs

Hi, I've fixed the broken URL of the http2 specification.
Closes #3273

fix: update broken link to http2 spec

---

src/body/incoming.rs
src/proto/mod.rs
tests/client.rs

Closes #2872
Added test is failing against the current version (before this fix)
Backport for `0.14.x`: https://github.com/hyperium/hyper/pull/3274

fix(client): early server response shouldn't propagate NO_ERROR

---

src/body/body.rs
src/proto/mod.rs
tests/client.rs

Closes #2872 for `0.14.x` version: **this is backport, see** #3275
Added test is failing against the current version (before the fix).

fix(0.14.x): early server response shouldn't propagate NO_ERROR

---

src/ffi/mod.rs
src/lib.rs

docs(ffi): add unstable feature flag to module in docsrs

---

src/client/client.rs
tests/integration.rs
tests/support/mod.rs

As per [RFC 8441](https://datatracker.ietf.org/doc/html/rfc8441#section-4):
> On requests that contain the :protocol pseudo-header field, the
:scheme and :path pseudo-header fields of the target URI (see
[Section 5](https://datatracker.ietf.org/doc/html/rfc8441#section-5)) MUST also be included.
I was trying to implement WebSocket handshake based on HTTP/2 Extended CONNECT. The current implementation crafted a request which was considered invalid by the server (HAProxy 2.8):
Compared to the [example](https://datatracker.ietf.org/doc/html/rfc8441#section-5.1) illustrated in RFC 8441, the pseudo headers `:scheme` and `:path` were missing.
After the fix, the client could successfully establish a WebSocket tunnel to the server.

fix(client): Do not strip `path` and `scheme` components from URIs for HTTP/2 Extended CONNECT requests

---

src/server/server.rs

Closes https://github.com/hyperium/hyper/issues/3272.

feat: add local addr getter to server builder

---

src/proto/h2/client.rs

This reworks http2 client connection task in order to avoid storing a `Select` future. Under some scheduling cases the future was polled multiple times, resulting in runtime panics:
```
thread 'main' panicked at 'cannot poll Select twice', /index.crates.io/futures-util-0.3.28/src/future/select.rs:112:42
stack backtrace:
[...]
5: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
6: <hyper::proto::h2::client::H2ClientFuture<B,T> as core::future::future::Future>::poll
[...]
```
Closes: https://github.com/hyperium/hyper/issues/3289

fix(http2/client): avoid double-polling a Select future

---

src/ext/h1_reason_phrase.rs
src/proto/h1/role.rs

This removes the `from_bytes_unchecked()` method, since it's utility seems dubious (we can always add back if it's badly needed). It also makes `from_static` a const fn.

ReasonPhrase Polish

---

src/body/mod.rs

docs(body): reference http-body-util for more implementations

---

capi/include/hyper.h
src/ffi/body.rs
src/ffi/client.rs
src/ffi/error.rs
src/ffi/http_types.rs
src/ffi/io.rs
src/ffi/task.rs

When using the C API for the first time I found the documentation missing some important details.

Clarify ownership responsibilities in the C API docs

---

Cargo.toml
examples/README.md
examples/graceful_shutdown.rs

I wanted to have graceful shutdown after a timeout in my server application.  There is not an existing example that does exactly this.
This is mostly the existing `hello.rs` example with graceful shutdown added.
Thanks!

Add graceful_shutdown example.

---

Cargo.toml

These dependencies seem not to be used.

chore(dependencies): Remove unused num_cpus and tokio-util dependencies

---

.github/workflows/CI.yml
.github/workflows/bench.yml

Updates to `actions/checkout@v4` from version 3.

chore(ci): Update to actions/checkout@v4

---

src/error.rs
tests/client.rs
tests/server.rs

hyper's `Error` used to print the error source automatically, preferring to provide a better default for users who do not know about `Report`. But, to fit better with the wider ecosystem, this changes the format to only print the hyper `Error` itself, and not its source.
Closes #2844
BREAKING CHANGE: The format no longer prints the error chain. Be sure to
check if you are logging errors directly.
The `Error::message()` method is removed, it is no longer needed.
The `Error::into_cause()` method is removed.

feat(error): change `Display for Error` to only print top error

---

Cargo.toml
tests/client.rs

Replaces `matches` crate with std `assert` and `matches` macro.

chore: Replace matches crate with std assert and matches macro

---

src/error.rs

Document that the exact types returned in the erased errors of `Error::source()` may change at any moment, and cannot be depended on.
Closes #2843
BREAKING CHANGE: Do not build any logic depending on the exact types of
an `Error::source()`. They are only for debugging.

feat(error): `Error::source()` is purposefully unspecified

---

Cargo.toml

Allows users to use `socket2` 0.5 version. When users want to use `tokio` which version is larger than 1.30, as it starts to use `socket2` 0.5, users depend on multiple versions of `socket2`, 0.4 and 0.5. According to the [changelog](https://github.com/rust-lang/socket2/blob/v0.5/CHANGELOG.md#050), as `hyper` 0.14 seems not to be affected by the `socket2`'s breaking changes, `hyper` might be able to allow users to use `socket2` 0.5.

chore(dependencies): Allow socket2 0.5

---

.github/workflows/CI.yml
.github/workflows/external-types.toml

This adds CI job that runs `cargo-check-external-types` against a whitelist of exported types.
Whitelist in https://github.com/hyperium/hyper/issues/2925#issuecomment-1362473727 didn't change.
For now the nightly for this needs to be pinned to `nightly-2022-11-16`, because `cargo-check-external-types` doesn't work with the latest nightly json doc format.
Resolves #2925
Superseeds #2957

feat(CI): check external types

---

Cargo.toml

`httpdate` and `want` are used in some combinations of features. Although Cargo does not provide such a combined features configuration, the scopes could be reduced.

chore(dependencies): reduce default dependencies

---

src/server/conn/http1.rs
src/server/conn/http2.rs
src/server/conn/mod.rs
src/service/service.rs

This PR aims to address some of the tasks in https://github.com/hyperium/hyper/issues/3067, specifically:
> conn module: mention hyper-util providing an AutoConnection and builder
>  struct conn::http1::Connection: Explain that this is returned from Builder::serve_connection, and that it is essential an impl Future that must be polled (or awaited) for anything to happen.
The change in service is to make it an automatic link, which was suggested by cargo doc.
The changes have been tested by running `cargo doc --features "server,http1,client,http2" --open` and inspecting the docs.
Feedback on phrasing or if anything should be expanded on is most welcome!

docs(server): polish server connection docs

---

.github/workflows/CI.yml

- Updates to `actions/checkout@v4` from version 3.
- Replaces `actions-rs/install` with `taiki-e/cache-cargo-install-action` as the former is not maintained and throws warnings.

chore(ci): update ci config

---

.github/workflows/CI.yml
Cargo.toml
src/body/length.rs
src/client/conn/http1.rs
src/client/conn/http2.rs
src/client/dispatch.rs
src/lib.rs
src/proto/h1/conn.rs
src/proto/h1/decode.rs
src/proto/h1/dispatch.rs
src/proto/h1/encode.rs
src/proto/h1/io.rs
src/proto/h1/role.rs
src/proto/h2/client.rs
src/proto/h2/mod.rs
src/proto/h2/ping.rs
src/proto/h2/server.rs
src/trace.rs
src/upgrade.rs

This change allow users to opt out of tracing via the `tracing` crate by adding tracing as an optional feature. This change is part of the effort, outlined in #2874, to reach hyper 1.0.
Closes #3319
BREAKING CHANGES: tracing is disabled by default and requires users to opt in to revert to previous behavior.

feat(upgrade): introduce tracing as an optional unstable feature

---

Cargo.toml
src/error.rs

As `hyper::error::Parse` is a private type, `httparse` crate seems to be only used in http1 feature actually. Therefore `httparse` might be able to be moved to http1 feature.

chore(dependencies): move httparse to http1 feature

---

benches/support/tokiort.rs
src/rt/timer.rs

`std::future::Future` could be used at these places.

refactor(ext): replace futures_util::Future with std::future::Future

---

.github/workflows/CI.yml

`cargo-hack` has `--no-dev-deps` option to check without dev-dependencies. As this does not require nightly Rust version, the features checks are allowed to be performed with stable Rust by using this instead of `-Z avoid-dev-deps`.

chore(ci): use cargo-hack --no-dev-deps option to check without dev-dependencies

---

.github/workflows/CI.yml
src/body/length.rs
src/body/mod.rs
src/client/dispatch.rs
src/common/buf.rs
src/common/io/mod.rs
src/common/mod.rs
src/common/task.rs
src/common/time.rs
src/error.rs
src/ext/h1_reason_phrase.rs
src/ext/mod.rs
src/headers.rs
src/proto/h1/conn.rs
src/proto/h1/dispatch.rs
src/proto/h1/role.rs
src/proto/mod.rs
src/rt/io.rs
src/server/conn/http1.rs
src/server/conn/http2.rs
src/upgrade.rs

Adds `cfg` feature attributes to resolve unused warnings, which occur in each features and the combinations, and ci config to check `unused_imports` and `dead_code`.

refactor: resolve unused warning

---

Cargo.toml

This is for `tokio::sync::watch::Sender::send_replace` as introduced in https://github.com/tokio-rs/tokio/commit/dee3236c97b5502290046b9d677e108089188a9e and fixes https://github.com/hyperium/hyper/issues/3195

Upgrade minimum tokio to 1.13

---

src/client/connect/http.rs

Consider addrs length is 0.
From issue: seanmonstar/reqwest#2003

fix(http): divide by zero error when dividing duration by scalar

---

src/client/pool.rs

From issue: https://github.com/hyperium/hyper/issues/2997
Test Example:
```rust
#![deny(warnings)]
#![warn(rust_2018_idioms)]
use hyper::body::Buf;
use serde::Deserialize;
// A simple type alias so as to DRY.
type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;
#[tokio::main]
async fn main() -> Result<()> {
let url = "http://jsonplaceholder.typicode.com/users".parse().unwrap();
let users = fetch_json(url).await?;
// print users
println!("users: {:#?}", users);
// print the sum of ids
let sum = users.iter().fold(0, |acc, user| acc + user.id);
println!("sum of ids: {}", sum);
Ok(())
}
async fn fetch_json(url: hyper::Uri) -> Result<Vec<User>> {
let client = hyper::client::Builder::default()
.pool_idle_timeout(Some(std::time::Duration::ZERO)) …
```

fix(client): panic when pool idle timeout set to zero

---

src/common/io/rewind.rs
src/proto/h1/role.rs

Remove outdated FIXME comments, and resolve FIXME regarding usage of `MaybeUninit`.
Since hyper's MSRV is higher now, we can use some new stabilized apis. I also removed some `unsafe` blocks related to `MaybeUninit` usage.

refactor(lib): resolve FIXME messages

---

src/proto/h2/server.rs
src/server/conn/http2.rs

Closes #3358 
BREAKING CHANGE: This is a behavioral change. Consider setting your own
maximum.

fix(http2): change default server max concurrent streams to 200

---

src/client/conn/http1.rs
src/client/conn/http2.rs
src/server/conn/http1.rs
src/server/conn/http2.rs

docs(client,server): added note about stability of Builder struct default options

---

src/common/io/compat.rs
src/common/io/mod.rs
src/common/io/rewind.rs
src/proto/h1/decode.rs
src/proto/h1/dispatch.rs
src/proto/h1/io.rs
src/proto/h2/client.rs
src/proto/h2/server.rs

This is a small refactoring. The constructor of `Compat` has been defined as a independent function, `compat`. As its name is the same of the module name `compat`, which the constructor function belongs to, it seems a little bit complicating. Moving it to the method reduces the re-export of the function as well. It might slightly improve readability.

refactor(common): move compat constructor to method

---

Cargo.toml

This is required to use HeaderName::from_static in a const.
Without this, I was getting the following error:
```
RUSTFLAGS="--cfg hyper_unstable_ffi" cargo rustc --features client,http1,http2,ffi --crate-type cdylib
...
error[E0015]: cannot call non-const fn `http::header::HeaderName::from_static` in constants
--> src/proto/h2/mod.rs:39:5
|
39 |     HeaderName::from_static("keep-alive"),
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: calls in constants are limited to constant functions, tuple structs and tuple variants
error[E0015]: cannot call non-const fn `http::header::HeaderName::from_static` in constants
--> src/proto/h2/mod.rs:40:5
|
40 |     HeaderName::from_static("proxy-connection"),
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: calls in constants are limited …
```

Update http dep to 0.2.7

---

examples/single_threaded.rs
examples/upgrades.rs
src/client/conn/http1.rs

This removes the requirement of the IO type from being `Send` for the HTTP/1 client connection. To do so, the ability to perform `hyper::upgrade`s had to be moved to a separate type which does require the `Send` bound. This mirrors how the server types do it.
The `Connection` type now has a `with_upgrades()` method to convert.
Closes #3363
BREAKING CHANGE: If you use client HTTP/1 upgrades, you must call
`Connection::with_upgrades()` to still work the same.

feat(client): allow `!Send` IO with HTTP/1 client

---

Cargo.toml
examples/params.rs

As `hyper`'s example uses `url` crate just for the re-exported `form_urlencoded`, seems to be able to use it directly.

chore(dependencies): use form_urlencoded crate directly

---

Cargo.toml

`futures-util`'s `alloc` feature seems not to be used.

chore(dependencies): disable unused futures-util alloc feature

---

src/proto/h2/ping.rs

close #3380
rely on https://pkg.go.dev/google.golang.org/grpc/keepalive
server-side will output `too many pings`

ping: eliminates unnecessary ping when the connection is idle.

---

src/client/connect/mod.rs
tests/support/mod.rs

Fixes the lint errors for the nightly Rust, which occurred in #3384.

chore(lib): fix lint error

---

.github/workflows/CI.yml
src/client/client.rs
src/client/conn.rs
src/client/conn/http1.rs
src/client/conn/http2.rs
src/client/connect/dns.rs
src/client/connect/http.rs
src/client/connect/mod.rs
src/headers.rs
src/proto/h1/decode.rs
src/proto/h1/dispatch.rs
src/proto/h2/mod.rs
src/proto/h2/ping.rs
src/proto/h2/server.rs
src/server/tcp.rs

This backports cargo fmt workaround #3255.

style(lib): cargo fmt cfg workaround

---

.github/workflows/CI.yml

Sets rustfmt edition config to 2018 used by `hyper`.

chore(ci): fix rustfmt edition to 2018

---

src/server/conn/http1.rs

This should resolve
> struct `conn::http1::Builder`: Provide an example constructing one and setting some options.
in https://github.com/hyperium/hyper/issues/3067

docs(server): add conn::http1::Builder example

---

Cargo.toml

tower_client example seems to require backports feature.

fix(examples): add backports feature requirement to tower_client example

---

CONTRIBUTING.md

closed #3387
relyed on https://rust-analyzer.github.io/manual.html#features

(contributing.md): add a comment to make good use of `rust-analyzer`

---

src/common/time.rs
src/server/conn/http1.rs

If a default timeout is set, and no Timer, a warning will be emitted.
If a timeout is configured by the user, and no Timer is set, it will panic.
Closes #3393

feat(lib): missing Timer will warn or panic

---

src/server/conn/http1.rs

Default the header read timeout to 30 seconds.
This depends on #3394 merging.
cc @82marbag

feat(server): default http1 header_read_timeout to 30 seconds

---

src/client/conn/http2.rs
src/proto/h2/client.rs
src/proto/h2/server.rs
src/rt/bounds.rs
src/server/conn/http2.rs

As I was adding docs, I realized these had inconsistent names. Worth making them consistent now.
BREAKING CHANGE: (From previous RCs) `ExecutorClient` is renamed to
`Http2ClientConnExec`, and `Http2ConnExec` is renamed to
`Http2ServerConnExec`.

feat(rt): rename to `Http2ClientConnExec` and `Http2ServerConnExec`

---

Cargo.toml
src/ffi/http_types.rs
src/ffi/mod.rs
src/upgrade.rs
tests/client.rs

Updates dependencies `http` and `http-body` to 1.0.
To do so, implements `Clone` for `OnUpgrade`.
BREAKING CHANGE: Upgrade to `http` 1.0.

feat(lib): update to `http` 1.0

---

.github/workflows/CI.yml
Cargo.toml

This pull request reverts #3345. #3195 is about 0.14.25 and `tokio::sync::watch::Sender::send_replace` seems not to be used in this branch.

chore(dependencies): relax minimum tokio version to 1

---

src/rt/io.rs

Implement Read/Write for Pin<P>

---

src/rt/io.rs

Needed when interfacing with std::io APIs like in hyper-openssl: https://github.com/sfackler/hyper-openssl/blob/2ca0514a5903bd52c402d16f80117efc4f4b3841/src/lib.rs#L57

Make ReadBuf::new public

---

capi/gen_header.sh

I've tested with 1.73 and the script now works on stable.
Also, added instructions to install requirements.

capi: updated comments in gen_header.sh

---

src/client/conn/http1.rs

in `client::conn::http1::Connection` the method `poll_without_shutdown` references `without_shutdown` in its documentation, but the method `without_shutdown` is not present in the code. This PR copies `without_shutdown` from hyper `0.14.x`: https://github.com/hyperium/hyper/blob/0.14.x/src/client/conn.rs#L520-L528

fix(client): add missing without_shutdown method

---

Cargo.toml
examples/send_file.rs

This is to show what I have wrote so far. It does not compile in the current state.
This addresses issues #3432

Improved send_file.rs example to use streaming.

---

examples/http_proxy.rs

Just nits, I think it makes it slightly better.

(nit) Update http_proxy example to use (host, port) pair as addr

---

benches/support/tokiort.rs

I was going through the `tokiort` module and noticed that the `TokioTimeout` struct was not used anywhere anymore.

refactor(common): Remove unused TokioTimeout

---

src/server/conn/http1.rs

Required to support graceful shutdown on hyper-util's "auto conn". More details here https://github.com/hyperium/hyper-util/pull/66

feat(server): expose `UpgradeableConnection`

---

Cargo.toml
src/body/incoming.rs
src/body/length.rs
src/body/mod.rs
src/common/mod.rs
src/common/watch.rs
src/error.rs

Removes the lint configs of allowing unused code, and adds features `cfg` attributes to them.

refactor(lib): remove lint config to allow unused code

---

.github/workflows/CI.yml

chore(ci): check tracing feature

---

src/proto/h1/conn.rs
src/proto/h1/dispatch.rs
src/proto/h1/encode.rs
src/proto/h1/role.rs
tests/client.rs
tests/server.rs
tests/support/mod.rs
tests/support/trailers.rs

feat(http1): Add support for writing Trailer Fields

---

src/proto/h1/role.rs

Fixes the compile error https://github.com/hyperium/hyper/actions/runs/7225810424/job/19690016477.

fix(proto): use HeaderMap type without client feature

---

src/common/mod.rs
src/common/task.rs

Reduces the redundant feature cfg.

refactor(common): move common feature cfg in common::task to common::mod

---

src/proto/h1/decode.rs

Previously, hyper would decode `\r\n\r\n` as `0\r\n\r\n`. This fixes hyper to require a digit to be present before starting at 0.
Reported-by: Ben Kallus <benjamin.p.kallus.gr@dartmouth.edu>

fix(http1): reject chunked headers missing a digit

---

src/proto/h1/decode.rs

The chunked transfer-encoding allows for extensions within the header of each chunk. hyper currently ignores the extension bytes. Sending large amounts of bytes in the extensions will waste CPU reaing and skipping them.
This change adds an internal limit to how many bytes will be read and ignored in a single body, before returning an error.
Reported-by: Bartek Nowotarski <bartek@nowotarski.info>

fix(http1): add internal limit for chunked extensions

---

src/proto/h1/decode.rs

0.14 backport chunked fixes

---

examples/service_struct_impl.rs

use share data in service

---

src/proto/h2/server.rs
src/server/conn/http2.rs

This PR is a partial reimplementation of @Noah-Kennedy's changes in #3201.
As described in hyperium/hyper#3461, `hyper` is missing the `max_pending_accept_reset_streams` added to `h2` in #3201. 
I essentially copy/pasted Noah's code, but not sure how to signal that he wrote the code in this PR. Not a git wizard, so if there's some way to remerge his changes from the original PR, I will close this.
~~Edit: Per the PR guidelines, happy to add tests for the existing configuration values to prevent this from re-occurring.~~
wouldn't have stopped this from happening 🤷, just lmk

h2: "readd" max_pending_accept_reset_streams configuration option

---

src/body/incoming.rs
src/client/conn/http1.rs
src/client/conn/http2.rs
src/common/mod.rs
src/lib.rs
src/proto/h1/conn.rs
src/proto/h1/decode.rs
src/proto/h1/dispatch.rs
src/proto/h1/io.rs
src/proto/h2/client.rs
src/proto/h2/mod.rs
src/proto/h2/server.rs
src/server/conn/http1.rs
src/server/conn/http2.rs

`hyper` seems to be able to use `futures_util::ready`, instead of defining `hyper`'s own `ready` macro.

refactor(common): replace hyper::common::ready with futures_util::ready

---

src/client/conn/http2.rs
src/proto/h2/client.rs

This adds `initial_max_send_streams` method to the HTTP/2 client builder.
The value set via this method will then be forwarded to [`h2::client::Builder::initial_max_send_streams`]. If not set, the default value defined in `h2` crate will be used in case some users might rely on this behavior. However, in the following version we plan to explicitly set `100` as a reasonable default value (see https://github.com/hyperium/h2/issues/731 for rationale on why this can be considered a reasonable value).
[`h2::client::Builder::initial_max_send_streams`]: https://docs.rs/h2/0.4.1/h2/client/struct.Builder.html#method.initial_max_send_streams

feat(http2): add `initial_max_send_streams` method to HTTP/2 client builder

---

Cargo.toml
src/proto/h2/server.rs
src/server/conn/http2.rs

chore(http2): pull 3528 up to master

---

Cargo.toml
src/lib.rs
src/proto/h2/server.rs
src/server/conn.rs
src/server/server.rs

This change exposes a tunable for the max_local_error_reset_streams parameter in h2.

feat(http2): add config for max_local_error_reset_streams in server

---

src/body/incoming.rs

After prodding from https://github.com/hyperium/hyper/issues/3015#issuecomment-1829333578, checking to see if this works now.

test(body): re-enable miri on a few channel tests

---

src/client/conn/http2.rs

fix simple typo in trace logging for http2 connection handshake.

fix(http2): typo in trace logging

---

Cargo.toml
benches/end_to_end.rs
src/ffi/body.rs

Our MSRV is already past when 2021 edition was introduced, so might as well. It gets us a the better resolver for dependencies.
Closes #3541

chore(lib): update to 2021 edition

---

Cargo.toml
src/client/conn/http1.rs
src/proto/h1/conn.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h1/role.rs
src/server/conn/http1.rs

Recently we encountered a problem when using `hyper`.
After the client sent the request, it received response `431 Request Header Fields Too Large`. After investigation, we found that `hyper` sets an upper limit on the number of `headers`, and this upper limit is a fixed and non-configurable value.
#3283 also encountered similar problems.
This PR sets `max_headers` to a configurable value. Its default value remains the same as the previous code, and we can set this value when needed.
Additionally, unit tests have been added and the current code passes.

feat(http1): support configurable `max_headers`

---

src/ext/h1_reason_phrase.rs
src/proto/h1/encode.rs
tests/client.rs
tests/server.rs

These traits are now part of the 2021 edition's prelude.

chore(lib): remove importing prelude trait in 2021 edition

---

src/error.rs

Resolves an unused trait error.

refactor(error): resolve unused trait error

---

.github/workflows/CI.yml

Updates to `cargo-check-external-types` 0.1.11.

chore(ci): update to cargo-check-external-types 0.1.11

---

src/common/io/rewind.rs
src/proto/h1/role.rs
src/upgrade.rs

This tweaks the request path parsing logic (in server role) in order to perform zero-copy URI parsing.
Closes: https://github.com/hyperium/hyper/issues/3574

proto/h1/server: avoid copy-allocation in request path parsing

---

src/client/conn/http2.rs
src/proto/h2/client.rs

This sets the default value of `initial_max_send_streams` to 100, which previously was `usize::MAX` as defined in [`h2` crate](https://github.com/hyperium/h2/blob/4ce59557b56943eb8b5d7dc45f97eda3f0ae0104/src/client.rs#L653).
This default value can be considered reasonable given that widely-used HTTP/2 client implementations adopt this value such as nghttp2 and Go's x/net/http2, and [the HTTP/2 spec recommends that HTTP/2 servers should set `MAX_CONCURRENT_STREAM` they advertise to clients to at least 100](https://www.rfc-editor.org/rfc/rfc9113.html#section-6.5.2-2.6.1). More details can be found at https://github.com/hyperium/h2/issues/731.
Continuation of #3524

fix(http2): `initial_max_send_streams` defaults to 100

---

src/server/conn/http1.rs

Part of https://github.com/hyperium/hyper/issues/3567
This PR adds more info on the documentation for `header_read_timeout` that it will panic when timeout is configured without timer.

chore(docs): add info on required timer for header_read_timeout

---

src/client/conn/mod.rs

replace client link in docs

---

src/client/conn/http1.rs
src/client/conn/http2.rs

`Client` no longer exists. This is similar to #3501.

Remove reference to Client in SendRequest::send_request

---

Cargo.toml

chore(dependencies): enable futures-util/alloc for tests

---

src/server/conn/http1.rs
src/server/conn/http2.rs

I can't tell if this was intentional. hyper 0.14.x didn't have this requirement and as far as I can tell it's not actually needed.

feat: relax connection IO trait bounds

---

src/client/conn/http1.rs
src/server/conn/http1.rs
src/upgrade.rs

Uses `non_exhaustive` attribute instead of manual implementation.

refactor(lib): use non_exhaustive attribute

---

src/server/conn/http1.rs
tests/server.rs

Closes #3615
Added test which fails without these changes

fix: avoid panic when calling `graceful_shutdown` if H1 connection was upgraded

---

src/client/conn/http2.rs
src/proto/h2/client.rs

This PR exposes `max_pending_accept_reset_streams` option for `client`.
Necessary to support https://github.com/hyperium/tonic/pull/1670

feat(h2/client): add `max_pending_accept_reset_streams` option

---

src/server/conn/http1.rs

fix: avoid unwrapping for the `Future` impl of `UpgradeableConnection`

---

src/proto/h1/role.rs
tests/client.rs

Most request methods define a payload. If hyper detects that no body has been included, it will now include a `content-length: 0` header automatically.
It will not do this for methods that don't have defined payloads (GET, HEAD, and CONNECT).

fix(client): send content-length even with no body

---

src/service/mod.rs

Exposes `Service` and `HttpService` trait unconditionally.
refs:  #3590

feat(service): expose Service and HttpService trait unconditionally

---

src/proto/h1/encode.rs

When the "trailer" header was not found in the response, the debug message would say "attempted to encode trailers for non-chunked response". This was quite misleading as the response was chunked. We now include a better debug message that hints to the user that the "trailer" header was not specified.
When a chunked response contained a trailer header that did not match the header names specified in the "trailer" response header, there was no debug message to the user. We now include debug messages that tell the user if the header name is not allowed and if the header name was not specified in the "trailer" response header.

fix(http1): improve debug messages when sending trailers

---

src/proto/h2/mod.rs

This pull request addresses the incorrect handling of the `Trailer` header in HTTP/2 responses within the hyper project. According to RFC 9110 "HTTP Semantics", the `Trailer` header is not listed as a "hop-by-hop" header in section 7.6.1. [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html) specifies that a sender intending to generate one or more trailer fields in a message should use the `Trailer` header in the header section to indicate potential trailer fields, as mentioned in section 6.6.2.
The current implementation in hyper may result in unnecessary warnings for gRPC calls, as gRPC implementations, such as grpc-go, routinely use the `Trailer` header to indicate the presence of trailers after the response body. (See this behavior in [grpc-go's …

fix(http2): "Trailer" header should be allowed in HTTP/2 responses as per RFC 9110

---

examples/service_struct_impl.rs

There was a comment in the service_struct_impl.rs example indicating that the default match arm would somehow return a 404 and not increment the counter. This wasn't the case. That arm also had a redundant return.

Remove incorrect comment in example

---

benches/support/tokiort.rs
examples/hello.rs

The usage of TokioTimer in the example differs from how it would be used with the hyper-util crate.  When you try to use the code like you see in the example, it says the type is private, but it is clearly public in the source code of hyper-util.  After coming back to this months later, it seems that in hyper-util itself, the usage of `#[non_exhaustive]` makes the type unconstructable outside the crate, which necessitates using the ::new() method.

Fix confusing usage of TokioTimer in hello.rs example

---

src/body/incoming.rs
src/proto/h1/conn.rs
src/proto/h1/decode.rs
src/proto/h1/dispatch.rs
src/proto/h1/role.rs
tests/client.rs
tests/server.rs

Closes #2703
In https://github.com/hyperium/hyper/pull/3375 we were strict about sending trailers per RFC 7230. In this PR, I have been much more accepting of trailers. Is this the behavior we want?
Some questions:
- If the client does not send `TE: trailers` but the server sends trailer headers, should trailers be parsed and passed along?
- If the server does not include a `trailers: ...` header indicating which trailer headers are being returned, should trailers be parsed and passed along? I think this one is almost certainly "yes".
- If the server includes trailers with invalid header names, such as `Content-Length: 5`, should that still be parsed and passed along?

feat(http1): add support for receiving trailer fields

---

tests/client.rs

For https://github.com/hyperium/hyper/issues/3652.
In https://github.com/hyperium/hyper/pull/3647, I thought I tracked down the root cause of https://github.com/hyperium/hyper/issues/3652. However, with the help of @seanmonstar  in https://github.com/hyperium/hyper/issues/3652#issuecomment-2085359895 I realized that this was too forcefully terminating the connection even if things other than SendRequest were still alive. I also realized the original test case I wrote was just wrong and failed to properly reproduce the issue.
This adds a test that properly reproduces the issue. On my machine, it fails about 5% of the time:
```
1876 runs so far, 100 failures (94.94% pass rate). 95.197349ms avg, 1.097347435s max, 5.398457ms min
```
With further investigation, I believe this bug actually …

Add test for HTTP2 CONNECT termination

---

src/service/service.rs

simplifies the usage of `dyn Service`s and making `Service` types `Clone` by wrapping them in a `Rc`or `Arc`

forward implement Service for reference types

---

.github/workflows/CI.yml

Updates to the latest version of `cargo-check-external-types`.
https://github.com/awslabs/cargo-check-external-types/releases/tag/v0.1.12

chore: update to cargo-check-external-types 0.1.12

---

src/proto/h1/conn.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h1/role.rs
tests/server.rs

The `http1_header_read_timeout` used to start once there was a single read of headers. This change makes it start the timer immediately, right when the connection is estabilished.
Closes #3178 
cc @paolobarbolini @silence-coding @SylvainGarrigues

fix(server): start header read timeout immediately

---

src/client/conn/http1.rs

chore: fix some comments

---

src/client/conn/http2.rs

I just noticed that the `Http2ClientConnExec` argument is missing from the doc comment for `handshake`.

Include exec arg in client::conn::http2::handshake doc

---

src/client/conn/http2.rs
src/proto/h2/client.rs

This PR is created to raise the question if `Future` implementation on `Connection` is mandatory to request Executor to be `Send` + `Sync`.
Question initially raised here https://discord.com/channels/500028886025895936/670880858630258689/1247563996068970557.

Make Future implementation on Connection unconditional on executor being Send + Sync.

---

src/client/conn/http1.rs
src/client/conn/http2.rs
src/client/conn/mod.rs
src/client/dispatch.rs
src/proto/h1/dispatch.rs
src/proto/h2/client.rs
tests/client.rs

This change adds a `try_send_request()` method to `SendRequest`. This method returns a `TrySendError` type, which allows for returning the request back to the caller if an error occured between queuing and trying to write the request.
This method is added for both `http1` and `http2`.
Closes #3673 
Closes https://github.com/seanmonstar/reqwest/issues/2325
(Well, after hyper-util makes use of it.)
---
If you try to `send_request(req)` at the same time the server is closing the connection, it's possible hyper will notice the HUP before the request gets serialized. If so, theoretically the request is safe to try on another connection.
But there isn't a mechanism for hyper to give the request _back_. And since the pool was moved out of hyper, it doesn't know how to just grab another …

feat(client): add `SendRequest::try_send_request()` method

---

src/proto/h1/decode.rs
tests/server.rs

If a chunked body had valid chunks, but ended without a `0` in the final chunk (so, just `\r\n\r\n`), it would be parsed as a valid end. Now it will be rejected as the final chunk MUST be `0\r\n\r\n`.
This was partially done before (https://github.com/hyperium/hyper/pull/3494), but only if there were no chunks before the final. This fixes both paths.

fix(http1): reject final chunked if missing 0

---

src/rt/io.rs

There is currently no way to write to ReadBufCursor without unsafe code, even though writing a slice to it like one would do to a Buf shouldn't require unsafe code.

Expose ReadBufCursor::remaining and ReadBufCursor::put_slice

---

src/proto/h1/conn.rs
src/server/conn/http1.rs

`date_header` option is not work in http1 because the argument in `Builder` is forgotten to pass into the further connection object.

fix(http1): make `date_header` effective

---

src/client/conn/http2.rs
src/proto/h2/client.rs

Hmm, I noticed that hyper is missing some configuration options for http2 that apply to my scenario. If that makes sense, merged to the mainline branch? I thought there might be someone else who might need it

feat(client): Add more Http2 client settings options

---

src/client/conn/http1.rs
src/client/conn/http2.rs

When reading the documentation for `Connection` it is not entirely obvious how instances of this type are obtained. Add a helpful link, mostly for those less familiar.

docs: link from Connection to handshake

---

src/proto/h2/server.rs

Strip content-length header in response to HTTP/2 CONNECT requests

---

.github/workflows/CI.yml

Uses `tokio-util` 0.7.11 in msrv job.

chore(ci): use tokio-util 0.7.11 in msrv job

---

benches/pipeline.rs
benches/server.rs
src/proto/h1/conn.rs
tests/server.rs

fix(http1): send 'connection: close' during graceful shutdown

---

src/proto/h1/io.rs
src/proto/h1/role.rs

If request headers are received in incremental partial chunks, hyper would restart parsing each time. This is because the HTTP/1 parser is stateless, since the most common case is a full message and stateless parses faster.
However, if continuing to receive more partial chunks of the request, each subsequent full parse is slower and slower. Since partial parses is less common, we can store a little bit of state to improve performance in general.
Now, if a partial request is received, hyper will check for the end of the message quickly, and if not found, simply save the length to allow the next partial chunk to start its search from there. Only once the end is found will a fill parse happen.
This issue was reported by Datong Sun of Kong Inc.

perf(http1): improve parsing of sequentially partial messages

---

tests/client.rs

test(client): unflake client try_send_request unit test

---

src/lib.rs

I think this will make the docs clearer. Before this change, `HeaderMap` is separate as a re-export, and the other types all look native to hyper. This will show that most of the top level types in hyper are re-exports from `http`.

docs(lib): do not inline http rexports

---

src/proto/h2/server.rs

Needed for implementing tonic max_connection_age_ms .
- https://github.com/hyperium/tonic/issues/1428
Related PRs:
- https://github.com/hyperium/tonic/pull/1865

Change graceful_shutdown function behavior.

---

src/proto/h2/server.rs

The patch #3528 added the ability for hyper users to configure `max_local_error_reset_streams` via the server builder to hyper v0.14.29. It was then pulled in to hyper v1.2.0 as well in #3530, where the wrong parameter `max_pending_accept_reset_streams` is passed to h2's builder as `max_local_error_reset_streams`.
This could lead to significant impact especially when a hyper user does not set `max_pending_accept_reset_streams`, because its default value is `None` and passing `None` to h2's `max_local_error_reset_streams` method will make the server vulnerable to DOS attacks.
This issue has been fixed in this patch, simply by passing the correct value to the h2's builder method.
Note that the original patch merged into v0.14 does not suffer this problem.

fix(http2): pass proper value to h2 `max_local_error_reset_streams`

---

Cargo.toml
src/ffi/body.rs
src/ffi/client.rs
src/ffi/error.rs
src/ffi/http_types.rs
src/ffi/io.rs
src/ffi/mod.rs
src/ffi/task.rs

`hyper` uses `libc` in `ffi` feature for the C language's type aliases. As `hyper`'s `ffi` feature is an unstable feature, `hyper` could use these types via `std::ffi` which require Rust 1.64, except for `c_size_t` which is a nightly only API. As `libc::size_t` and `core::ffi::c_size_t` are both defined as `usize`, this type might be able to be defined as type alias in `hyper` until it stabilizes.

chore(dependencies): remove libc crate from dependencies

---

.github/workflows/CI.yml
Cargo.toml
capi/README.md

Probably doesn't fully work yet, but here's a start.
Closes #3786

feat(ffi): add cargo-c support

---

src/proto/h1/role.rs

fix: content length assertion for HEAD

---

src/server/conn/http2.rs

**NB:** this commit is based on the `0.14.x` release series.
the `server::conn::http2` submodule provides types that are conditionally compiled when the [`backports`](https://hyper.rs/guides/1/upgrading/) feature is active, to facilitate upgrading to the `1.x` release.
i've been working on upgrading the
[`linkerd2-proxy`](https://github.com/linkerd/linkerd2-proxy/) project to use hyper 1.0, but encountered a pertinent gap in `Builder<E>`'s interface when setting the `backports` and `deprecated` features.
this adds a `max_pending_accept_reset_streams(..)` method (_added in #3201_) to this builder, so that 0.14.x users relying on this functionality can prepare to upgrade to hyper 1.x safely.
this is effectively a backport of #3507, which restored this interface to the 1.0 release.
for more …

chore(server/conn): backport `max_pending_accept_reset_streams()`

---

.github/workflows/CI.yml
examples/hello-http2.rs
src/proto/h1/encode.rs
src/proto/h1/role.rs

Update tests that require the server feature to only be compiled when the feature is enabled. After updating these tests, the server feature is no longer required for the ffi job when running tests.
Closes #3790

fix(server): fix failing tests for server feature

---

capi/gen_header.sh

Fixes https://github.com/hyperium/hyper/issues/3708
Testing with `--verify` and without `--verify`.

chore: Only backup when passing --verify

---

benches/end_to_end.rs
benches/support/tokiort.rs
examples/client.rs
examples/gateway.rs
examples/http_proxy.rs
examples/single_threaded.rs
examples/upgrades.rs
examples/web_api.rs
src/ext/h1_reason_phrase.rs
src/proto/h1/decode.rs
src/proto/h1/dispatch.rs
src/proto/h1/encode.rs
src/proto/h1/io.rs
src/proto/h1/role.rs
src/proto/h2/ping.rs
src/proto/h2/server.rs
src/rt/io.rs
src/service/service.rs
tests/client.rs
tests/server.rs
tests/support/mod.rs

Tried to complete https://github.com/hyperium/hyper/issues/3802 as well as possible.
This PR wants to reduce some Clippy warnings that worth fixing.  Almost all of the changes are based on clippy prompts. And passed the MSRV 1.63 test.
Some of the warnings have not changed, mainly based on Clippy's false positives, and some clippy rules are newer than the current MSRV 1.63.
Needs downgrade some crate versions to run on MSRV 1.63.
```
cargo update tokio --precise 1.38.1 
cargo update tokio-util --precise 0.7.11
cargo update hashbrown --precise 0.15.0
cargo update regex --precise 1.9.6
cargo update async-stream --precise 0.3.5
cargo update tokio-stream --precise 0.1.15
```
Run `cargo +1.63-x86_64-unknown-linux-gnu  clippy --workspace --no-deps --all-targets --features="full"  -- -D …

refactor(clippy): Reduce some Clippy warnings

---

Cargo.toml

1. Open this project in vs code. 
2. Open `benches/support/tokiort.rs`, check error report by IDE at:
https://github.com/hyperium/hyper/blob/0bd4adfed2bf40dda6867260ded05542d5b921c5/benches/support/tokiort.rs#L11

fix pin-project-lite not found error in vs code.

---

docs/ROADMAP-1.0.md
docs/ROADMAP.md

This updates the ROADMAP, since much of what was previously in it was accomplished in the v1 work. For now, it archives the previous roadmap too. That does make the diff look weird, but really the previous file was just renamed, and the new one is in the original file. So, while it looks like all in `ROADMAP-1.0.md` is new, it's just a rename. The [rendered version](https://github.com/hyperium/hyper/blob/roadmap-next/docs/ROADMAP.md) may be more useful to look at.
---
Uplifting the summary:
> ## Goal
> 
> Align current hyper to the [hyper VISION][VISION].
> 
> The VISION outlines a decision-making framework, use-cases, and general shape
> of hyper. This roadmap describes the focus areas to continue to improve hyper
> to look more like what is in the VISION.
> 
> ## Focus Areas
> 
> While …

ROADMAP post v1.0

---

src/proto/h1/io.rs
tests/client.rs

Backport 0.14: fix intermitent panic parsing partial headers

---

CHANGELOG.md
Cargo.toml

While it has a feature, it's for the unstable FFI, so I don't think I count it as part of semver.

Prepare v1.5.2

---

src/server/conn/http2.rs

currently, dependents of hyper 0.14 that enable the `server` and `http2` feature flags will see an error if they enable the `backports` flag.
building hyper like so...
```sh
cargo check --features server,http2,backports
```
...will yield the following errors (shown in "short" format here for brevity):
```text
src/server/conn.rs:75:9: warning: unused import: `tracing::trace`
src/server/conn/http2.rs:185:25: error[E0609]: no field `keep_alive_interval` on type `h2::server::Config`
src/server/conn/http2.rs:199:25: error[E0609]: no field `keep_alive_timeout` on type `h2::server::Config`
warning: `hyper` (lib) generated 1 warning
error: could not compile `hyper` (lib) due to 2 previous errors; 1 warning emitted
```
this stems from the fact that the deprecated connection builder …

fix(http2): gate server `Builder` keep-alive interfaces

---

src/server/conn/http2.rs

This PR fixes an inconsistency with the HTTP/2 builder, which I assume was unintentional. This is a breaking change. Hopefully it counts as acceptable breakage.
I searched and only found one public, non-fork user of `max_local_error_reset_streams` on GitHub (https://github.com/IGrok2/monorepo/blob/955a9b9bbed159b99637cf7576482af831acac7d/src/opnieuw/src/main.rs#L380-L388) and I think this PR wouldn't even break it.

fix(server): `max_local_error_reset_streams` function `mut self` -> `&mut self`

---

Cargo.toml
src/proto/h1/conn.rs
src/server/conn/http1.rs

Fixes https://github.com/hyperium/hyper/issues/3825

http1 expose ignore_invalid_headers_in_requests opt

---

.github/workflows/CI.yml

`yq` can be used to get values from TOML file.

chore(ci): use yq to get rust-version in manifest

---

src/ext/informational.rs
src/ext/mod.rs
src/ffi/http_types.rs
src/proto/h1/conn.rs
src/proto/h1/io.rs
src/proto/h1/mod.rs
src/proto/h1/role.rs
tests/client.rs

This new function allows attaching a callback to a request, such that when it is sent through a hyper client connection, and any 1xx informational responses are received, they are passed to the callback.
Closes #2565
---
This takes the unstable client informational feature (introduced in #2594, tracking issue in #2565), and promotes it to a stable API. The way it works is largely the same: a user can embed a callback in an extension in a request, and if present, it is called with each 1xx response parsed for that request.
As long as it was working in an unstable manor for curl, we didn't really discuss further if it is particularly *rusty*. I welcome feedback to that effect.
- **ResponseFuture::poll_informational()** - I'll note that in the tracking issue, it was discussed that an …

feat(ext): add `ext::on_informational()` callback extension

---

src/ffi/task.rs

chore: remove redundant backticks

---

src/body/incoming.rs

Running `cargo test` fails to compile because tests rely on types which are behind a #[cfg(…)] which is disabled by default.
Add a #[cfg(…)] directive to tests which rely on types which are also behind a #[cfg(…)] directive, so that these tests run only if the types on which they depend exist.

Gate tests with features they test

---

src/service/http.rs
src/service/service.rs

this commit introduces some additional documentation to the `HttpService` trait, and the `Service` trait.
notably, this commit introduces some intradoc links, so that rustdoc will render links to types like `http::Request` and `http::Response`, or to the `Body` trait.
additionally, mention of `hyper-util` is added to the `Service` trait, to direct users to the glue implementations that they will likely need to interact with e.g. `tower`.

docs(service): add `HttpService` documentation

---

examples/http_proxy.rs

```rust
type ClientBuilder = hyper::client::conn::http1::Builder;
type ServerBuilder = hyper::server::conn::http1::Builder;
```
This pull request includes changes to the `examples/http_proxy.rs` file to improve code readability and maintainability by introducing type aliases for the `hyper::client::conn::http1::Builder` and `hyper::server::conn::http1::Builder` types.
Code readability and maintainability improvements:
* [`examples/http_proxy.rs`](diffhunk://#diff-10b438215a36b6a0fe2edd8a018e21c782cf85c57bb98aca060941e45beef7a4L7-L8): Removed direct usage of `hyper::client::conn::http1::Builder` and `hyper::server::conn::http1::Builder` in favor of type aliases `ClientBuilder` and `ServerBuilder`. 
It's confusing for beginners to read this two lines. …

docs(examples): alias Builder for clarity

---

src/proto/h2/ping.rs

`proto::h2::ping` has some documentation that won't be rendered properly, because it is written as documentation of an item rather than documenting the enclosing submodule.
this commit updates this comment, using `//!` notation.

chore(proto/h2): fix module-level documentation

---

src/client/dispatch.rs

this commit introduces a new inherent method to
`hyper::client::conn::TrySendError<T>`.
this error type includes a `TrySendError::take_message()` method today that will return an owned instance of the inbound message, should the underlying dispatch have been closed before serialization of the message ever began.
this commit introduces a new method that allows callers to inspect the message, e.g. to update metrics, without needing to take ownership of the message.

feat(client): add a `TrySendError::message()` method

---

src/error.rs
src/proto/h2/client.rs

fixes #3858 : add error type for http/2 connect requests with non-zero body.

fix(http2): add decriptive error for non-zero connect request

---

Cargo.toml
src/body/incoming.rs
src/client/conn/http1.rs
src/client/conn/http2.rs
src/client/dispatch.rs
src/common/either.rs
src/common/future.rs
src/common/mod.rs
src/common/task.rs
src/common/time.rs
src/common/watch.rs
src/proto/h1/conn.rs
src/proto/h1/decode.rs
src/proto/h1/dispatch.rs
src/proto/h1/io.rs
src/proto/h2/client.rs
src/proto/h2/mod.rs
src/proto/h2/server.rs
src/server/conn/http1.rs
src/server/conn/http2.rs

Make hyper usable for h1/h2 and client/server without this heavyweight dependency. It's about 17k lines of code and takes up to 1.7 seconds to compile on my machine, but hyper is only using a tiny fraction of it. Larger applications probably still pull in futures-util by other means, but it's no longer as unavoidable as in the early days of the ecosystem.
To remove futures-util without raising MSRV, I took these steps:
* When futures-util just re-exports something from its dependencies, use it directly from the source.
* Inline trivial helpers like `poll_unpin` that "only" communicate intent a little better but don't save any significant amount of code.
* Refactor the h2 client code to avoid `StreamFuture` for the "Client has been dropped" detection -- just poll the mpsc channel directly. …

refactor(lib): drop futures-util except in ffi

---

src/common/date.rs

`CachedDate` gets updated every second, but the current logic doesn't take into account milliseconds and nanoseconds - if the application starts at `12:00:00.600`, hyper will report `date: ...T120000` up until `12:00:01.600`, which is overzealous.
We can sidestep this by subtracting the nanoseconds part (which includes milliseconds) from the time passed to `CachedDate::update()`, essentially rounding `self.next_update` to the beginning of the next closest second.

fix(date): improve caching accuracy

---

src/error.rs

Benchmarking tools often cause connections to be ungracefully shutdown.
This makes it possible to filter these errors out.
Replaces #2745

feat: add Error::is_shutdown()

---

Cargo.toml

Fix a mistake in commit e11b2ad (PR #3890): use the 'dep:' syntax for futures-util, so that Cargo won't implicitly create a feature called 'futures-util'. Removing features is semver-breaking, but said commit hasn't been in any release yet, so it can still be fixed now.

fix(lib): avoid implicit cargo feature

---

src/server/conn/http1.rs

Adds an `allow_multiple_spaces_in_request_line_delimiters` config method to the http1 server `Builder` as requested in #3923

feat(http1): add allow_multiple_spaces_in_request_line_delimiters h1 builder config method

---

src/ffi/macros.rs

- Eliminates deprecation warnings
- Follows modern Rust best practices
- Prevents potential issues with ABI compatibility across different compilers and platforms

refactor(ffi): specify "C" ABI explicitly in ffi_fn! macro

---

tests/client.rs

see https://github.com/hyperium/hyper/issues/3896.
this commit ports an assortment of test cases for the client to an in-memory socket using `tokio::io::duplex()`.
this should help reduce test flakes related to TCP close behavior.
this supersedes https://github.com/hyperium/hyper/pull/3946.

fix(client): port tests to in-memory socket
